---
title: "Application to 2016 Election Data"
output: 
  pdf_document:
    keep_tex: true
header-includes:
  - \usepackage{stackengine}
  - \usepackage{rotating}
---

```{r setup, include=FALSE}
rm(list = ls())
## WEIGHTING A 2016 PRE-ELECTION SURVEY

### Packages
library(tidyverse)
library(survey)
library(knitr)
library(kableExtra)

#devtools::install_github("chadhazlett/KBAL", ref = "master") 
library(kbal)
```


```{r setup_params}

## Erin's path
path_data = "~/Dropbox/Documents/2019__2020/work/kpop/2016_reweighting_example/data/"
```

```{r useful_functions}
vote_contrast <- quote((recode_vote_2016Democrat - recode_vote_2016Republican) /
                           (recode_vote_2016Democrat + recode_vote_2016Republican))

### Function for creating targets from auxiliary information and formula
create_targets <- function (target_design, target_formula) {
    target_mf <- model.frame(target_formula, model.frame(target_design))
    target_mm <- model.matrix(target_formula, target_mf)
    wts <- weights(target_design)
    colSums(target_mm * wts) / sum(wts)
}

```

## Load Data

```{r}
## SURVEY DATA (PEW)
### Load
###This needs to be loaded from dropbox/local not github bc it's too big
pew <- readRDS(paste0(path_data, "pew.rds"))

## AUXILIARY INFORMATION (CCES)
### Load
#This needs to be loaded from dropbox/local not github bc it's too big
cces <- readRDS(paste0(path_data, "cces.rds"))
### Drop invalid cases
cces <- cces %>%
    filter((CC16_401 == "I definitely voted in the General Election.") &
               !is.na(commonweight_vv_post))

## make white_pid column
cces <- cces %>%
  mutate(recode_white_pid = case_when(recode_race == "White" ~ recode_pid_3way,
                               TRUE ~ "No Split"))

pew <- pew %>%
  mutate(recode_white_pid = case_when(recode_race == "White" ~ recode_pid_3way,
                               TRUE ~ "No Split"))

### Actual results
pres <- readRDS(paste0(path_data, "election.rds"))

natl_margin <- pres %>%
    summarise(margin = (sum(demtotal) - sum(reptotal)) /
                  (sum(demtotal) + sum(reptotal))) %>%
    as.numeric()
natl_margin
```

```{r define_models}
formula_rake_demos_noeduc <- ~recode_age_bucket + recode_female + recode_race + recode_region + recode_pid_3way
formula_rake_demos_weduc <- ~recode_age_bucket + recode_female + recode_race + recode_region + 
    recode_educ + recode_pid_3way
formula_ps <- ~recode_age_3way + recode_female + recode_race +
    recode_region + recode_educ_3way + recode_pid_3way
#add interaction with pid
formula_retrospective <- ~recode_age_bucket:recode_pid_3way + recode_female:recode_pid_3way+
    recode_race_educ_reg:recode_pid_3way
```

```{r make_svydesign}
## Find Missing Strata
## Make "strata" variable in CCES and Pew
cces <- bind_cols(cces, cces %>% 
                    unite("strata", all.vars(formula_ps), remove = FALSE) %>%
                    unite("strata_wage", c(all.vars(formula_ps), "recode_age"), remove = FALSE) %>%
                    select(strata, strata_wage))

pew <- bind_cols(pew, pew %>% 
                   unite("strata", all.vars(formula_ps), remove = FALSE) %>%
                   unite("strata_wage", c(all.vars(formula_ps), "recode_age"), remove = FALSE) %>%
                   select(strata, strata_wage))


missing_strata <- unique(cces$strata)[!(unique(cces$strata) %in% unique(pew$strata))]

## recode missing age
pew$recode_age[is.na(pew$recode_age)] <- mean(pew$recode_age, na.rm = TRUE)
cces$recode_age[is.na(cces$recode_age)] <- mean(cces$recode_age, na.rm = TRUE)

### Make survey designs

## For Pew, since there are no design weights, assume SRS
pew_srs <- svydesign(ids = ~1, data = pew)
cces_awt <- svydesign(ids = ~1, weights = ~commonweight_vv_post, data = cces)
```

```{r population_targets}
### Population targets
targets_rake_demos_noeduc <- create_targets(cces_awt, formula_rake_demos_noeduc)
targets_rake_demos_weduc <- create_targets(cces_awt, formula_rake_demos_weduc)
targets_retrospective <- create_targets(cces_awt, formula_retrospective)
```

```{r do_calibration}

## Raking on demographics, excluding education
rake_demos_noeduc <- calibrate(design = pew_srs,
                       formula = formula_rake_demos_noeduc,
                       population = targets_rake_demos_noeduc,
                       calfun = "raking")

rake_demos_noeduc <- svydesign(~1, data = pew, weights = weights(rake_demos_noeduc))

## Raking on demographics, including education
rake_demos_weduc <- calibrate(design = pew_srs,
                              formula = formula_rake_demos_weduc,
                              population = targets_rake_demos_weduc,
                              calfun = "raking")

rake_demos_weduc <- svydesign(~1, data = pew, weights = weights(rake_demos_weduc))

## Post-stratification
targets_ps <- svytable(formula = ~strata, design = subset(cces_awt, !(strata %in% missing_strata)))
post_stratification <- postStratify(design = pew_srs,
                         strata = ~strata,
                         population = targets_ps)

post_stratification <- svydesign(~1, data = pew, weights = weights(post_stratification))

## Retrospective weighting scheme
rake_retrospective <- calibrate(design = pew_srs,
                              formula = formula_retrospective,
                              population = targets_retrospective,
                              calfun = "raking",
                              force = TRUE)

rake_retrospective <- svydesign(~1, data = pew, weights = weights(rake_retrospective))
```

```{r kpop}
#############################################
##### PUT FINAL KPOP CODE HERE
#############################################

load("./cleaned data/Full SVD/weights_wPid_full.Rdata")

kpop <- svydesign(~1, data = pew, weights = wts_wPid[, "wtkbal_b.5x"])
kpop_mf <- svydesign(~1, data = pew, weights = wts_wPid[, "wtkbal_mf_b2x"])
```

```{r check_margins}
margin_summary <- round(cbind(cces = svymean(formula_rake_demos_weduc, cces_awt),
            rake_demos_noeduc = svymean(formula_rake_demos_weduc, rake_demos_noeduc),
            rake_demos_weduc = svymean(formula_rake_demos_weduc, rake_demos_weduc),
            post_stratification = svymean(formula_rake_demos_weduc, post_stratification),
            rake_retrospective = svymean(formula_rake_demos_weduc, rake_retrospective),
            kpop = svymean(formula_rake_demos_weduc, kpop),
            kpop_mf = svymean(formula_rake_demos_weduc, kpop_mf)) * 100, 1) %>%
  data.frame() %>%
  rownames_to_column() %>%
  mutate(variable = case_when(str_detect(rowname, "age") ~ "4-way Age Bucket",
                             str_detect(rowname, "female") ~ "Gender",
                             str_detect(rowname, "race") ~ "Race/Ethnicity",
                             str_detect(rowname, "region") ~ "Region",
                             str_detect(rowname, "educ") ~ "Education Level",
                             str_detect(rowname, "pid") ~ "Party Identification",
                             TRUE ~ "Empty"),
         level = gsub("recode_|age_bucket|female|race|region|educ|pid_3way", "", rowname)) %>%
  select(level, everything(), -rowname, -variable)
```

```{r margins_table, echo = FALSE, results = 'asis'}
margin_summary %>%
  mutate(level = str_replace(level, "graduate", "")) %>%
  kable(format = "latex", booktabs = T,
        col.names = linebreak(c("", "\\belowbaseline[0ex]{\\rotatebox{90}{\\parbox{1.1in}{\\raggedright{Target (CCES)}}}}", 
                                "\\belowbaseline[0ex]{\\rotatebox{90}{\\parbox{1.1in}{\\raggedright{Raking \\\\Demographics No Education }}}}",
                                "\\belowbaseline[0ex]{\\rotatebox{90}{\\parbox{1.1in}{\\raggedright{Raking \\\\Demographics with Education }}}}",
                                "\\belowbaseline[0ex]{\\rotatebox{90}{\\parbox{1.1in}{\\raggedright{Post-Stratification}}}}", 
                                "\\belowbaseline[0ex]{\\rotatebox{90}{\\parbox{1.1in}{\\raggedright{Raking Retrospective}}}}", 
                                "\\belowbaseline[0ex]{\\rotatebox{90}{\\parbox{1.1in}{\\raggedright{Kpop}}}}", 
                                "\\belowbaseline[0ex]{\\rotatebox{90}{\\parbox{1.1in}{\\raggedright{Kpop Mean First}}}}")), escape = FALSE,
        caption = "Marginal distribution of important demographics under different weighting models.") %>%
  column_spec(2:ncol(margin_summary), width = "0.5in") %>%
  column_spec(1, width = "1.35in") %>%
  kable_styling() %>%
  pack_rows("4-way Age Bucket", 1, 4, latex_gap_space = "0.5em") %>%
  pack_rows("Gender", 5, 6, latex_gap_space = "0.5em") %>%
  pack_rows("Race/Ethnicity", 7, 10, latex_gap_space = "0.5em") %>%
  pack_rows("Region", 11, 14, latex_gap_space = "0.5em") %>%
  pack_rows("Education Level", 15, 20, latex_gap_space = "0.5em") %>%
  pack_rows("Party Identification", 21, 23, latex_gap_space = "0.5em")
```

```{r make_results}
target_margin <- svycontrast(svymean(~recode_vote_2016, cces_awt, na.rm = TRUE),
                       vote_contrast)[1]

comp_df <- data.frame(
    cces = svycontrast(svymean(~recode_vote_2016, cces_awt, na.rm = TRUE),
                       vote_contrast),
    unweighted = svycontrast(svymean(~recode_vote_2016, pew_srs, na.rm = TRUE),
                        vote_contrast),
    rake_demos_noeduc = svycontrast(svymean(~recode_vote_2016, rake_demos_noeduc, na.rm = TRUE),
                        vote_contrast),
    rake_demos_weduc = svycontrast(svymean(~recode_vote_2016, rake_demos_weduc, na.rm = TRUE),
                        vote_contrast),
    post_stratification = svycontrast(svymean(~recode_vote_2016, post_stratification, na.rm = TRUE),
                        vote_contrast),
    rake_retrospective = svycontrast(svymean(~recode_vote_2016, rake_retrospective, na.rm = TRUE),
                        vote_contrast),
    kpop = svycontrast(svymean(~recode_vote_2016, kpop, na.rm = TRUE),
                        vote_contrast),
    kpop_mf = svycontrast(svymean(~recode_vote_2016, kpop_mf, na.rm = TRUE),
                        vote_contrast)) %>%
    pivot_longer(cols = everything(),
                 names_to = c("source", ".value"), 
                 names_pattern = "(.*)\\.(.*)") %>%
    rename(est = nlcon) %>%
    mutate(est = est * 100,
           SE = SE * 100,
           err_target = est - target_margin * 100,
           source = str_replace(source, "_", " "),
           source_name = factor(source, labels = c("Target (CCES)", 
                                              "KPop", 
                                              "KPop + Mean First",
                                              "Post-Stratification", 
                                              "Raking\nDemographics (no Education)", 
                                              "Raking\nDemographics w/ Education", 
                                              "Raking\nRetrospective", 
                                              "Pew\nUnweighted"),
                           ordered = TRUE))

comp_df
```

```{r plot_results}
comp_df %>%
    ggplot() +
    aes(x = source_name, y = est, ymin = est - 1.96*SE, ymax = est + 1.96*SE) +

    geom_hline(yintercept = c(0, natl_margin, comp_df$est[comp_df$source == "cces"]),
               linetype = c("solid", "dashed", "longdash"),
               color = c("black", "gray60", "black")) +
    geom_pointrange() +
    scale_y_continuous(breaks = c(natl_margin, seq(-.05, .1, .05)),
                       minor_breaks = NULL,
                       labels = scales::percent_format()) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +

    labs(x = NULL, y = "Estimated Margin (95% CI)") +
    ggtitle("Estimates of Clinton National Popular Vote Margin") +
    theme(axis.text.x = element_text(angle = 55, hjust = 1)) +
    annotate(geom = "text", x = 8.65, y = natl_margin, label = " True\n National\n Margin", hjust = 0, angle = -90, color = "gray60", size = 3.5) +
    annotate(geom = "text", x = 8.55, y = comp_df$est[comp_df$source == "cces"], label = " CCES Estimated\n Margin", hjust = 0, angle = 90, size = 3.5) +
    theme(legend.title = element_blank()) +
  scale_x_discrete(limits=comp_df$source_name, expand = expansion(0, 1.2))
```

```{r save_plot}
ggsave("./plots/weighted_pew_results.pdf", width = 6, height = 4)
```