---
title: 'Application: XGB Modeled'
output:
  pdf_document: default
editor_options: 
  chunk_output_type: console
---


```{r setup, include = F}
#rm(list = ls())
knitr::opts_chunk$set(echo = TRU
set.seed(9345876)

### Packages
library(MASS)
library(tidyverse)
library(survey)
library(kbal)
library(parallel)
library(knitr)
library(kableExtra)
library(glmnet)
library(xgboost)
library(caret)
```



```{r load_data}

path_data= "/Users/Ciara/Dropbox/kpop/application/data/"
# path_kbalruns = "/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/"

# AUXILIARY INFORMATION (CCES)
cces <- readRDS(paste0(path_data, "cces_new.rds"))

### Drop invalid cases
##### SOON DROP NAS
cces <- cces %>%
    filter((CC16_401 == "I definitely voted in the General Election.") &
               !is.na(commonweight_vv_post) 
               ) %>% 
    mutate(commonweight_vv_post = commonweight_vv_post/ mean(commonweight_vv_post))

cces <- cces %>% mutate(recode_attndch_bin = 
                            factor(ifelse(recode_attndch_4way== "Never", "No", "Yes")))

#ALL KPOP RESULTS ARE WITH THESE INCLUDED
# cces <- cces %>%
#     filter(!is.na(recode_vote_2016))
```


```{r setup_targets}


formula_rake_demos_noeduc <- ~recode_age_bucket + recode_female + recode_race + 
    recode_region + recode_pid_3way

#should this be 3way or 6 way education?
formula_rake_demos_weduc <- ~recode_age_bucket + recode_female + 
    recode_race + recode_region + recode_educ_3way + recode_pid_3way

formula_rake_all_vars <- ~recode_age_bucket + recode_female + 
    recode_race + recode_region + recode_pid_3way + recode_educ +
    recode_income_5way + recode_relig_6way + recode_born + recode_attndch_4way


formula_ps <- ~recode_age_3way + recode_female + recode_race +
    recode_region + recode_educ_wh_3way + recode_pid_3way

formula_ps_reduc <- ~recode_age_3way + recode_female + 
    recode_race + recode_region + recode_pid_3way  +
    recode_income_3way + recode_born + recode_educ_wh_3way

#let's coarsen income and religion and attend church:

formula_ps_all <- ~recode_age_3way + recode_female + 
    recode_race + recode_region + recode_pid_3way + recode_educ_3way +
    recode_income_3way + recode_relig_6way + recode_born + recode_attndch_bin


formula_retrospective <- ~recode_age_bucket:recode_pid_3way + 
    recode_female:recode_pid_3way+ recode_race_educ_reg:recode_pid_3way

### set up some functions for convenient estimates
vote_contrast <- quote((recode_vote_2016Democrat - recode_vote_2016Republican) /
                               (recode_vote_2016Democrat + recode_vote_2016Republican))

vote_diff <- quote((recode_vote_2016Democrat - recode_vote_2016Republican) /(recode_vote_2016Democrat + recode_vote_2016Republican + recode_vote_2016Other)) 


#### Build Strata For PS
cces <- bind_cols(cces, cces %>% 
                      unite("strata", all.vars(formula_ps), remove = FALSE) %>%
                         unite("strata_reduc", all.vars(formula_ps_reduc), 
                               remove = FALSE) %>%
                         unite("strata_all", all.vars(formula_ps_all)) %>%
                      dplyr::select(strata, strata_reduc, strata_all))




# Make survey designs 
#cces_awt <- svydesign(ids = ~1, weights = ~commonweight_vv_post, data = cces)

#cces_nowt <- svydesign(ids = ~1,  data = cces)


#make targets
create_targets <- function (target_design, target_formula) {
    target_mf <- model.frame(target_formula, model.frame(target_design))
    target_mm <- model.matrix(target_formula, target_mf)
    wts <- weights(target_design)
    colSums(target_mm * wts) / sum(wts)
}

```




## XGB PEW FUNCT

```{r xgb_pew_funct}
pew_out <- function(PRE = TRUE,
                    age_buckets = FALSE, 
                    popw = FALSE,
                    three_way = TRUE,
                    noDNK_weights = TRUE, 
                    drop_ccesNAs = TRUE,
                    xgb_cces_mod, 
                    bigB, 
                    smallB,
                    cat_kernel, 
                    display_pew_mod) {
    
    if(!noDNK_weights) {warning("weights with DNK voters not supported well atm",
                                immediate. = T)}
    ####### SURVEY DATA (PEW) ####
    if(PRE) {
        pew <- readRDS(paste0(path_data, "pew_new.rds"))
        # #in pre: eliminate don't know plan to vote respondents:
        pew <- pew %>%
            filter(plan1 %in% c("Plan to vote", "Already voted"))
    } else {
        age_buckets = FALSE
        warning("with postwave, kpop weights are currently only without age buckets",
                immediate. = TRUE)
        pew <- readRDS(paste0(path_data, "pew_post_CS_q4.rds"))
    }
    
    pew <- pew %>% mutate(recode_attndch_bin = 
                            factor(ifelse(recode_attndch_4way== "Never", "No", "Yes")))
    
    pew <- bind_cols(pew, pew %>% 
                         unite("strata", all.vars(formula_ps), remove = FALSE) %>%
                         unite("strata_reduc", all.vars(formula_ps_reduc), 
                               remove = FALSE) %>%
                         unite("strata_all", all.vars(formula_ps_all)) %>%
                         dplyr::select(strata, strata_reduc, strata_all))

    #these are the strata in the population but not in the sample
    if(drop_ccesNAs) {
        cces <- cces %>% filter(!is.na(recode_vote_2016))
        if(!noDNK_weights) { warning("noDNK_weights must be true with no cces NAs",
                                     immediate. = T)}
        if(age_buckets) { warning("age_buckets must be true with no cces NAs",
                                     immediate. = T)}
        if(popw) { warning("POPW must be false with no cces NAs",
                                     immediate. = T)}
        noDNK_weights = TRUE
        age_buckets = FALSE
        popw = FALSE
    }
    
    
    ##### RUN XGB on PEW ##################
    
    #this subsets cces strata to only those in pew
    missing_strata <- unique(cces$strata)[!(unique(cces$strata) %in%
                                                unique(pew$strata))]
    length(missing_strata)/ length(unique(cces$strata))
    missing_strata_reduc <- unique(cces$strata_reduc)[!(unique(cces$strata_reduc) %in%
                                                unique(pew$strata_reduc))]
    length(missing_strata_reduc)/ length( unique(cces$strata_reduc))
    missing_strata_all <- unique(cces$strata_all)[!(unique(cces$strata_all) %in%
                                                unique(pew$strata_all))]
    length(missing_strata_all)/ length( unique(cces$strata_all))
    
    #we also have the reverse where pew may have strata we don't have in cces
    #this arises if we eliminate NAs in recode_vote for cces
    #this ofc would never happen if cces was a true full pop but it's actually just
    #a much bigger sample so it can happen
     problem <- unique(pew$strata)[!(unique(pew$strata) %in%
                                                   unique(cces$strata))]
     problem_reduc <- unique(pew$strata_reduc)[!(unique(pew$strata_reduc) %in%
                                                   unique(cces$strata_reduc))]
     length(problem_reduc)
     problem_all <- unique(pew$strata_all)[!(unique(pew$strata_all) %in%
                                                   unique(cces$strata_all))]
     length(problem_all)
     if(length(problem) != 0) {
     warning(paste("NB: strata present in pew not in cces (3way)will be dropped in ps:\n",
                   problem, 
                   "\nrepresenting", nrow(pew %>% filter(strata %in% problem)),
                   "/", nrow(pew), "\n"), immediate. = TRUE)
     }
     if(length(problem_reduc) != 0) {
     warning(paste("NB: strata present in pew not in cces (3way)will be dropped in ps:\n",
                   "\nrepresenting", nrow(pew %>% filter(strata_reduc %in%
                                                             problem_reduc)),
                   "/", nrow(pew), "\n"), immediate. = TRUE)
     }
     if(length(problem_all) != 0) {
     warning(paste("NB: strata present in pew not in cces (3way)will be dropped in ps:\n",
                   "\nrepresenting", nrow(pew %>% filter(strata_all %in% problem_all)),
                   "/", nrow(pew), "\n"), immediate. = TRUE)
     }
    # need to actually drop it from pew for ps and all that to run correctly
    #note this also means we need to go and drop it from the kpop weights so 
    #i will keep track of the index
    #problem_index <- which(pew$strata %in% problem)
    #
    
    if(three_way) {
        pew_model_dat = pew
        classes = 3
    } else {
        pew_model_dat = pew[pew$recode_vote_2016 != "Other",]
        classes = 2
    }
    pew_outcome = pew_model_dat$recode_vote_2016
    pew_out_int <- as.integer(as.factor(pew_outcome))-1
    
    pew_matrix_sparse <- pew_model_dat %>%
        dplyr::select(recode_age,
               recode_female,
               recode_race,
               recode_region,
               recode_pid_3way,
               recode_educ,
               recode_income,
               #recode_relig has 38 Nas so need to use buckets
               recode_relig_6way,
               recode_born,
               #recode_attndch has some nas need to use buckegs
               recode_attndch_4way,
               recode_race_educ_reg) %>%
        sparse.model.matrix(as.formula("~."), .)
    
    pew_matrix_sparse = pew_matrix_sparse[,-1]
    
    
    pew_percent <- sample.int(nrow(pew_model_dat), (nrow(pew_model_dat)/10)*8)
    pew_dat_xgb_train <- xgb.DMatrix(data = pew_matrix_sparse[pew_percent,], 
                                     label = pew_out_int[pew_percent])
    pew_dat_xgb_outofsamp <- xgb.DMatrix(data =
                                             pew_matrix_sparse[-pew_percent,], 
                                         label = pew_out_int[-pew_percent])
    
    #using the same params as cces:
    params = list(
        booster="gbtree",
        eta=0.3,
        max_depth=10,
        min_child_weight = 4,
        gamma=3,
        subsample= 0.7,
        colsample_bytree=1,
        objective="multi:softprob",
        num_class= classes,
        eval_metric = "merror"
        )
    pew_xgbcv <- xgb.cv( params = params,
                         data = pew_dat_xgb_train, 
                         nrounds = 500,
                         nfold = 5, 
                         early_stopping_rounds = 50,
                         showsd = T, 
                         stratified = T, 
                         print_every_n = 10, 
                         early_stop_round = 20, 
                         maximize = F)
    
    low_test  = which(pew_xgbcv$evaluation_log$test_merror_mean ==
                          min(pew_xgbcv$evaluation_log$test_merror_mean))
    low_test
    pew_xgbcv$best_iteration
    
    #run
    xgb_pew =xgb.train(params=params,
                       data=pew_dat_xgb_train,
                       nrounds= pew_xgbcv$best_iteration,
                       watchlist = list(validation = pew_dat_xgb_outofsamp),
                       nthreads=2,
                       print_every_n = 10)
    
    
    pew_xgb_outcome = predict(xgb_pew, pew_dat_xgb_train, reshape=T)
    pew_xgb_outofsamp = predict(xgb_pew, pew_dat_xgb_outofsamp, reshape =T)
    
    #getting outcome with max prob
    pew_xgb_plurality_train <- apply(pew_xgb_outcome,1, which.max)
    pew_xgb_plurality_test <- apply(pew_xgb_outofsamp,1, which.max)
    
    sum(pew_xgb_plurality_train -1 == 
            pew_out_int[pew_percent])/length(pew_out_int[pew_percent])
    sum(pew_xgb_plurality_test - 1 == 
            pew_out_int[-pew_percent])/length(pew_out_int[-pew_percent])
    #rep = 2, dem = 0 other = 1
    if(three_way) {
         pew_xgb_train_char = factor(case_when(pew_xgb_plurality_train == 1
                                               ~ "Democrat",
                                          pew_xgb_plurality_train  == 3 
                                          ~ "Republican",
                                          pew_xgb_plurality_train  == 2 
                                          ~ "Other"),
                                levels = c("Democrat", "Other", "Republican"))
    
         pew_xgb_test_char = factor(case_when(pew_xgb_plurality_test  == 1 
                                              ~ "Democrat",
                                         pew_xgb_plurality_test  == 3 
                                         ~ "Republican",
                                         pew_xgb_plurality_test  == 2 
                                         ~ "Other"), 
                               levels = c("Democrat", "Other", "Republican"))
    } else {
        pew_xgb_train_char = factor(case_when(pew_xgb_plurality_train-1  == 0 
                                              ~ "Democrat",
                                            pew_xgb_plurality_train-1  == 1 
                                            ~ "Republican"),
                            levels = c("Democrat", "Republican"))


        pew_xgb_test_char = factor(case_when(pew_xgb_plurality_test-1  == 0 ~ "Democrat",
                                            pew_xgb_plurality_test-1  == 1 ~ "Republican"), 
                           levels = c("Democrat", "Republican"))
    }
   
    #check
    sum(pew_xgb_train_char == pew_outcome[pew_percent])/length(pew_percent)
    sum(pew_xgb_test_char == pew_outcome[-pew_percent])/length(pew_outcome[-pew_percent])
    
    pew_conf_train = confusionMatrix(as.factor(pew_xgb_train_char), 
                                as.factor(pew_model_dat$recode_vote_2016)[pew_percent])
    
    pew_conf_test = confusionMatrix(pew_xgb_test_char, 
                                as.factor(pew_model_dat$recode_vote_2016)[-pew_percent])
    cat("Confusion Matrix: Pew on Pew Training\n")
    print(t(t(pew_conf_train$table)/colSums(pew_conf_train$table)))
    cat("Confusion Matrix: Pew on Pew Testing\n")
    print(t(t(pew_conf_test$table)/colSums(pew_conf_test$table)))
    
    
    ########  PREDICTING XBG CCES OUTCOME ###############
    #need full pew in case this is two way
    pew_matrix_all <- pew %>%
        dplyr::select(recode_age,
               recode_female,
               recode_race,
               recode_region,
               recode_pid_3way,
               recode_educ,
               recode_income,
               #recode_relig has 38 Nas so need to use buckets
               recode_relig_6way,
               recode_born,
               #recode_attndch has some nas need to use buckegs
               recode_attndch_4way,
               recode_race_educ_reg) %>%
        sparse.model.matrix(as.formula("~."), .)
        
    pew_matrix_all = pew_matrix_all[,-1]
    
     #with cces data, predict cces modeled outcome; must use full cces data regardless 
    #of model
    cces_matrix_all <- cces %>%
    dplyr::select(recode_age,
           recode_female,
           recode_race,
           recode_region,
           recode_pid_3way,
           recode_educ,
           recode_income,
           #recode_relig has 38 Nas so need to use buckets
           recode_relig_6way,
           recode_born,
           #recode_attndch has some nas need to use buckegs
           recode_attndch_4way,
           recode_race_educ_reg) %>%
    sparse.model.matrix(as.formula("~."), .)

    cces_matrix_all = cces_matrix_all[,-1]


    
    
    
    ######## PRED ON PEW #######
    ### 1. CCES ON PEW
    xgb_cces_on_pew = predict(xgb_cces_mod, pew_matrix_all, reshape=T)
    xgb_cces_on_pew_plur <- apply(xgb_cces_on_pew,1, which.max)
    sum(xgb_cces_on_pew_plur -1 == pew_out_int)/length(pew_out_int)
    #same thing just with characters to make confusion matrix easier to read
    if(three_way) {
         xgb_cces_on_pew_out <- case_when(xgb_cces_on_pew_plur-1 == 2 ~  "Republican",
                                     xgb_cces_on_pew_plur-1 == 1 ~ "Other", 
                                     xgb_cces_on_pew_plur-1 == 0 ~ "Democrat")
    } else {
        xgb_cces_on_pew_out <- case_when(xgb_cces_on_pew_plur-1 == 1 ~  "Republican",
                                 xgb_cces_on_pew_plur-1 == 0 ~ "Democrat")
    }
    #includes predictions on others forced to be binary in two-way
    #if want only on modeled data use pew_model_dat (makes no difference for three way)
    sum(xgb_cces_on_pew_out == pew$recode_vote_2016)/nrow(pew)
    conf_pew <- confusionMatrix(as.factor(xgb_cces_on_pew_out), 
                                as.factor(pew$recode_vote_2016))
    cat("Confusion Matrix: CCES on Pew (All Data)\n")
    print(t(t(conf_pew$table)/colSums(conf_pew$table)))
    
    ### 2. PEW ON PEW
    #with pew data, predict pew modeled outcome
    xgb_pew_on_pew = predict(xgb_pew, pew_matrix_all, reshape=T)
    xgb_pew_on_pew_plur <- apply(xgb_pew_on_pew,1, which.max)
    #this only works for three waty for two way need to adjust length of xgb_pew_on_pew
    #sum(xgb_pew_on_pew_plur -1 == pew_out_int)/length(pew_out_int)
    
    if(three_way) {
        xgb_pew_on_pew_out <- factor(case_when(xgb_pew_on_pew_plur-1 == 2 ~
                                                   "Republican",
                                           xgb_pew_on_pew_plur-1 == 1 ~ "Other", 
                                           xgb_pew_on_pew_plur-1 == 0 ~ "Democrat"),
                                 levels = c("Democrat", "Other", "Republican"))
    } else {
        xgb_pew_on_pew_out <- factor(case_when(xgb_pew_on_pew_plur-1 == 1 ~  "Republican",
                                       xgb_pew_on_pew_plur-1 == 0 ~ "Democrat"),
                             levels = c("Democrat", "Republican"))
    }
    #evaluating the performance on all pew data
    #for two way this means all those Other will be wrong automatically
    sum(xgb_pew_on_pew_out == pew$recode_vote_2016)/nrow(pew)
    conf_pew_pew <- confusionMatrix(xgb_pew_on_pew_out, 
                                    as.factor(pew$recode_vote_2016))
    cat("Confusion Matrix: Pew on Pew (All Data)\n")
    print(t(t(conf_pew_pew$table)/colSums(conf_pew_pew$table)))
    
    ####### PRED ON CCES ######
    ### 3. PEW on CCES
    xgb_pew_on_cces = predict(xgb_pew, cces_matrix_all, reshape=T)
    xgb_pew_on_cces_plur <- apply(xgb_pew_on_cces,1, which.max)
    #need to run xgb cces first for this to work (out_int definted)
    #sum(xgb_pew_on_cces_plur -1 == out_int)/length(out_int)
    
    if(three_way) {
        xgb_pew_on_cces_out <- factor(case_when(xgb_pew_on_cces_plur-1 == 2 ~
                                             "Republican",
                                     xgb_pew_on_cces_plur-1 == 1 ~ "Other", 
                                     xgb_pew_on_cces_plur-1 == 0 ~ "Democrat"), 
                                      levels = c("Democrat", "Other", "Republican"))
    } else {
        xgb_pew_on_cces_out <- case_when(xgb_pew_on_cces_plur-1 == 1 ~
                                             "Republican",
                                 xgb_pew_on_cces_plur-1 == 0 ~ "Democrat")
    }
    #to get these perecents just use full otucome where NAs are cosidered other
    outcome <- cces$recode_vote_2016
    outcome[is.na(outcome)] <- "Other"
    sum(xgb_pew_on_cces_out == outcome)/length(outcome)
    conf_pew_on_cces <- confusionMatrix(as.factor(xgb_pew_on_cces_out),
                                        as.factor(outcome))
    cat("Confusion Matrix: Pew on CCES (All Data)\n")
    print(t(t(conf_pew_on_cces$table)/colSums(conf_pew_on_cces$table)))
    
    
    #### 4. CCES ON CCES
    #(this could be done outside the function but it's nice to keep it all together for
    #2 and 3 way keeping track)
    ### CCES ON CCES
    xgb_cces_on_cces = predict(xgb_cces_mod, cces_matrix_all, reshape=T)
    
    xgb_cces_on_cces_plur <- apply(xgb_cces_on_cces,1, which.max)
    # sum(xgb_cces_on_cces_plur -1 == out_int)/length(out_int)
    if(three_way) {
       xgb_cces_on_cces_out <- factor(case_when(xgb_cces_on_cces_plur-1 == 2 ~ 
                                                    "Republican",
                                      xgb_cces_on_cces_plur-1 == 1 ~ "Other", 
                                      xgb_cces_on_cces_plur-1 == 0 ~ "Democrat"), 
                                      levels = c("Democrat", "Other", "Republican"))
    } else {
         xgb_cces_on_cces_out <- case_when(xgb_cces_on_cces_plur-1 == 1 ~  "Republican",
                                      xgb_cces_on_cces_plur-1 == 0 ~ "Democrat")
    }
   
    sum(xgb_cces_on_cces_out == outcome)/length(outcome)
    conf_cces_on_cces <- confusionMatrix(as.factor(xgb_cces_on_cces_out),
                                         as.factor(outcome))
    cat("Confusion Matrix: CCES on CCES (All Data)\n")
    print(t(t(conf_cces_on_cces$table)/colSums(conf_cces_on_cces$table)))

    
    ################### POST PROCESS #######################
    #max prob is
    xgb_cces_on_pew_plur <- apply(xgb_cces_on_pew,1, max)
    xgb_pew_on_pew_plur <- apply(xgb_pew_on_pew,1, max)
    
    if(three_way) {
        #prob rep
        xgb_cces_on_pew_pR <- xgb_cces_on_pew[,3]
        xgb_pew_on_pew_pR <- xgb_pew_on_pew[,3]
        
        #prob dem
        xgb_cces_on_pew_pD <- xgb_cces_on_pew[,1]
        xgb_pew_on_pew_pD <-  xgb_pew_on_pew[,1]
        
        #prob other
        xgb_cces_on_pew_pO <- xgb_cces_on_pew[,2]
        xgb_pew_on_pew_pO <-  xgb_pew_on_pew[,2]
    } else {
        #prob rep
        xgb_cces_on_pew_pR <- xgb_cces_on_pew[,2]
        xgb_pew_on_pew_pR <- xgb_pew_on_pew[,2]

        #prob dem
        xgb_cces_on_pew_pD <- xgb_cces_on_pew[,1]
        xgb_pew_on_pew_pD <-  xgb_pew_on_pew[,1]
    }
    
    #individual level margins
    margin_cces_on_pew = (xgb_cces_on_pew_pD - xgb_cces_on_pew_pR)/ 
        (xgb_cces_on_pew_pR + xgb_cces_on_pew_pD)
    margin_pew_on_pew = (xgb_pew_on_pew_pD- xgb_pew_on_pew_pR)/
        (xgb_pew_on_pew_pR + xgb_pew_on_pew_pD)
    #indiv level diff
    diff_cces_on_pew = xgb_cces_on_pew_pD - xgb_cces_on_pew_pR
    diff_pew_on_pew = xgb_pew_on_pew_pD- xgb_pew_on_pew_pR
    
    pew_xgb <- cbind(pew, 
                     xgb_cces_on_pew_out, 
                     xgb_pew_on_pew_out,
                     xgb_cces_on_pew_plur,
                     xgb_pew_on_pew_plur,
                     xgb_cces_on_pew_pR,
                     xgb_pew_on_pew_pR,
                     xgb_cces_on_pew_pD,
                     xgb_pew_on_pew_pD,
                     margin_cces_on_pew,
                     margin_pew_on_pew,
                     diff_cces_on_pew,
                     diff_pew_on_pew) 
 
    if(three_way) {
        pew_xgb <- cbind(pew_xgb, 
                         xgb_cces_on_pew_pO, xgb_pew_on_pew_pO)
    }
    
    pew_srs_xgb <- svydesign(ids = ~1, data = pew_xgb)
    pew_w_srs <-  svydesign(ids = ~1, weights = ~weight, data = pew_xgb)
    
    ### CCES:
    
    #max prob is
    xgb_cces_on_cces_plur <- apply(xgb_cces_on_cces,1, max)
    xgb_pew_on_cces_plur <- apply(xgb_pew_on_cces,1, max)
    
    if(three_way) {
        #prob rep
        xgb_cces_on_cces_pR <- xgb_cces_on_cces[,3]
        xgb_pew_on_cces_pR <- xgb_pew_on_cces[,3]
        
        #prob dem
        xgb_cces_on_cces_pD <- xgb_cces_on_cces[,1]
        xgb_pew_on_cces_pD <-  xgb_pew_on_cces[,1]
        
        #prob dem
        xgb_cces_on_cces_pO <- xgb_cces_on_cces[,2]
        xgb_pew_on_cces_pO <-  xgb_pew_on_cces[,2]
        
    } else {
        #prob rep
        xgb_cces_on_cces_pR <- xgb_cces_on_cces[,2]
        xgb_pew_on_cces_pR <- xgb_pew_on_cces[,2]
        
        #prob dem
        xgb_cces_on_cces_pD <- xgb_cces_on_cces[,1]
        xgb_pew_on_cces_pD <-  xgb_pew_on_cces[,1]
    }
    
    margin_cces_on_cces = (xgb_cces_on_cces_pD - xgb_cces_on_cces_pR)/ 
        (xgb_cces_on_cces_pR + xgb_cces_on_cces_pD)
    margin_pew_on_cces = (xgb_pew_on_cces_pD - xgb_pew_on_cces_pR)/ 
        (xgb_pew_on_cces_pR + xgb_pew_on_cces_pD)
   
    diff_cces_on_cces = xgb_cces_on_cces_pD - xgb_cces_on_cces_pR
    diff_pew_on_cces = xgb_pew_on_cces_pD - xgb_pew_on_cces_pR
    
    cces_xgb <- cbind(cces, 
                      xgb_cces_on_cces_out,
                      xgb_pew_on_cces_out,
                      xgb_cces_on_cces_plur,
                      xgb_pew_on_cces_plur,
                      xgb_cces_on_cces_pD,
                      xgb_pew_on_cces_pD,
                      xgb_cces_on_cces_pR,
                      xgb_pew_on_cces_pR,
                      margin_cces_on_cces,
                      margin_pew_on_cces,
                      diff_cces_on_cces,
                      diff_pew_on_cces)
    if(three_way) {
        cces_xgb <- cbind(cces_xgb, xgb_cces_on_cces_pO, xgb_pew_on_cces_pO)
    }
    
    cces_awt_xgb <- svydesign(ids = ~1, weights = ~commonweight_vv_post, 
                              data = cces_xgb)
    cces_nowt_xgb <- svydesign(ids = ~1, data = cces_xgb)
    
    if(noDNK_weights) {
        
        if(popw) {
            
            targets_rake_demos_noeduc <- create_targets(cces_awt_xgb, 
                                                        formula_rake_demos_noeduc)
            targets_rake_demos_weduc <- create_targets(cces_awt_xgb, 
                                                       formula_rake_demos_weduc)
            targets_rake_all_vars <- create_targets(cces_awt_xgb, 
                                                       formula_rake_all_vars)
            targets_retrospective <- create_targets(cces_awt_xgb,
                                                    formula_retrospective)
            targets_ps <- svytable(formula = ~strata,
                                   design = subset(cces_awt_xgb,
                                                   !(strata %in% missing_strata)))
            targets_ps_reduc <- svytable(formula = ~strata_reduc,
                               design = subset(cces_awt_xgb, !(strata_reduc %in%
                                                                missing_strata_reduc)))
            targets_ps_all <- svytable(formula = ~strata_all,
                               design = subset(cces_awt_xgb, !(strata_all %in%
                                                                missing_strata_all)))
            
            if(age_buckets) {
                
                #this was run WITH CCES  voteNAs because its 47344
                load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/kpop_nodnk_agebuck_wpopw.Rdata")
                weights <- weights_nodnk_agebuckets_wpopw
                clean <- output
                
            } else { # no age buckets + pop weights
                #this was run WITH CCES NAs because its 47344
                load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/kpop_nodnk_fixed.Rdata")
                weights <- weights_nodnk
                clean <- output
            } 
            
        } else { #no pop weights
            targets_rake_demos_noeduc <- create_targets(cces_nowt_xgb, 
                                                        formula_rake_demos_noeduc)
            targets_rake_demos_weduc <- create_targets(cces_nowt_xgb, 
                                                       formula_rake_demos_weduc)
            targets_rake_all_vars <- create_targets(cces_nowt_xgb, 
                                                       formula_rake_all_vars)
            targets_retrospective <- create_targets(cces_nowt_xgb,
                                                    formula_retrospective)
            targets_ps <- svytable(formula = ~strata,
                                   design = subset(cces_nowt_xgb, !(strata %in%
                                                                missing_strata)))
            targets_ps_reduc <- svytable(formula = ~strata_reduc,
                               design = subset(cces_nowt_xgb, !(strata_reduc %in%
                                                                missing_strata_reduc)))
            targets_ps_all <- svytable(formula = ~strata_all,
                               design = subset(cces_nowt_xgb, !(strata_all %in%
                                                                missing_strata_all)))
            if(cat_kernel) {
              
                # load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/allB_cat.Rdata")
                # load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/altB_cat.Rdata")
                # load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/allB_cat_2021-02-25.Rdata")
                #increased tolerance (issue w maxit)
                # load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/allB_cat_parallel_2021-02-26.Rdata")
                #tolerance 1e-6, maxit 500, maxnumdims 500
                load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/allB_cat_par_m500_t1e-06_2021-03-04.Rdata")
               #weights_cat <- weights_cat
                weights <- weights_cat[2:13]
                weights_alt <- weights_cat[1:2]
                #weights_alt <- weights_cat[12:13]
                clean <- out_cat
            }
                
            if(drop_ccesNAs & !cat_kernel) {
                    load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/noNAs_nopopw.Rdata")
                    weights <- weights_nodnk_noNAs_nopopw
                    clean <- out_nopopw_noNAs
    
                    if(bigB) {
                         load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/Working/smallB_nodnk_noNas_nopopw_man.Rdata")
                     clean_smallb <- smallb_out_nopopw_noNAs
                    
                    load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/Working/biggerB_nodnk_noNas_nopopw.Rdata")
                    weights_bigb <- weights_nodnk_noNAs_nopopw
                    clean <- out_nopopw_noNAs
                    clean <- rbind(clean_smallb, clean)
                    }               
            } else if(age_buckets & !cat_kernel) {
                    #thiw was run with cces vote NAs is 47344
                    load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/kpop_nodnk_agebuckets_nopopw.Rdata") #loads weights_nodnk_nopopw
                    weights <- weights_nodnk_nopopw
                    clean <- output
                    
            } else if(!cat_kernel) {
                    #this was run with cces vote Nas is 47344
                    load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/kpop_nodnk_nopopw.Rdata") #loads weights_nodnk_nopopw
                    weights <- weights_nodnk_nopopw
                    clean <- output
            }
            
        } # end of no pop w
    } else { #WITH DNK VOTERS: THIS IS PROBABLY ALL MESSED UP NOW SO LET'S Never USE THIS
        ## XXXXX HAS NOT BEEN FIXED/UPDATED
        #if want weights with dnk voters then we do not have no age bucket option
        #we also don't have no popw option
        if(PRE) {
            age_buckets = FALSE
            popw = FALSE
            warning("with postwave,
                    kpop weights are currently only without age buckets and with popw",
                    immediate. = TRUE)
            load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/kpop_pre_nodnk_app.Rdata")
            out <- kpop_pre_nodnk
            
        } else {
            age_buckets = FALSE
            popw = FALSE
            warning("with postwave,
                    kpop weights are currently only without age buckets and with popw",
                    immediate. = TRUE)
            #NOTE THIS DN HAVE AGE BUCKETS
            load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/kpop_post_q4_app.Rdata")
            out <- kpop_post_q4
        }
        estimates <- lapply(out, `[[`,1) %>% bind_rows()
        estimates[, 2] <- 100*estimates[,2] 
        estimates[, 3] <- 100*estimates[,3] 
        estimates[,6] <- 100*estimates[,6]
        estimates[, 7] <- 100*estimates[,7] 
        estimates[,10] <- 100*estimates[,10]
        estimates[, 11] <- 100*estimates[,11] 
        #sub <- estimates[, c(1,2,4,5,7)]
        colnames(estimates) <- c("b", "kpop_est", "kpop_se",
                                 "bb", "bb ratio", "kpop_conv_est", "kpop_conv_se", 
                                 "bb_conv", "bb ratio_conv",
                                 "kpop_mf_est","kpop_mf_se", "mf_bb","mf_bb_ratio",
                                 "numdims", "numdims_conv", "numdims_mf")
        rownames(estimates) <- c(32,16,8,4,2,1)
        clean <- round(estimates[,c(1,2,5,6,9,10,13,14,15,16)], 3)
        weights <- lapply(out,`[[`,2)
    }
    
    
    ############## PREP FOR PLOT
    ###### Kbal
    #we need to drop the problem unit in pew if there is one note that "pew" has already
    #dropped it but the kbal weights still have them
    kbal_data_sampled <- c(rep(1, nrow(pew)), rep(0, nrow(cces)))
    # #this way we don't ever use the weight for this unit in the survey 
    # kbal_data_sampled[problem_index] <- 0
    
    #laziest way and probably inefficient but whatever
    if(cat_kernel) {
        
         kpop_bmean <- svydesign(~1, data = pew_xgb, 
                                      weights =
                                     weights_alt[[1]]$kpop_w[kbal_data_sampled==1])
         kpop_bmean_conv <- svydesign(~1, data = pew_xgb, 
                                   weights = 
                                       weights_alt[[1]]$kpop_w_conv[kbal_data_sampled==1])
         kpop_mf_bmean <- svydesign(~1, data = pew_xgb, 
                                 weights =
                                     weights_alt[[1]]$kpop_mf_w[kbal_data_sampled==1])
        
         kpop_bmaxvar <- svydesign(~1, data = pew_xgb, 
                                      weights =
                                     weights_alt[[2]]$kpop_w[kbal_data_sampled==1])
         kpop_bmaxvar_conv <- svydesign(~1, data = pew_xgb, 
                                   weights = 
                                       weights_alt[[2]]$kpop_w_conv[kbal_data_sampled==1])
         kpop_mf_bmaxvar <- svydesign(~1, data = pew_xgb, 
                                 weights =
                                     weights_alt[[2]]$kpop_mf_w[kbal_data_sampled==1])
        
         
        
        if(bigB) {
            
            kpop_b128 <- svydesign(~1, data = pew_xgb, 
                                      weights = weights[[7]]$kpop_w[kbal_data_sampled==1])
            kpop_b128_conv <- svydesign(~1, data = pew_xgb, 
                                   weights = 
                                       weights[[7]]$kpop_w_conv[kbal_data_sampled==1])
            kpop_mf_b128 <- svydesign(~1, data = pew_xgb, 
                                 weights =
                                     weights[[7]]$kpop_mf_w[kbal_data_sampled==1])
            
            kpop_b256 <- svydesign(~1, data = pew_xgb, 
                              weights = weights[[8]]$kpop_w[kbal_data_sampled==1])
            kpop_b256_conv <- svydesign(~1, data = pew_xgb, 
                                   weights = 
                                       weights[[8]]$kpop_w_conv[kbal_data_sampled==1])
            kpop_mf_b256 <- svydesign(~1, data = pew_xgb, 
                                 weights =
                                     weights[[8]]$kpop_mf_w[kbal_data_sampled==1])
            
            kpop_b512 <- svydesign(~1, data = pew_xgb, 
                              weights = weights[[9]]$kpop_w[kbal_data_sampled==1])
            kpop_b512_conv <- svydesign(~1, data = pew_xgb, 
                                   weights =
                                weights[[9]]$kpop_w_conv[kbal_data_sampled==1])
            kpop_mf_b512 <- svydesign(~1, data = pew_xgb, 
                                 weights =
                                     weights[[9]]$kpop_mf_w[kbal_data_sampled==1])
            
            kpop_b1024 <- svydesign(~1, data = pew_xgb, 
                              weights = weights[[10]]$kpop_w[kbal_data_sampled==1])
            kpop_b1024_conv <- svydesign(~1, data = pew_xgb, 
                        weights = weights[[10]]$kpop_w_conv[kbal_data_sampled==1])
            kpop_mf_b1024 <- svydesign(~1, data = pew_xgb, 
                                 weights =
                                     weights[[10]]$kpop_mf_w[kbal_data_sampled==1])
            
            kpop_b2048 <- svydesign(~1, data = pew_xgb, 
                              weights = weights[[11]]$kpop_w[kbal_data_sampled==1])
            kpop_b2048_conv <- svydesign(~1, data = pew_xgb, 
                                   weights = 
                            weights[[11]]$kpop_w_conv[kbal_data_sampled==1])
            kpop_mf_b2048 <- svydesign(~1, data = pew_xgb, 
                                 weights =
                                     weights[[11]]$kpop_mf_w[kbal_data_sampled==1])
            
                    
            kpop_b32 <- svydesign(~1, data = pew_xgb, 
                                  weights = weights[[5]]$kpop_w[kbal_data_sampled==1])
            kpop_b16 <- svydesign(~1, data = pew_xgb, 
                                  weights = weights[[4]]$kpop_w[kbal_data_sampled==1])
            kpop_b8 <- svydesign(~1, data = pew_xgb, 
                                 weights = weights[[3]]$kpop_w[kbal_data_sampled==1])
            kpop_b4 <- svydesign(~1, data = pew_xgb, 
                                 weights = weights[[2]]$kpop_w[kbal_data_sampled==1])
            kpop_b2 <- svydesign(~1, data = pew_xgb, 
                                 weights = weights[[1]]$kpop_w[kbal_data_sampled==1])
        }
       
        
        if(smallB) {
             kpop_b64 <- svydesign(~1, data = pew_xgb, 
                              weights = weights[[6]]$kpop_w[kbal_data_sampled==1])
            kpop_b64_conv <- svydesign(~1, data = pew_xgb, 
                                   weights = 
                                       weights[[6]]$kpop_w_conv[kbal_data_sampled==1])
            kpop_mf_b64 <- svydesign(~1, data = pew_xgb, 
                                 weights =
                                     weights[[6]]$kpop_mf_w[kbal_data_sampled==1])
            
            kpop_b32_conv <- svydesign(~1, data = pew_xgb, 
                                       weights = 
                                           weights[[5]]$kpop_w_conv[kbal_data_sampled==1])
            kpop_b16_conv <- svydesign(~1, data = pew_xgb, 
                                       weights =
                                          weights[[4]]$kpop_w_conv[kbal_data_sampled==1])
            kpop_b8_conv <- svydesign(~1, data = pew_xgb, 
                                      weights =
                                          weights[[3]]$kpop_w_conv[kbal_data_sampled==1])
            kpop_b4_conv <- svydesign(~1, data = pew_xgb, 
                                      weights =
                                          weights[[2]]$kpop_w_conv[kbal_data_sampled==1])
            kpop_b2_conv <- svydesign(~1, data = pew_xgb, 
                                      weights =
                                          weights[[1]]$kpop_w_conv[kbal_data_sampled==1])
            
            kpop_mf_b32 <- svydesign(~1, data = pew_xgb, 
                                     weights =
                                         weights[[5]]$kpop_mf_w[kbal_data_sampled==1])
            kpop_mf_b16 <- svydesign(~1, data = pew_xgb, 
                                     weights =
                                         weights[[4]]$kpop_mf_w[kbal_data_sampled==1])
            kpop_mf_b8 <- svydesign(~1, data = pew_xgb, 
                                    weights =
                                        weights[[3]]$kpop_mf_w[kbal_data_sampled==1])
            kpop_mf_b4 <- svydesign(~1, data = pew_xgb, 
                                    weights =
                                        weights[[2]]$kpop_mf_w[kbal_data_sampled==1])
            kpop_mf_b2 <- svydesign(~1, data = pew_xgb, 
                                    weights =
                                        weights[[1]]$kpop_mf_w[kbal_data_sampled==1])
        }
       
        
        # kpop_cat = svydesign(~1, data = pew_xgb,
        #                           weights = weights_cat[[1]]$kpop_w[kbal_data_sampled==1])
        # kpop_cat_conv = svydesign(~1, data = pew_xgb,
        #                           weights = weights_cat[[1]]$kpop_w_conv[kbal_data_sampled==1])
        # kpop_cat_mf <- svydesign(~1, data = pew_xgb,
        #                              weights =
        #                                  weights_cat[[1]]$kpop_mf_w[kbal_data_sampled==1])
        
        
    } else if(drop_ccesNAs) {
            i = 2
            kpop_b64 <- svydesign(~1, data = pew_xgb, 
                              weights = weights[[1]]$kpop_w[kbal_data_sampled==1])
            kpop_b64_conv <- svydesign(~1, data = pew_xgb, 
                                   weights = 
                                       weights[[1]]$kpop_w_conv[kbal_data_sampled==1])
            kpop_mf_b64 <- svydesign(~1, data = pew_xgb, 
                                 weights =
                                     weights[[1]]$kpop_mf_w[kbal_data_sampled==1])
            if(bigB) {
                kpop_b128 <- svydesign(~1, data = pew_xgb, 
                                  weights = weights_bigb[[2]]$kpop_w[kbal_data_sampled==1])
                kpop_b128_conv <- svydesign(~1, data = pew_xgb, 
                                       weights = 
                                           weights_bigb[[2]]$kpop_w_conv[kbal_data_sampled==1])
                kpop_mf_b128 <- svydesign(~1, data = pew_xgb, 
                                     weights =
                                         weights_bigb[[2]]$kpop_mf_w[kbal_data_sampled==1])
                
                kpop_b256 <- svydesign(~1, data = pew_xgb, 
                                  weights = weights_bigb[[3]]$kpop_w[kbal_data_sampled==1])
                kpop_b256_conv <- svydesign(~1, data = pew_xgb, 
                                       weights = 
                                           weights_bigb[[3]]$kpop_w_conv[kbal_data_sampled==1])
                kpop_mf_b256 <- svydesign(~1, data = pew_xgb, 
                                     weights =
                                         weights_bigb[[3]]$kpop_mf_w[kbal_data_sampled==1])
                
                kpop_b512 <- svydesign(~1, data = pew_xgb, 
                                  weights = weights_bigb[[4]]$kpop_w[kbal_data_sampled==1])
                kpop_b512_conv <- svydesign(~1, data = pew_xgb, 
                                       weights =
                                    weights_bigb[[4]]$kpop_w_conv[kbal_data_sampled==1])
                kpop_mf_b512 <- svydesign(~1, data = pew_xgb, 
                                     weights =
                                         weights_bigb[[4]]$kpop_mf_w[kbal_data_sampled==1])
                
                kpop_b1024 <- svydesign(~1, data = pew_xgb, 
                                  weights = weights_bigb[[5]]$kpop_w[kbal_data_sampled==1])
                kpop_b1024_conv <- svydesign(~1, data = pew_xgb, 
                            weights = weights_bigb[[5]]$kpop_w_conv[kbal_data_sampled==1])
                kpop_mf_b1024 <- svydesign(~1, data = pew_xgb, 
                                     weights =
                                         weights_bigb[[5]]$kpop_mf_w[kbal_data_sampled==1])
                
                kpop_b2048 <- svydesign(~1, data = pew_xgb, 
                                  weights = weights_bigb[[6]]$kpop_w[kbal_data_sampled==1])
                kpop_b2048_conv <- svydesign(~1, data = pew_xgb, 
                                       weights = 
                                weights_bigb[[6]]$kpop_w_conv[kbal_data_sampled==1])
                kpop_mf_b2048 <- svydesign(~1, data = pew_xgb, 
                                     weights =
                                         weights_bigb[[6]]$kpop_mf_w[kbal_data_sampled==1])
                
                
                kpop_b4096 <- svydesign(~1, data = pew_xgb, 
                                  weights = weights_bigb[[7]]$kpop_w[kbal_data_sampled==1])
                kpop_b4096_conv <- svydesign(~1, data = pew_xgb, 
                                       weights = 
                                    weights_bigb[[7]]$kpop_w_conv[kbal_data_sampled==1])
                kpop_mf_b4096 <- svydesign(~1, data = pew_xgb, 
                                     weights = 
                                         weights_bigb[[7]]$kpop_mf_w[kbal_data_sampled==1])
                
                
                kpop_b8192 <- svydesign(~1, data = pew_xgb, 
                                  weights = weights_bigb[[8]]$kpop_w[kbal_data_sampled==1])
                kpop_b8192_conv <- svydesign(~1, data = pew_xgb, 
                                       weights = 
                                    weights_bigb[[8]]$kpop_w_conv[kbal_data_sampled==1])
                kpop_mf_b8192 <- svydesign(~1, data = pew_xgb, 
                                     weights = 
                                         weights_bigb[[8]]$kpop_mf_w[kbal_data_sampled==1])
                
                
                kpop_b16384 <- svydesign(~1, data = pew_xgb, 
                                  weights = weights_bigb[[9]]$kpop_w[kbal_data_sampled==1])
                kpop_b16384_conv <- svydesign(~1, data = pew_xgb, 
                                       weights =
                                    weights_bigb[[9]]$kpop_w_conv[kbal_data_sampled==1])
                kpop_mf_b16384 <- svydesign(~1, data = pew_xgb, 
                                     weights =
                                         weights_bigb[[9]]$kpop_mf_w[kbal_data_sampled==1])
                kpop_b24576 <- svydesign(~1, data = pew_xgb, 
                                  weights =
                                      weights_bigb[[10]]$kpop_w[kbal_data_sampled==1])
                kpop_b24576_conv <- svydesign(~1, data = pew_xgb, 
                                       weights = 
                                    weights_bigb[[10]]$kpop_w_conv[kbal_data_sampled==1])
                kpop_mf_b24576 <- svydesign(~1, data = pew_xgb, 
                                     weights =
                                        weights_bigb[[10]]$kpop_mf_w[kbal_data_sampled==1])
        }
            
     }
    
    if(!cat_kernel & smallB) {
            i = 1
            #survey designs
        kpop_b32 <- svydesign(~1, data = pew_xgb, 
                              weights = weights[[i]]$kpop_w[kbal_data_sampled==1])
        kpop_b16 <- svydesign(~1, data = pew_xgb, 
                              weights = weights[[i+1]]$kpop_w[kbal_data_sampled==1])
        kpop_b8 <- svydesign(~1, data = pew_xgb, 
                             weights = weights[[i+2]]$kpop_w[kbal_data_sampled==1])
        kpop_b4 <- svydesign(~1, data = pew_xgb, 
                             weights = weights[[i+3]]$kpop_w[kbal_data_sampled==1])
        kpop_b2 <- svydesign(~1, data = pew_xgb, 
                             weights = weights[[i+4]]$kpop_w[kbal_data_sampled==1])
        kpop_b1 <- svydesign(~1, data = pew_xgb, 
                             weights = weights[[i+5]]$kpop_w[kbal_data_sampled==1])
        
        kpop_b32_conv <- svydesign(~1, data = pew_xgb, 
                                   weights = 
                                       weights[[i]]$kpop_w_conv[kbal_data_sampled==1])
        kpop_b16_conv <- svydesign(~1, data = pew_xgb, 
                                   weights =
                                      weights[[i+1]]$kpop_w_conv[kbal_data_sampled==1])
        kpop_b8_conv <- svydesign(~1, data = pew_xgb, 
                                  weights =
                                      weights[[i+2]]$kpop_w_conv[kbal_data_sampled==1])
        kpop_b4_conv <- svydesign(~1, data = pew_xgb, 
                                  weights =
                                      weights[[i+3]]$kpop_w_conv[kbal_data_sampled==1])
        kpop_b2_conv <- svydesign(~1, data = pew_xgb, 
                                  weights =
                                      weights[[i+4]]$kpop_w_conv[kbal_data_sampled==1])
        kpop_b1_conv <- svydesign(~1, data = pew_xgb, 
                                  weights =
                                      weights[[i+5]]$kpop_w_con[kbal_data_sampled==1])
        
        kpop_mf_b32 <- svydesign(~1, data = pew_xgb, 
                                 weights =
                                     weights[[i]]$kpop_mf_w[kbal_data_sampled==1])
        kpop_mf_b16 <- svydesign(~1, data = pew_xgb, 
                                 weights =
                                     weights[[i+1]]$kpop_mf_w[kbal_data_sampled==1])
        kpop_mf_b8 <- svydesign(~1, data = pew_xgb, 
                                weights =
                                    weights[[i+2]]$kpop_mf_w[kbal_data_sampled==1])
        kpop_mf_b4 <- svydesign(~1, data = pew_xgb, 
                                weights =
                                    weights[[i+3]]$kpop_mf_w[kbal_data_sampled==1])
        kpop_mf_b2 <- svydesign(~1, data = pew_xgb, 
                                weights =
                                    weights[[i+4]]$kpop_mf_w[kbal_data_sampled==1])
        kpop_mf_b1 <- svydesign(~1, data = pew_xgb, 
                                weights =
                                    weights[[i+5]]$kpop_mf_w[kbal_data_sampled==1])
     }
        

    #run other methods
    rake_demos_noeduc <- calibrate(design = pew_srs_xgb,
                                   formula = formula_rake_demos_noeduc,
                                   population = targets_rake_demos_noeduc,
                                   calfun = "raking")
    
    rake_demos_noeduc <- svydesign(~1, data = pew_xgb,
                                   weights = weights(rake_demos_noeduc))
    
    ## Raking on demographics, including education
    rake_demos_weduc <- calibrate(design = pew_srs_xgb,
                                  formula = formula_rake_demos_weduc,
                                  population = targets_rake_demos_weduc,
                                  calfun = "raking")
    
    rake_demos_weduc <- svydesign(~1, data = pew_xgb, weights =
                                      weights(rake_demos_weduc))
    #rake all
    rake_all_vars <- calibrate(design = pew_srs_xgb,
                                  formula = formula_rake_all_vars,
                                  population = targets_rake_all_vars,
                                  calfun = "raking")
    
    rake_all_vars <- svydesign(~1, data = pew_xgb, weights =
                                      weights(rake_all_vars))
    
    ## Post-stratification
    pew_ps_xgb <- svydesign(ids = ~1, data = pew_xgb %>% filter(!(strata %in% problem)))
    post_stratification <- postStratify(design = pew_ps_xgb,
                                        strata = ~strata,
                                        population = targets_ps)
    post_stratification <- svydesign(~1, 
                                     data = pew_xgb %>% filter(!(strata %in% problem)),
                                     weights = weights(post_stratification))
    #reduced
    pew_ps_reduc_xgb <- svydesign(ids = ~1, data = pew_xgb %>% 
                                      filter(!(strata_reduc %in% problem_reduc)))
    post_strat_reduc <- postStratify(design = pew_ps_reduc_xgb,
                                        strata = ~strata_reduc,
                                        population = targets_ps_reduc)
    post_strat_reduc <- svydesign(~1, 
                                  data = pew_xgb %>%filter(!(strata_reduc %in%
                                                                 problem_reduc)),
                                     weights = weights(post_strat_reduc))
    
    pew_ps_all_xgb <- svydesign(ids = ~1, 
                                data = pew %>% filter(!(strata_all %in% problem_all)))
    post_strat_all <- postStratify(design = pew_ps_all_xgb,
                                        strata = ~strata_all,
                                        population = targets_ps_all)
    post_strat_all <- svydesign(~1,
                                data = pew_xgb %>% filter(!(strata_all %in% problem_all)),
                                weights = weights(post_strat_all))
    
    
    rake_retrospective <- calibrate(design = pew_srs_xgb,
                                    formula = formula_retrospective,
                                    population = targets_retrospective,
                                    calfun = "raking",
                                    force = TRUE)
    rake_retrospective <- svydesign(~1, data = pew_xgb,
                                    weights = weights(rake_retrospective))
        
    
    
    
    ########### Get Estimates #########
    #vote contrasts for svymean
       
    if(popw) {
        cces_svy = cces_awt_xgb
    } else {
        cces_svy = cces_nowt_xgb
    }
    
    
    ##### START GIANT PLOTS PREP
    # a little ridiculous but here we are
    df_build <- function(var_orig, var_cces, var_pew, drop_ccesNAs, vote_form = vote_diff,
                         real = FALSE, bigB, smallB, cat_kernel) {
        if(!real) {
          df <- data.frame(
            #this is: ncategory/(nrow - 360 NAs) then weighted and then take difference of those percents/means
            cces_orig = svycontrast(svymean(as.formula(paste0("~", var_orig)), 
                                            cces_svy, na.rm = TRUE),
                                    vote_form),
            #this is cces modeled outcome on cces
            cces_xgb = svymean(as.formula(paste0("~", var_cces)), cces_svy, na.rm = TRUE),
            
            #outcome = modeled cces predicted with pew (cces on pew)
            unweighted = svymean(as.formula(paste0("~", var_pew)), pew_srs_xgb, na.rm = TRUE),
            
            pew_weighted = svymean(as.formula(paste0("~", var_pew)), pew_w_srs, na.rm = TRUE),
            rake_demos_noeduc = svymean(as.formula(paste0("~", var_pew)), 
                                        rake_demos_noeduc, na.rm = TRUE),
            rake_demos_weduc = svymean(as.formula(paste0("~", var_pew)), 
                                       rake_demos_weduc, na.rm = TRUE),
            rake_all_vars = svymean(as.formula(paste0("~", var_pew)), 
                                       rake_all_vars, na.rm = TRUE),
            post_stratification = svymean(as.formula(paste0("~", var_pew)), 
                                          post_stratification,
                                          na.rm = TRUE),
            post_strat_reduc = svymean(as.formula(paste0("~", var_pew)), 
                                          post_strat_reduc,
                                          na.rm = TRUE),
            post_strat_all = svymean(as.formula(paste0("~", var_pew)), 
                                          post_strat_all,
                                          na.rm = TRUE),
            rake_retrospective = svymean(as.formula(paste0("~", var_pew)),
                                         rake_retrospective, 
                                         na.rm = TRUE),
            kpop_bmean = if(cat_kernel) {
                svymean(as.formula(paste0("~", var_pew)), kpop_bmean, na.rm = TRUE)
                       } else {
                    NA},
            kpop_bmean_conv =
                if(cat_kernel) {
                 svymean(as.formula(paste0("~", var_pew)), kpop_bmean_conv, na.rm = TRUE)
                         } else {
                    NA},
            kpop_mf_bmean =
                if(cat_kernel) {
                svymean(as.formula(paste0("~", var_pew)), kpop_mf_bmean, na.rm = TRUE)
                       } else {
                    NA},
            
            kpop_bmaxvar = if(cat_kernel) {
                svymean(as.formula(paste0("~", var_pew)), kpop_bmaxvar, na.rm = TRUE)
                       } else {
                    NA},
            kpop_bmaxvar_conv =
                if(cat_kernel) {
                 svymean(as.formula(paste0("~", var_pew)), kpop_bmaxvar_conv, na.rm = TRUE)
                         } else {
                    NA},
            kpop_mf_bmaxvar =
                if(cat_kernel) {
                svymean(as.formula(paste0("~", var_pew)), kpop_mf_bmaxvar, na.rm = TRUE)
                       } else {
                    NA},
            
            kpop_b24576 = if(drop_ccesNAs & bigB &!cat_kernel) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b24576,
                        na.rm = TRUE) } else {
                    NA},
            kpop_b16384 = if(drop_ccesNAs & bigB &!cat_kernel) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b16384,
                        na.rm = TRUE) } else {
                    NA},
            kpop_b8192= if(drop_ccesNAs & bigB &!cat_kernel) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b8192,
                        na.rm = TRUE) } else {
                    NA},
            kpop_b4096 = if(drop_ccesNAs & bigB &!cat_kernel) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b4096, 
                        na.rm = TRUE) } else {
                    NA},
            kpop_b2048 = if(drop_ccesNAs & bigB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b2048,
                        na.rm = TRUE) } else {
                    NA},
            kpop_b1024 = if(drop_ccesNAs & bigB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b1024,
                        na.rm = TRUE) } else {
                    NA},
            kpop_b512 = if(drop_ccesNAs & bigB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b512,
                        na.rm = TRUE) } else {
                    NA},
            kpop_b256 = if(drop_ccesNAs & bigB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b256, 
                        na.rm = TRUE) } else {
                    NA},
            kpop_b128 = if(drop_ccesNAs & bigB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b128, 
                        na.rm = TRUE) } else {
                    NA},
            kpop_b64 = if(smallB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b64, 
                        na.rm = TRUE) } else {
                    NA},
            kpop_b32 = if(smallB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b32, 
                        na.rm = TRUE)  } else {
                    NA},
            kpop_b16 = if(smallB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b16, 
                        na.rm = TRUE)  } else {
                    NA},
            kpop_b8 = 
                if(smallB) { 
                 svymean(as.formula(paste0("~", var_pew)), kpop_b8, 
                         na.rm = TRUE) } else {
                    NA},
            kpop_b4 = 
                if(smallB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b4, 
                        na.rm = TRUE) } else {
                    NA},
            kpop_b2 = if(smallB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b2,
                        na.rm = TRUE)} else { NA},
            kpop_b1 = if(smallB &!cat_kernel) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b1,
                        na.rm = TRUE)  } else {NA},
            
            kpop_b24576_conv = if(drop_ccesNAs & bigB&!cat_kernel) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b24576_conv,
                        na.rm = TRUE) } else {
                    NA},
            kpop_b16384_conv = if(drop_ccesNAs & bigB&!cat_kernel) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b16384_conv,
                        na.rm = TRUE) } else {
                    NA},
            kpop_b8192_conv = if(drop_ccesNAs & bigB&!cat_kernel) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b8192_conv,
                        na.rm = TRUE) } else {
                    NA},
            kpop_b4096_conv = if(drop_ccesNAs & bigB&!cat_kernel) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b4096_conv, 
                        na.rm = TRUE) } else {
                    NA},
            kpop_b2048_conv = if(drop_ccesNAs & bigB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b2048_conv,
                        na.rm = TRUE) } else {
                    NA},
            kpop_b1024_conv = if(drop_ccesNAs & bigB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b1024_conv,
                        na.rm = TRUE) } else {
                    NA},
            kpop_b512_conv = if(drop_ccesNAs & bigB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b512_conv,
                        na.rm = TRUE) } else {
                    NA},
            kpop_b256_conv = if(drop_ccesNAs & bigB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b256_conv, 
                        na.rm = TRUE) } else {
                    NA},
            kpop_b128_conv = if(drop_ccesNAs & bigB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b128_conv, 
                        na.rm = TRUE) } else {
                    NA},
            kpop_b64_conv = if(smallB) { 
                svymean(as.formula(paste0("~", var_pew)), 
                        kpop_b64_conv, na.rm = TRUE) } else {  NA},
            kpop_b32_conv = if(smallB) { 
               svymean(as.formula(paste0("~", var_pew)), kpop_b32_conv,
                                    na.rm = TRUE) } else {
                    NA},
            kpop_b16_conv = if(smallB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b16_conv, 
                                    na.rm = TRUE) } else {
                    NA},
            kpop_b8_conv = if(smallB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b8_conv,
                                   na.rm = TRUE) } else {
                    NA},
            kpop_b4_conv = if(smallB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b4_conv, 
                                   na.rm = TRUE) } else {
                    NA},
            kpop_b2_conv = if(smallB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_b2_conv, 
                                   na.rm = TRUE) } else {
                    NA},
            kpop_b1_conv = if(smallB&!cat_kernel) { 
               svymean(as.formula(paste0("~", var_pew)), kpop_b1_conv, 
                                   na.rm = TRUE) } else {
                    NA},
            
            
            kpop_mf_b24576 = if(drop_ccesNAs & bigB&!cat_kernel) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_mf_b24576,
                        na.rm = TRUE) } else {
                    NA},
            kpop_mf_b16384 = if(drop_ccesNAs & bigB&!cat_kernel) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_mf_b16384,
                        na.rm = TRUE) } else {
                    NA},
            kpop_mf_b8192 = if(drop_ccesNAs & bigB&!cat_kernel) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_mf_b8192,
                        na.rm = TRUE) } else {
                    NA},
            kpop_mf_b4096 = if(drop_ccesNAs & bigB&!cat_kernel) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_mf_b4096, 
                        na.rm = TRUE) } else {
                    NA},
            kpop_mf_b2048 = if(drop_ccesNAs & bigB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_mf_b2048,
                        na.rm = TRUE) } else {
                    NA},
            kpop_mf_b1024 = if(drop_ccesNAs & bigB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_mf_b1024,
                        na.rm = TRUE) } else {
                    NA},
            kpop_mf_b512 = if(drop_ccesNAs & bigB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_mf_b512,
                        na.rm = TRUE) } else {
                    NA},
            kpop_mf_b256 = if(drop_ccesNAs & bigB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_mf_b256, 
                        na.rm = TRUE) } else {
                    NA},
            kpop_mf_b128 = if(drop_ccesNAs & bigB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_mf_b128, 
                        na.rm = TRUE) } else {
                            NA},
            
            kpop_mf_b64 = if(smallB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_mf_b64,
                        na.rm = TRUE) }  else { NA},
            kpop_mf_b32 = if(smallB) { 
               svymean(as.formula(paste0("~", var_pew)), kpop_mf_b32,
                                  na.rm = TRUE) } else { NA},
            kpop_mf_b16 = if(smallB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_mf_b16, 
                                  na.rm = TRUE) } else { NA},
            kpop_mf_b8 = if(smallB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_mf_b8, 
                                 na.rm = TRUE) }  else { NA},
            kpop_mf_b4 = if(smallB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_mf_b4, 
                                 na.rm = TRUE) }  else { NA},
            kpop_mf_b2 = if(smallB) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_mf_b2,
                                 na.rm = TRUE) }  else { NA},
            kpop_mf_b1 = if(smallB&!cat_kernel) { 
                svymean(as.formula(paste0("~", var_pew)), kpop_mf_b1, 
                                 na.rm = TRUE) } else { NA}) %>%
    pivot_longer(cols = everything(),
                         names_to = c("source", ".value"), 
                         names_pattern = "(.*)\\.(.*)") 
          
            df$SE <- coalesce(df[[var_cces]], df[[var_pew]], df$SE)
            df <- df %>% mutate(est = coalesce(nlcon, mean))
        } else {
            df <- data.frame(
                cces_orig = svycontrast(svymean(~recode_vote_2016, 
                                                cces_svy, na.rm = TRUE),
                                        vote_form),
                #outcome = modeled cces predicted with pew (cces on pew)
                unweighted = svycontrast(svymean(~recode_vote_2016, 
                                                 pew_srs_xgb, na.rm = TRUE),
                                         vote_form),
                pew_weighted = svycontrast(svymean(~recode_vote_2016, 
                                                   pew_w_srs, na.rm = TRUE),
                                           vote_form),
                
                rake_demos_noeduc = svycontrast(svymean(~recode_vote_2016, 
                                                        rake_demos_noeduc, na.rm = TRUE),
                                                vote_form),
                rake_demos_weduc = svycontrast(svymean(~recode_vote_2016, 
                                                       rake_demos_weduc, na.rm = TRUE),
                                               vote_form),
                rake_all_vars = svycontrast(svymean(~recode_vote_2016, 
                                                       rake_all_vars, na.rm = TRUE),
                                               vote_form),
                post_stratification = svycontrast(svymean(~recode_vote_2016, 
                                                          post_stratification,
                                                          na.rm = TRUE),
                                                  vote_form),
                post_strat_reduc = svycontrast(svymean(~recode_vote_2016, 
                                                          post_strat_reduc,
                                                          na.rm = TRUE),
                                                  vote_form),
                post_strat_all = svycontrast(svymean(~recode_vote_2016, 
                                                          post_strat_all,
                                                          na.rm = TRUE),
                                                  vote_form),
                rake_retrospective = svycontrast(svymean(~recode_vote_2016, 
                                                         rake_retrospective,
                                                         na.rm = TRUE),
                                                 vote_form),
                # kpop_cat = if(cat_kernel) { 
                #                     svycontrast(svymean(~recode_vote_2016,
                #                                   kpop_cat, na.rm = TRUE),
                #                           vote_form) } else {
                #     NA},
                # kpop_cat_conv = 
                #     if(cat_kernel) { 
                #             svycontrast(svymean(~recode_vote_2016,
                #                                   kpop_cat_conv, na.rm = TRUE),
                #                           vote_form)} else {
                #         NA},
                #  kpop_cat_mf = 
                #     if(cat_kernel) { 
                #             svycontrast(svymean(~recode_vote_2016,
                #                                   kpop_cat_mf, na.rm = TRUE),
                #                           vote_form) } else {
                #         NA},
                 kpop_bmean = if(cat_kernel) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_bmean, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
                kpop_bmean_conv =
                    if(cat_kernel) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_bmean_conv, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
                kpop_mf_bmean =
                    if(cat_kernel) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_mf_bmean, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
                
                kpop_bmaxvar = if(cat_kernel) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_bmaxvar, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
                kpop_bmaxvar_conv =
                    if(cat_kernel) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_bmaxvar_conv, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
            kpop_mf_bmaxvar =
                if(cat_kernel) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_mf_bmaxvar, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
                kpop_b24576 = if(drop_ccesNAs & bigB&!cat_kernel) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b24576, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
                kpop_b16384 = if(drop_ccesNAs & bigB&!cat_kernel) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b16384, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
                kpop_b8192 = if(drop_ccesNAs & bigB&!cat_kernel) { 
                   svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b8192, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
                kpop_b4096 = if(drop_ccesNAs & bigB&!cat_kernel) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b4096, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_b2048 = if(drop_ccesNAs & bigB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b2048, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
                kpop_b1024 = if(drop_ccesNAs & bigB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b1024, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
                kpop_b512 = if(drop_ccesNAs & bigB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b512, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_b256 = if(drop_ccesNAs & bigB) { 
                   svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b256, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_b128 = if(drop_ccesNAs & bigB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b128, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_b64 = if(smallB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b64, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_b32 = if(smallB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                               kpop_b32, na.rm = TRUE),
                                       vote_form) } else {
                        NA},
                kpop_b16 = if(smallB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                               kpop_b16, na.rm = TRUE),
                                       vote_form) } else {
                        NA},
                kpop_b8 = if(smallB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                              kpop_b8, na.rm = TRUE),
                                      vote_form) } else {
                        NA},
                kpop_b4 = if(smallB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                              kpop_b4, na.rm = TRUE),
                                      vote_form) } else {
                        NA},
                kpop_b2 = if(smallB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                              kpop_b2, na.rm = TRUE),
                                      vote_form)} else {
                        NA},
                kpop_b1 = if(smallB&!cat_kernel) { 
                    svycontrast(svymean(~recode_vote_2016,
                                              kpop_b1, na.rm = TRUE),
                                      vote_form) } else {
                        NA},
                
                
                 kpop_b24576_conv = if(drop_ccesNAs & bigB&!cat_kernel) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b24576_conv, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
                kpop_b16384_conv = if(drop_ccesNAs & bigB&!cat_kernel) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b16384_conv, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
                kpop_b8192_conv = if(drop_ccesNAs & bigB&!cat_kernel) { 
                   svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b8192_conv, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
                kpop_b4096_conv = if(drop_ccesNAs & bigB&!cat_kernel) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b4096_conv, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_b2048_conv = if(drop_ccesNAs & bigB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b2048_conv, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
                kpop_b1024_conv = if(drop_ccesNAs & bigB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b1024_conv, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
                kpop_b512_conv = if(drop_ccesNAs & bigB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b512_conv, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_b256_conv = if(drop_ccesNAs & bigB) { 
                   svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b256_conv, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_b128_conv = if(drop_ccesNAs & bigB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b128_conv, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_b64_conv = if(smallB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b64_conv, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_b32_conv = if(smallB) { 
                          svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b32_conv, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_b16_conv = if(smallB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b16_conv, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_b8_conv = if(smallB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b8_conv, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_b4_conv = if(smallB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b4_conv, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_b2_conv = if(smallB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b2_conv, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_b1_conv =if(smallB&!cat_kernel) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_b1_conv, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                
                kpop_mf_b24576 = if(drop_ccesNAs & bigB&!cat_kernel) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_mf_b24576, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
                kpop_mf_b16384 = if(drop_ccesNAs & bigB&!cat_kernel) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_mf_b16384, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
                kpop_mf_b8192 = if(drop_ccesNAs & bigB&!cat_kernel) { 
                   svycontrast(svymean(~recode_vote_2016,
                                                  kpop_mf_b8192, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
                kpop_mf_b4096 = if(drop_ccesNAs & bigB&!cat_kernel) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_mf_b4096, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_mf_b2048 = if(drop_ccesNAs & bigB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_mf_b2048, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
                kpop_mf_b1024 = if(drop_ccesNAs & bigB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_mf_b1024, na.rm = TRUE),
                                          vote_form)  } else {
                        NA},
                kpop_mf_b512 = if(drop_ccesNAs & bigB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_mf_b512, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_mf_b256 = if(drop_ccesNAs & bigB) { 
                   svycontrast(svymean(~recode_vote_2016,
                                                  kpop_mf_b256, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_mf_b128 = if(drop_ccesNAs & bigB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_mf_b128, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                
                kpop_mf_b64 = if(smallB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_mf_b64, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_mf_b32 =  if(smallB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_mf_b32, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_mf_b16 = if(smallB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_mf_b16, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_mf_b8 =  if(smallB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_mf_b8, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_mf_b4 =  if(smallB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_mf_b4, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_mf_b2 =  if(smallB) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_mf_b2, na.rm = TRUE),
                                          vote_form) } else {
                        NA},
                kpop_mf_b1 = if(smallB&!cat_kernel) { 
                    svycontrast(svymean(~recode_vote_2016,
                                                  kpop_mf_b1, na.rm = TRUE),
                                          vote_form) } else {
                        NA}
            ) %>%
                pivot_longer(cols = everything(),
                             names_to = c("source", ".value"), 
                             names_pattern = "(.*)\\.(.*)") 
            
            df <- df %>% rename(est = nlcon)
            
        }
        df <- df %>% filter(!is.na(source))
        #if(!bigB) {df <- df %>% filter(!is.na(source))}
        #some manual fixing of names 
        df <- df %>% 
            dplyr::select(source, est, SE) %>%
            mutate(est = est * 100,
                   SE = SE * 100,
                   #err_target = est - target_diff * 100,
                   source = str_replace(source, "_", " "))
        
        if(!cat_kernel) {
            rep <- NULL
              if(bigB) {
                  rep <- c(24576,16384,8192,4096,2048,1024,512,256,128)
              }
              if(smallB) {
                    rep = c(rep, c(64,32,16,8,4,2, 1)) 
                }
            b_num <- c(b_num, rep(rep, 3))
        } else if(cat_kernel) {
             b_num = c(rep(out_cat$b[1], 3), rep(out_cat$b[2], 3) ) 
             rep <- NULL
              if(bigB) {
                rep <- c(2048,1024,512,256,128)
                }
                if(smallB) {
                    rep = c(rep, c(64,32,16,8,4,2)) 
                }
            b_num <- c(b_num, rep(rep, 3))
        }
        
        df <- df %>% 
            mutate(source_name = factor(source, 
                                        levels = as.character(df$source) ,
                                        labels = c("CCES Orig",
                                                   if(!real){"CCES XGB"},
                                                   "Pew Unweighted", 
                                                   "Pew Weights",
                                                   "Raking Demos NO Education", 
                                                   "Raking Demos W Education", 
                                                   "Raking All Vars",
                                                   "Post-Strat (former)", 
                                                   "Post-Strat (reduced)",
                                                   "Post-Strat (all)",
                                                   "Raking Retrospective", 
                                                   if(cat_kernel) {"Kpop b=mean"},
                                                    if(cat_kernel) {"Kpop Conv b=mean"},
                                                    if(cat_kernel) {"Kpop MF b=mean"},
                                                   if(cat_kernel) {"Kpop b=max(var(K))*2"},
                                            if(cat_kernel) {"Kpop Conv b=max(var(K))*2"},
                                            if(cat_kernel) {"Kpop MF b=max(var(K))*2"},
                                                   if(bigB&!cat_kernel) {"Kpop b=24576x"},
                                                    if(bigB&!cat_kernel) {"Kpop b=16384x"},
                                                    if(bigB&!cat_kernel) {"Kpop b=8192x"},
                                                    if(bigB&!cat_kernel) {"Kpop b=4096x"},
                                                    if(bigB) {"Kpop b=2048x"},
                                                    if(bigB) {"Kpop b=1024x"},
                                                    if(bigB) {"Kpop b=512x"}, 
                                                    if(bigB) {"Kpop b=256x"},
                                                    if(bigB) {"Kpop b=128x"},
                                                   if(smallB) {"Kpop b=64x"},
                                                    if(smallB) {"Kpop b=32x"},
                                                    if(smallB) {"Kpop b=16x"},
                                                    if(smallB) {"Kpop b=8x"},
                                                    if(smallB) {"Kpop b=4x"},
                                                    if(smallB) {"Kpop b=2x"},
                                            if(smallB&!cat_kernel) {"Kpop b=1x"},
                                            if(bigB&!cat_kernel) {"Kpop Conv b=24576x"},
                                            if(bigB&!cat_kernel) {"Kpop Conv b=16384x"},
                                            if(bigB&!cat_kernel) {"Kpop Conv b=8192x"},
                                            if(bigB&!cat_kernel) {"Kpop Conv b=4096x"},
                                                    if(bigB) {"Kpop Conv b=2048x"},
                                                    if(bigB) {"Kpop Conv b=1024x"},
                                                    if(bigB) {"Kpop Conv b=512x"}, 
                                                    if(bigB) {"Kpop Conv b=256x"},
                                                    if(bigB) {"Kpop Conv b=128x"},
                                                   if(smallB) {"Kpop Conv b=64x"},
                                                    if(smallB) {"Kpop Conv b=32x"},
                                                    if(smallB) {"Kpop Conv b=16x"},
                                                    if(smallB) {"Kpop Conv b=8x"},
                                                    if(smallB) {"Kpop Conv b=4x"},
                                                    if(smallB) {"Kpop Conv b=2x"},
                                            if(smallB&!cat_kernel) {"Kpop Conv b=1x"},
                                            if(bigB&!cat_kernel) { "Kpop MF b=24576x"},
                                        if(bigB&!cat_kernel) { "Kpop MF b=16384x"},
                                        if(bigB&!cat_kernel) {"Kpop MF b=8192x"},
                                            if(bigB&!cat_kernel) {"Kpop MF b=4096x"},
                                                    if(bigB) {"Kpop MF b=2048x"},
                                                    if(bigB) {"Kpop MF b=1024x"},
                                                    if(bigB) {"Kpop MF b=512x"}, 
                                                    if(bigB) {"Kpop MF b=256x"},
                                                if(bigB) {"Kpop MF b=128x"},
                                                  if(smallB) {"Kpop MF b=64x"},
                                                    if(smallB) {"Kpop MF b=32x"},
                                                    if(smallB) {"Kpop MF b=16x"},
                                                    if(smallB) {"Kpop MF b=8x"},
                                                    if(smallB) {"Kpop MF b=4x"},
                                                    if(smallB) {"Kpop MF b=2x"},
                                            if(smallB&!cat_kernel) {"Kpop MF b=1x"})
                                            ))
        
        df$MF <- "NA"
        df$MF[grep("MF", levels(df$source_name))] <- "MF"
        df$MF[!grepl("MF", levels(df$source_name)) & 
                            grepl("Kpop", levels(df$source_name))]<- "No MF"
        df$Conv <- "NA"
        df$Conv[!grepl("Conv", levels(df$source_name)) & 
                              grepl("Kpop", levels(df$source_name))]<- "Conv Not Required"
        df$Conv[c(grep("Conv", levels(df$source_name)),
                            grep("MF", levels(df$source_name)))] <- "Conv Required"
        
        df$b <- NA
        df$b[grep("b=", levels(df$source_name)) ]<- b_num
        
        df <- df %>% filter(!is.na(est))
        return(df)
    }
    
    comp_df_diff <- df_build("recode_vote_2016", "diff_cces_on_cces", "diff_cces_on_pew",
                             drop_ccesNAs = drop_ccesNAs, 
                             bigB = bigB, smallB = smallB,
                             cat_kernel = cat_kernel)
    
    comp_df_diff_pewoutcome <- df_build("recode_vote_2016", 
                                        "diff_pew_on_cces",
                                        "diff_pew_on_pew",
                                        drop_ccesNAs = drop_ccesNAs,
                                        bigB = bigB, smallB = smallB,
                                        cat_kernel = cat_kernel)
    

###### XXX do I want to have diff with cces_on_pew as well for cces_xgb or as below just use cces_on_ccess for cces_xgb for both
    comp_df_margin <- df_build("recode_vote_2016", 
                                        "margin_cces_on_cces",
                                        "margin_cces_on_pew",
                                        drop_ccesNAs = drop_ccesNAs, 
                               bigB = bigB,  smallB = smallB,
                               cat_kernel = cat_kernel)
    
    comp_df_margin_pewoutcome <- df_build("recode_vote_2016", 
                                          "margin_pew_on_cces",
                                          "margin_pew_on_pew",
                                          drop_ccesNAs = drop_ccesNAs, 
                                          bigB = bigB,
                                           smallB = smallB,
                                          cat_kernel = cat_kernel)
    comp_df_pR <- df_build("recode_vote_2016", 
                           "xgb_cces_on_cces_pR",
                           "xgb_cces_on_pew_pR",
                            drop_ccesNAs = drop_ccesNAs, 
                           bigB = bigB,
                            smallB = smallB,
                           cat_kernel = cat_kernel)
    
    comp_df_pR_pewoutcome <- df_build("recode_vote_2016", 
                           "xgb_pew_on_cces_pR",
                           "xgb_pew_on_pew_pR",
                            drop_ccesNAs = drop_ccesNAs, 
                           bigB = bigB,
                            smallB = smallB,
                           cat_kernel = cat_kernel)
    
    comp_df_pD <- df_build("recode_vote_2016", 
                           "xgb_cces_on_cces_pD",
                           "xgb_cces_on_pew_pD",
                            drop_ccesNAs = drop_ccesNAs, 
                           bigB = bigB, smallB = smallB,
                           cat_kernel = cat_kernel)
        
    comp_df_pD_pewoutcome <- df_build("recode_vote_2016", 
                           "xgb_pew_on_cces_pD",
                           "xgb_pew_on_pew_pD",
                            drop_ccesNAs = drop_ccesNAs, 
                           bigB = bigB, smallB = smallB,
                           cat_kernel = cat_kernel)
    
    
    comp_df_real <- df_build("recode_vote_2016", 
                           "recode_vote_2016",
                           "recode_vote_2016",
                           drop_ccesNAs = drop_ccesNAs, 
                           real = TRUE, 
                           vote_form = vote_contrast,
                           bigB = bigB,
                            smallB = smallB,
                           cat_kernel = cat_kernel)
    
    comp_df_real_diff <-  df_build("recode_vote_2016", 
                           "recode_vote_2016",
                           "recode_vote_2016",
                            drop_ccesNAs = drop_ccesNAs, 
                           real = TRUE, bigB = bigB, 
                            smallB = smallB,
                           cat_kernel = cat_kernel)
    
    
    ######## PLOT ESTIMATES: Pre-wave Indiv Average Margin ########

    
    if(PRE) {
        pew_ver = "Pre-Wave"
    } else {
        pew_ver = "Post-Wave"
    }
     
    if(popw) {
        popw_lab = "w/Pop W."
    } else {
        popw_lab = "No Pop W."
    }
    
    if(age_buckets) {
        ageb = "w Age Buckets"
    } else {
        ageb = "No Age Buckets"
    }
    if(noDNK_weights) {
        dnk = "(no dnk voters)"
    } else {
        dnk = "(w dnk voters)"
    }
    if(three_way) {
        out_lab = "Three-way Vote"
    } else {
        out_lab = "Two-way Vote"
    }
    if(drop_ccesNAs) {
        NAs_lab = " No CCES NAs"
    } else {
        NAs_lab = " No CCES NAs"
    }
    
    pres <- readRDS(paste0(path_data, "election.rds"))
    
    natl_margin <- pres %>%
        summarise(margin = (sum(demtotal) - sum(reptotal)) /
                      (sum(demtotal) + sum(reptotal))) %>%
        as.numeric()
    
    #IS THIS RIGHT
    natl_diff <- pres %>%
        summarise(margin = (sum(demtotal) - sum(reptotal)) /
                      (sum(totalvotes))) %>%
        as.numeric()*100
    
    #XXXX IS THIS RIGHT?
    natl_Rep <- pres %>%
        summarise(pR =  sum(reptotal) /
                      sum(totalvotes)) %>%
        as.numeric()
    natl_Dem <- pres %>%
        summarise(pR =  sum(demtotal) /
                      sum(totalvotes)) %>%
        as.numeric()
    

    ###################
     #### merge together for aethetics on ggplot
    comp_df_margin_merge <- rbind(comp_df_margin, comp_df_margin_pewoutcome) %>% 
        mutate(model = c(rep("Modeled CCES",nrow(comp_df_margin)), 
                      rep(paste("Modeled", pew_ver, "Pew"),
                          nrow(comp_df_margin_pewoutcome)) ) )
    
    comp_df_diff_merge <- rbind(comp_df_diff, comp_df_diff_pewoutcome) %>% 
        mutate(model = c(rep("Modeled CCES",nrow(comp_df_margin)), 
                      rep(paste("Modeled", pew_ver, "Pew"),
                          nrow(comp_df_margin_pewoutcome)) ) )
    
    comp_df_pD_merge <- rbind(comp_df_pD, comp_df_pD_pewoutcome) %>% 
        mutate(model = c(rep("Modeled CCES",nrow(comp_df_margin)), 
                      rep(paste("Modeled", pew_ver, "Pew"),
                          nrow(comp_df_margin_pewoutcome)) ) )
    
    comp_df_pR_merge <- rbind(comp_df_pR, comp_df_pR_pewoutcome) %>% 
        mutate(model = c(rep("Modeled CCES",nrow(comp_df_margin)), 
                      rep(paste("Modeled", pew_ver, "Pew"),
                          nrow(comp_df_margin_pewoutcome)) ) )
    
    
    #droping wegithed pew estimates if dn ask for popw
    if(!popw) {
        comp_df_diff_merge <- comp_df_diff_merge[-which(comp_df_diff_merge$source == "pew weighted"), ]
        
        comp_df_margin_merge <- comp_df_margin_merge[-which(comp_df_margin_merge$source == "pew weighted"), ]
       
        comp_df_pR_merge <- comp_df_pR_merge[-which(comp_df_pR_merge$source == "pew weighted"), ]
        
        comp_df_pD_merge <- comp_df_pD_merge[-which(comp_df_pD_merge$source == "pew weighted"), ]
        
        comp_df_real <- comp_df_real[-which(comp_df_real$source == "pew weighted"), ]
        comp_df_real_diff <- comp_df_real_diff[-which(comp_df_real_diff$source == "pew weighted"), ]
    }
    
    ############plots
    b_default <- clean %>% filter(max(bbr) == bbr) %>% dplyr::select(b) %>% pull()
    b_conv <- clean %>% filter(max(bbr_conv) == bbr_conv) %>% 
        dplyr::select(b) %>% pull()
    b_mf <- clean %>% filter(max(bbr_mf) == bbr_mf) %>% 
        dplyr::select(b)%>% pull()
    best_b <- c(as.character((comp_df_diff %>% filter(b == b_default) %>%
                 dplyr::select(source_name))[1,] %>% pull()),
                as.character((comp_df_diff %>% filter(b == b_conv) %>%
                     dplyr::select(source_name))[2,] %>% pull()),
                as.character((comp_df_diff %>% filter(b == b_mf) %>%
                     dplyr::select(source_name))[3,] %>% pull()))
    best_b
    
    comp_df_plot_real_margin <-
        ggplot() +
        aes(x = source_name, y = est, ymin = est - 1.96*SE, ymax = est + 1.96*SE,
            color = as.factor(Conv), shape=as.factor(MF)) +
        
        geom_hline(yintercept = c(0, natl_margin*100,
                                  comp_df_margin$est[comp_df_margin$source_name == "CCES Orig"]),
                   linetype = c("solid", "dashed", "longdash"),
                   color = c("black", "gray60", "black")) +
        geom_pointrange(data = comp_df_real) +
        scale_y_continuous(breaks = c(natl_margin, seq(-5, 10, 5)),
                           minor_breaks = NULL,
                           labels = scales::percent_format(scale=1, accuracy = 0.1)) +
        theme_bw() +
        theme(plot.title = element_text(hjust = 0.5)) +
        
        labs(x = NULL, y = "Estimated Vote Margin (95% CI)") +
        ggtitle(paste(pew_ver, " Pew on TRUE CCES Vote Margin\n",NAs_lab, popw_lab, ageb, dnk)) +
        theme(axis.text.x = element_text(angle = 70, hjust = 1,
                                         face=if(PRE) {
                                             ifelse(comp_df_real$source_name %in% 
                                                        best_b,
                                                    "bold","plain")
                                         } else {
                                             ifelse(comp_df_real$source_name %in% 
                                                        best_b,
                                                    "bold","plain")
                                         })) +
        annotate(geom = "text", x = nrow(comp_df_real)+1.55, y = natl_margin * 100,
                 label = " True\n National\n Margin",
                 hjust = 0, angle = -90,
                 color = "gray60", size = 3) +
        annotate(geom = "text", x = nrow(comp_df_real)+1.35,
                 y = comp_df_margin$est[comp_df_margin$source_name == "CCES Orig"],
                 label = " CCES\n Target",
                 hjust = 0, angle = 90, size = 3) +
        #for spacing
         annotate(geom = "text", x = nrow(comp_df_real)+2.75,
                 y = comp_df_margin$est[comp_df_margin$source_name == "CCES Orig"],
                 label = " ",
                 hjust = 0, angle = 90, size = 3) +
        theme(legend.title = element_blank())
    
    
    comp_df_plot_real_diff <-
        ggplot() +
        aes(x = source_name, y = est, ymin = est - 1.96*SE, ymax = est + 1.96*SE,
            color = as.factor(Conv), shape=as.factor(MF))  + 
        
        geom_hline(yintercept = c(0, natl_diff,
                                  comp_df_real_diff$est[comp_df_real_diff$source_name
                                                        =="CCES Orig"]),
                   linetype = c("solid", "dashed", "longdash"),
                   color = c("black", "gray60", "black")) +
        geom_pointrange(data = comp_df_real_diff) +
        scale_y_continuous(breaks = c(natl_diff, seq(-5, 10, 5)),
                           minor_breaks = NULL,
                           labels = scales::percent_format(scale=1, accuracy = 0.1)) +
        theme_bw() +
        theme(plot.title = element_text(hjust = 0.5)) +
        
        labs(x = NULL, y = "Estimated Vote Difference (95% CI)") +
        ggtitle(paste(pew_ver, " Pew on TRUE CCES Vote Difference\n",  NAs_lab,
                      popw_lab, ageb, dnk)) +
        theme(axis.text.x = element_text(angle = 70, hjust = 1,
                                         face=if(PRE) {
                                             ifelse(comp_df_real_diff$source_name
                                                    %in% 
                                                       best_b,
                                                    "bold","plain")
                                         } else {
                                             ifelse(comp_df_real_diff$source_name
                                                    %in% 
                                                        best_b,
                                                    "bold","plain")
                                         })) +
        annotate(geom = "text", x = nrow(comp_df_real_diff) +1.35, y = natl_margin * 100,
                 label = " True\n National\n Margin",
                 hjust = 0, angle = -90,
                 color = "gray60", size = 3) +
        annotate(geom = "text", x = nrow(comp_df_real_diff) +1.35,
                 y = comp_df_real_diff$est[comp_df_real_diff$source_name == 
                                               "CCES\ Orig"],
                 label = " CCES\n Target",
                 hjust = 0, angle = 90, size = 3) +
        #for spacing
         annotate(geom = "text", x = nrow(comp_df_real_diff) +2.75,
                 y = comp_df_real_diff$est[comp_df_real_diff$source_name == 
                                               "CCES Orig"],
                 label = " ",
                 hjust = 0, angle = 90, size = 3) +
        theme(legend.title = element_blank())
    
    
    
    comp_df_plot_diff <-
        ggplot() +
        aes(x = source_name, y = est, ymin = est - 1.96*SE, ymax = est + 1.96*SE,
            color = as.factor(Conv), shape=as.factor(MF), 
            alpha = if(display_pew_mod) {as.factor(model)
                } else {
                first <-  rep("", nrow(comp_df_diff))
                    if(!cat_kernel) {
                        first[grep("Kpop", comp_df_diff$source_name)] <- "Alt B"
                        first[grep("32", comp_df_diff$source_name)] <- ""
                    } else {
                        first[grep("Kpop", comp_df_diff$source_name)] <- "Alt B"
                        first[grep(paste(best_b, collapse = "|"),
                                   comp_df_diff$source_name)] <- ""
                       
                    }
                    first
            } 
        ) +
        geom_hline(yintercept = c(0, 
                                  #natl_margin*100,
                                 # comp_df_diff$est[comp_df_diff$source_name == "CCES\n Orig"],
                                  comp_df_diff$est[comp_df_diff$source_name == "CCES XGB"]),
                   linetype = c("solid", #"dashed", #"longdash",
                                "dashed"),
                   color = c("black",# "gray60", #"black",
                             "purple")) +
        geom_pointrange(data = if(display_pew_mod) {comp_df_diff_merge} else {comp_df_diff}) +
        scale_y_continuous(breaks = c(natl_margin, seq(-5, 10, 5)),
                           minor_breaks = NULL,
                           labels = scales::percent_format(scale=1, accuracy = 0.1)) +
        theme_bw() +
        theme(plot.title = element_text(hjust = 0.5)) +
        
        labs(x = NULL, y = "Estimated Modeled Vote Difference (95% CI)") +
        ggtitle(paste(pew_ver, "Pew on CCES XGB Modeled Mean Indiv Vote Diff p(D) - p(R)",
                      out_lab,"modeled\n", NAs_lab, popw_lab, ageb, dnk)) +
        theme(axis.text.x = element_text(angle = 70, hjust = 1,
                                         face=if(PRE& smallB) {
                                             ifelse(comp_df_diff$source_name %in% 
                                                        best_b,
                                                    "bold","plain")
                                         } else if(PRE) {
                                                 rep("plain", nrow(comp_df_diff))
                                         } else {
                                             ifelse(comp_df_diff$source_name %in% 
                                                       best_b,
                                                    "bold","plain")
                                         })) +
        # annotate(geom = "text", x = nrow(comp_df_diff)+0.35, y = natl_margin * 100,
        #          label = " True\n National\n Margin",
        #          hjust = 0, angle = -90,
        #          color = "gray60", size = 3) +
        annotate(geom = "text", x = nrow(comp_df_diff)+.35,
                 y = comp_df_diff$est[comp_df_diff$source_name == "CCES XGB"],
                 label = " CCES\n XGB Target",
                 color = "purple",
                 hjust = 0, angle = -90, size = 3) +
        #for spacing
        annotate(geom = "text", x = nrow(comp_df_pR)+.55,
                 y = comp_df_diff$est[comp_df_diff$source_name == "CCES XGB"],
                 label = "",
                 color = "purple",
                 hjust = 0, angle = -90, size = 3) +
        scale_alpha_discrete(range=c(1, .4)) +
        theme(legend.title = element_blank())
    

    
    
    comp_df_plot_margin <-
        ggplot() +
        aes(x = source_name, y = est, ymin = est - 1.96*SE, ymax = est + 1.96*SE,
            color = as.factor(Conv), shape=as.factor(MF), 
            alpha = if(display_pew_mod) {as.factor(model)
                } else {
                first <-  rep("", nrow(comp_df_margin))
                    if(!cat_kernel) {
                        first[grep("Kpop", comp_df_margin$source_name)] <- "Alt B"
                        first[grep("32", comp_df_margin$source_name)] <- ""
                    } else {
                        first[grep("Kpop", comp_df_margin$source_name)] <- "Alt B"
                        first[grep(paste(best_b, collapse = "|"),
                                   comp_df_margin$source_name)] <- ""
                       
                    }
                    first
            } 
        ) +
        geom_hline(yintercept = c(0, 
                                  #natl_margin*100,
                                 # comp_df_margin$est[comp_df_margin$source_name == "CCES\n Orig"],
                                  comp_df_margin$est[comp_df_margin$source_name == "CCES XGB"]),
                   linetype = c("solid", 
                                #"dashed", #"longdash",
                                "dashed"),
                   color = c("black", 
                             #"gray60", #"black",
                             "purple")) +
        geom_pointrange(data = if(display_pew_mod) {comp_df_margin_merge} else {comp_df_margin}) +
        #geom_pointrange(data = comp_df_margin_pewoutcome, alpha = 0.4) +
        scale_y_continuous(breaks = c(natl_margin, seq(-5, 10, 5)),
                           minor_breaks = NULL,
                           labels = scales::percent_format(scale=1, accuracy = 0.1)) +
        theme_bw() +
        theme(plot.title = element_text(hjust = 0.5)) +
        
        labs(x = NULL, y = "Estimated Modeled Vote Margin (95% CI)") +
        ggtitle(paste(pew_ver, "Pew on CCES XGB Modeled Mean Indiv Vote Margin",
                       out_lab,"modeled\n",NAs_lab, popw_lab, ageb, dnk)) +
        theme(axis.text.x = element_text(angle = 70, hjust = 1,
                                         face=if(PRE& smallB) {
                                             ifelse(comp_df_margin$source_name %in% 
                                                        best_b,
                                                    "bold","plain")
                                         } else if(PRE) {
                                                 rep("plain", nrow(comp_df_margin))
                                         } else {
                                             ifelse(comp_df_margin$source_name %in% 
                                                        best_b,
                                                    "bold","plain")
                                         })) +
        # annotate(geom = "text", x = nrow(comp_df_margin), y = natl_margin * 100,
        #          label = " True\n National\n Margin",
        #          hjust = 0, angle = 90,
        #          color = "gray60", size = 3) +
        annotate(geom = "text", x =  nrow(comp_df_pR)-1,
                 y = comp_df_margin$est[comp_df_margin$source_name == "CCES XGB"],
                 label = " CCES\n XGB Target",
                 color = "purple",
                 hjust = 0, angle = -90, size = 3) +
        #for spacing
        annotate(geom = "text", x =  nrow(comp_df_pR)+.75,
                 y = comp_df_margin$est[comp_df_margin$source_name == "CCES XGB"],
                 label = "",
                 color = "purple",
                 hjust = 0, angle = -90, size = 3) +
        scale_alpha_discrete(range=c(1, .4)) +
        theme(legend.title = element_blank())
    
    
    ####### p(R) plot
    
    comp_df_plot_both_pR <-
        ggplot() +
        aes(x = source_name, y = est, ymin = est - 1.96*SE, ymax = est + 1.96*SE,
            color = as.factor(Conv), shape=as.factor(MF), 
            alpha = if(display_pew_mod) {as.factor(model)
                } else {
                first <-  rep("", nrow(comp_df_pR))
                    if(!cat_kernel) {
                        first[grep("Kpop", comp_df_pR$source_name)] <- "Alt B"
                        first[grep("32", comp_df_pR$source_name)] <- ""
                    } else {
                        first[grep("Kpop", comp_df_pR$source_name)] <- "Alt B"
                        first[grep(paste(best_b, collapse = "|"),
                                   comp_df_pR$source_name)] <- ""
                       
                    }
                    first
            } 
        ) +
        
        geom_hline(yintercept = c(natl_Rep*100,
                                  #comp_df_pR$est[comp_df_pR$source_name == "CCES\n Orig"],
                                  comp_df_pR$est[comp_df_pR$source_name == "CCES XGB"]),
                   linetype = c( "dashed", #"longdash", 
                                 "dashed"),
                   color = c("gray60",# "black",
                             "purple")) +
        geom_pointrange(data = if(display_pew_mod) {comp_df_pR_merge} else {comp_df_pR}) +
       # geom_pointrange(data = comp_df_pR_pewoutcome, alpha = 0.4) +
        scale_y_continuous(breaks = c(natl_Rep, seq(40, 48, 2)),
                           minor_breaks = NULL,
                           labels = scales::percent_format(scale=1, accuracy = 0.1)) +
        theme_bw() +
        theme(plot.title = element_text(hjust = 0.5)) +
        
        labs(x = NULL, y = "Estimated Modeled Vote p(R) (95% CI)") +
        ggtitle(paste(pew_ver,"Pew on CCES XGB Modeled p(R)", out_lab,"modeled\n",
                      popw_lab, ageb, dnk)) +
        theme(axis.text.x = element_text(angle = 70, hjust = 1,
                                         face=if(PRE& smallB) {
                                             ifelse(comp_df_pR$source_name %in% 
                                                       best_b,
                                                    "bold","plain")
                                         } else if(PRE) {
                                                 rep("plain", nrow(comp_df_pR))
                                         } else {
                                             ifelse(comp_df_pR$source_name %in% 
                                                        best_b,
                                                    "bold","plain")
                                         })) +
        annotate(geom = "text", x =  nrow(comp_df_pR)+.35, y = natl_Rep * 100,
                 label = " True\n National\n % Rep",
                 hjust = 0, angle = -90,
                 color = "gray60", size = 3) +
        # annotate(geom = "text", x = nrow(comp_df_pR),
        #          y = comp_df_pR$est[comp_df_pR$source_name == "CCES Orig"],
        #          label = " CCES\n Target",
        #          hjust = 0, angle = 90, size = 3) +
        annotate(geom = "text", x = nrow(comp_df_pR),
                 y = comp_df_pR$est[comp_df_pR$source_name == "CCES XGB"],
                 label = " CCES\n XGB Target",
                 color = "purple",
                 hjust = 0, angle = -90, size = 3) +
        #for spacing
        annotate(geom = "text", x = nrow(comp_df_pR)+.55,
                 y = comp_df_pR$est[comp_df_pR$source_name == "CCES XGB"],
                 label = "",
                 color = "purple",
                 hjust = 0, angle = 90, size = 3) +
        
        scale_alpha_discrete(range=c(1, .4)) +
        theme(legend.title = element_blank())
    
    
    
    ###### p(R) plot
    
    comp_df_plot_both_pD <-
        ggplot() +
        aes(x = source_name, y = est, ymin = est - 1.96*SE, ymax = est + 1.96*SE,
            color = as.factor(Conv), shape=as.factor(MF), 
            alpha = if(display_pew_mod) {as.factor(model)
                } else {
                first <-  rep("", nrow(comp_df_pD))
                    if(!cat_kernel) {
                        first[grep("Kpop", comp_df_pD$source_name)] <- "Alt B"
                        first[grep("32", comp_df_pD$source_name)] <- ""
                    } else {
                        first[grep("Kpop", comp_df_pD$source_name)] <- "Alt B"
                        first[grep(paste(best_b, collapse = "|"),
                                   comp_df_pD$source_name)] <- ""
                       
                    }
                    first
            } 
        ) +
        
        geom_hline(yintercept = c( natl_Dem*100,
                                   #comp_df_pD$est[comp_df_pD$source_name == "CCES\n Orig"],
                                   comp_df_pD$est[comp_df_pD$source_name == "CCES XGB"]),
                   linetype = c( "dashed", #"longdash", 
                                 "dashed"),
                   color = c("gray60", #"black", 
                             "purple")) +
        geom_pointrange(data = if(display_pew_mod) {comp_df_pD_merge} else {comp_df_pD}) +
        #geom_pointrange(data = comp_df_pD_pewoutcome, alpha = 0.4) +
        scale_y_continuous(breaks = c(natl_Rep, seq(40, 56, 4)),
                           minor_breaks = NULL,
                           labels = scales::percent_format(scale=1, accuracy = 0.1)) +
        theme_bw() +
        theme(plot.title = element_text(hjust = 0.5)) +
        
        labs(x = NULL, y = "Estimated Modeled Vote p(R) (95% CI)") +
        ggtitle(paste(pew_ver, "Pew on CCES XGB Modeled p(D)", out_lab,"modeled\n",
                      popw_lab, ageb, dnk)) +
        theme(axis.text.x = element_text(angle = 70, hjust = 1,
                                         face=if(PRE& smallB) {
                                             ifelse(comp_df_pD$source_name %in% 
                                                        best_b,
                                                    "bold","plain")
                                         } else if(PRE) {
                                                 rep("plain", nrow(comp_df_pD))
                                         } else {
                                             ifelse(comp_df_pD$source_name %in% 
                                                       best_b,
                                                    "bold","plain")
                                         })) +
        annotate(geom = "text", x = nrow(comp_df_pR)+.35, y = natl_Dem * 100,
                 label = " True\n National\n % Rep",
                 hjust = 0, angle = 90,
                 color = "gray60", size = 3) +
        # annotate(geom = "text", x = nrow(comp_df_pR),
        #          y = comp_df_pD$est[comp_df_pD$source_name == "CCES Orig"],
        #          label = " CCES\n Target",
        #          hjust = 0, angle = 90, size = 3) +
        annotate(geom = "text", x = nrow(comp_df_pR)-1,
                 y = comp_df_pD$est[comp_df_pD$source_name == "CCES XGB"],
                 label = " CCES\n XGB Target",
                 color = "purple",
                 hjust = 0, angle = 90, size = 3) +
        annotate(geom = "text", x = if(display_pew_mod) {nrow(comp_df_pR_merge)+1.75} else {nrow(comp_df_pR)+1.75},
                 y = comp_df_pD$est[comp_df_pD$source_name == "CCES XGB"],
                 label = "",
                 color = "purple",
                 hjust = 0, angle = 90, size = 3) +
        scale_alpha_discrete(range=c(1, .4)) +
        theme(legend.title = element_blank() )
    

    
    ### output
    out <- list(orig_estimates = clean, 
                plot_diff = comp_df_plot_diff,
                plot_margin = comp_df_plot_margin,
                plot_pR = comp_df_plot_both_pR,
                plot_pD = comp_df_plot_both_pD,
                plot_real_margin = comp_df_plot_real_margin,
                plot_real_diff = comp_df_plot_real_diff,
                pew_dat = pew_xgb, 
                pew_svy = pew_srs_xgb, 
                problem = problem,
                problem_reduc = problem_reduc,
                problem_all = problem_all,
                cces_dat = cces_xgb,
                comp_df_diff = comp_df_diff_merge,
                comp_df_margin = comp_df_margin_merge,
                comp_df_pR = comp_df_pR_merge,
                comp_df_pD = comp_df_pD_merge, 
                comp_df_real_margin = comp_df_real,
                comp_df_real_diff = comp_df_real_diff)
    return(out)
    
}

```



## XGB CCES RUN - 3WAY

```{r xgb_cces_3way}
outcome = cces$recode_vote_2016
#if want to keep NA
outcome[is.na(cces$recode_vote_2016)] = "Other"
out_int <- as.integer(as.factor(outcome))-1

#### 1: RUNNING XGB ON CCES 3WAY VOTE OUTCOME #####

cces_matrix_sparse <- cces %>%
    dplyr::select(recode_age,
           recode_female,
           recode_race,
           recode_region,
           recode_pid_3way,
           recode_educ,
           recode_income,
           #recode_relig has 38 Nas so need to use buckets
           recode_relig_6way,
           recode_born,
           #recode_attndch has some nas need to use buckegs
           recode_attndch_4way,
           recode_race_educ_reg) %>%
    sparse.model.matrix(as.formula("~."), .)

cces_matrix_sparse = cces_matrix_sparse[,-1]


percent <- sample.int(nrow(cces), (nrow(cces)/10)*8)
dat_xgb_train <- xgb.DMatrix(data = cces_matrix_sparse[percent,], 
                             label = out_int[percent])
dat_xgb_outofsamp <- xgb.DMatrix(data = cces_matrix_sparse[-percent,], 
                                 label = out_int[-percent])


#params (not cv'ed)
params = list(
    booster="gbtree",
    eta=0.3,
    max_depth=10,
    min_child_weight = 4,
    gamma=3,
    subsample= 0.7,
    colsample_bytree=1,
    objective="multi:softprob",
    num_class=3,
    eval_metric = "merror"
)

xgbcv <- xgb.cv( params = params,
                 data = dat_xgb_train,
                 nrounds = 500,
                 nfold = 5,
                 early_stopping_rounds = 50,
                 showsd = T,
                 stratified = T,
                 print_every_n = 10,
                 early_stop_round = 20,
                 maximize = F)

low_test  = which(xgbcv$evaluation_log$test_merror_mean == min(xgbcv$evaluation_log$test_merror_mean))
low_test
xgbcv$best_iteration

#run
xgb_cces =xgb.train(params=params,
                    data=dat_xgb_train,
                    nrounds= xgbcv$best_iteration,
                    watchlist = list(validation = dat_xgb_outofsamp),
                    nthreads=2,
                    print_every_n = 10)

#overfit version
# xgb_cces =xgb.train(params=params,
#                     data=dat_xgb_train,
#                     nrounds= 498,
#                     watchlist = list(validation = dat_xgb_outofsamp),
#                     nthreads=2,
#                     print_every_n = 10)



##### EVAL PERFORMANCE ####
xgb_outcome = predict(xgb_cces, dat_xgb_train, reshape=T)
xgb_outofsamp = predict(xgb_cces, dat_xgb_outofsamp, reshape =T)

#convert to max prob outcome:
xgb_plurality_train <- apply(xgb_outcome,1, which.max)
xgb_plurality_test <- apply(xgb_outofsamp,1, which.max)

sum(xgb_plurality_train -1 == out_int[percent])/length(out_int[percent])
sum(xgb_plurality_test - 1 == out_int[-percent])/length(out_int[-percent])

#rep = 2, dem = 0 other = 1
xgb_train_char = case_when(xgb_plurality_train  == 1 ~ "Democrat",
                           xgb_plurality_train  == 3 ~ "Republican",
                           xgb_plurality_train  == 2 ~ "Other")

xgb_test_char = case_when(xgb_plurality_test  == 1 ~ "Democrat",
                          xgb_plurality_test  == 3 ~ "Republican",
                          xgb_plurality_test  == 2 ~ "Other")
#check
sum(xgb_train_char == outcome[percent])/length(percent)
sum(xgb_test_char == outcome[-percent])/length(outcome[-percent])


#look at performance of plurality max:
conf_train = confusionMatrix(as.factor(xgb_train_char), 
                             as.factor(cces$recode_vote_2016)[percent])
conf_test = confusionMatrix(as.factor(xgb_test_char), 
                            as.factor(cces$recode_vote_2016)[-percent])

#because dividing rowwise is annoying:
print("Confusion Matrix: CCES 3way on CCES Training")
t(t(conf_train$table)/colSums(conf_train$table))
print("Confusion Matrix: CCES 3awayon CCES Testing")
t(t(conf_test$table)/colSums(conf_test$table))

```



# RUN 

```{r}

cat_kernel_out <- pew_out(PRE = TRUE,
                           age_buckets = FALSE, 
                           popw = FALSE,
                           three_way = TRUE,
                           drop_ccesNAs = TRUE, 
                           noDNK_weights = TRUE, 
                           xgb_cces_mod = xgb_cces,
                           bigB = TRUE, 
                           smallB = TRUE,
                           cat_kernel = TRUE, 
                      display_pew_mod = FALSE)



cat_kernel_out$plot_real_diff
#ggsave("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/Working/current plots/app_cat_real_vdiff_allb.pdf", width = 14, height = 8)
cat_kernel_out$plot_diff
ggsave("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/Working/current plots/votediff_t1e-06_m500_allb.pdf", width = 14, height = 8)
cat_kernel_out$plot_real_margin
#ggsave("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/Working/current plots/app_cat_real_vmargin_allb.pdf", width = 14, height = 8)
cat_kernel_out$plot_margin
#ggsave("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/Working/current plots/app_cat_vmargin_allb.pdf", width = 14, height = 8)
cat_kernel_out$plot_pR
#ggsave("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/Working/current plots/app_cat_pR_allb.pdf", width = 14, height = 8)
cat_kernel_out$plot_pD
#ggsave("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/Working/current plots/app_cat_pD_allb.pdf", width = 14, height = 8)

# View(cat_kernel$comp_df_margin)
# View(cat_kernel$comp_df_diff)
# View(cat_kernel$comp_df_real_diff)
# View(cat_kernel$comp_df_real_margin)





```





# Eval Margins

```{r margins}
########## Margins Function #############

allmargins <- function(pop_weights = FALSE, 
                       age_buckets = FALSE,
                       b = 32,
                       three_way,
                       pew_xgb_dat,
                       cces_xgb_dat,
                       drop_ccesNAs, 
                       margins_formula = NULL, 
                       order = NULL,
                       cat_kernel) {
    
    if(drop_ccesNAs &!cat_kernel) {
        if(b == 64) {
            index = 1
        } else if(b == 32) {
            index = 2
        } else if(b==16) {
            index = 3
        } else if(b==8) {
            index = 4
        } else if(b==4) {
            index = 5 
        } else if(b ==2) {
            index = 6
        } else if(b ==1) {
            index = 7
        } else {
            stop("Must enter b in range 1-64 factors of 2")
        }
    } else if(!cat_kernel) {
        if(b == 32) {
            index = 1
        } else if(b == 16) {
            index = 2
        } else if(b==8) {
            index = 3
        } else if(b==4) {
            index = 4
        } else if(b==2) {
            index = 5 
        } else if(b ==1) {
            index = 6
        } else {
            stop("Must enter b in range 1-32 factors of 2")
        }
    }
    if(cat_kernel) {
       index = which(b_run == b)
        if(length(index) == 0 ) {
            stop("Must enter b in range of b_run")
        }
    }
    
    #build some interactions we want to lookat:
    cces_xgb_dat <- cces_xgb_dat %>% mutate(
    #36 levels
    recode_educ_pid_race = as.factor(paste(recode_educ_3way,
                                           recode_pid_3way, 
                                           recode_race, sep = ", ")),
    #12 levels
    recode_pid_race = as.factor(paste(recode_pid_3way, 
                                           recode_race, sep = ", ")),
    #9 levels
    recode_educ_pid = as.factor(paste(recode_educ_3way,
                                      recode_pid_3way, sep = ", ")),
    recode_agesq = recode_age*recode_age,
    recode_agecubed = recode_age*recode_age*recode_age,
    #13 levles
    recode_midwest_edu_race = as.factor(
        case_when(recode_region == "Midwest" ~ paste(recode_region,
                                                     recode_race,
                                                     recode_educ_3way, 
                                                     sep = ", "),
                  TRUE ~ "No Split")), 
    #4 levels ( low educated whites in midwest only)
    recode_midwest_wh_edu = factor(case_when(
        (recode_race != "White" | recode_region != "Midwest") ~ "No Split", 
        TRUE ~ as.character(recode_educ_3way)), 
        levels = c("No Split", "No College", "College", "Post-grad")), 
    recode_age_factor = factor(case_when(recode_age <92 ~ as.character(recode_age), 
                                         TRUE ~ "92+")) )


    pew_xgb_dat <- pew_xgb_dat %>% mutate(
        #this has 36 levles
        recode_educ_pid_race = as.factor(paste(recode_educ_3way,
                                               recode_pid_3way, 
                                               recode_race, sep = ", ")),
        #12 levels
        recode_pid_race = as.factor(paste(recode_pid_3way, 
                                          recode_race, sep = ", ")),
        #this has 9 levles
        recode_educ_pid = as.factor(paste(recode_educ_3way,
                                          recode_pid_3way, sep = ", ")),
        recode_agesq = recode_age*recode_age,
        recode_agecubed = recode_age*recode_age*recode_age,
        
        #this has 13 levels
        recode_midwest_edu_race = as.factor(
            case_when(recode_region == "Midwest" ~ paste(recode_region,
                                                         recode_race,
                                                         recode_educ_3way, 
                                                         sep = ", "),
                      TRUE ~ "No Split")),
        #this has 4 levels
        recode_midwest_wh_edu = factor(case_when(
            (recode_race != "White" | recode_region != "Midwest") ~ "No Split", 
            TRUE ~ as.character(recode_educ_3way)), 
            levels = c("No Split", "No College", "College", "Post-grad")),
        recode_age_factor = factor(case_when(recode_age <92 ~ as.character(recode_age), 
                                             TRUE ~ "92+")) )
    
    cces_nowt <- suppressWarnings(svydesign(ids = ~1, data = cces_xgb_dat))
    cces_awt <- svydesign(ids = ~1, weights = ~commonweight_vv_post,
                          data = cces_xgb_dat)
    pew_nowt <- suppressWarnings(svydesign(ids = ~1, data = pew_xgb_dat))
    
    missing_strata <- unique(cces_xgb_dat$strata)[!(unique(cces_xgb_dat$strata) %in%
                                                        unique(pew_xgb_dat$strata))]

    missing_strata_reduc <- unique(cces_xgb_dat$strata_reduc)[!(unique(cces_xgb_dat$strata_reduc) %in%
                                                unique(pew_xgb_dat$strata_reduc))]
  
    missing_strata_all <- unique(cces_xgb_dat$strata_all)[!(unique(cces_xgb_dat$strata_all) %in%
                                                unique(pew_xgb_dat$strata_all))]
    
    problem <- unique(pew_xgb_dat$strata)[!(unique(pew_xgb_dat$strata) %in%
                                                   unique(cces_xgb_dat$strata))]
    problem_reduc <- unique(pew_xgb_dat$strata_reduc)[!(unique(pew_xgb_dat$strata_reduc)
                                                         %in%
                                                   unique(cces_xgb_dat$strata_reduc))]
    
    problem_all <- unique(pew_xgb_dat$strata_all)[!(unique(pew_xgb_dat$strata_all) %in%
                                                   unique(cces_xgb_dat$strata_all))]
    

    kbal_data_sampled <- c(rep(1, nrow(pew_xgb_dat)),
                           rep(0, nrow(cces_xgb_dat)))
    
    if(cat_kernel) {
        
        # if(is.null(altB)) {
        #     load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/allB_cat.Rdata") 
        # } else if(altB) {
        #     load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/altB_cat.Rdata") 
        #     weights_cat <- weights_cat_alt
        # }
        # load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/allB_cat_2021-02-25.Rdata")
        # load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/allB_cat_parallel_2021-02-26.Rdata")
        
        #tolerance 1e-6 and increase maxit to 500, maxnumdims 500
load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/allB_cat_par_m500_t1e-06_2021-03-04.Rdata")
        
        kpop_w <- weights_cat[[index]]$kpop_w
        kpop_conv_w <- weights_cat[[index]]$kpop_w_conv
        kpop_mf_w <- weights_cat[[index]]$kpop_mf_w
        kpop_constr_w <- weights_cat[[index]]$kpop_contraint
        kpop_full_constr_w <- weights_cat[[index]]$kpop_full_constraintt
        cces_svy <- cces_nowt
        #colnames_bottom = c("No Wts", "No Wts", "(cat)", "(cat)", "(cat)","all", 
             #                       "reduc", "all", "retro")
        b_lab = paste0("b=", b)
        colnames_bottom =  c("", "No Wts", b_lab, b_lab, b_lab, b_lab,
                             "all", "reduc",
                             "all", "retro")
    } else if(drop_ccesNAs) {
        # load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/kpop_nodnk_noNas_nopopw.Rdata")
        load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/noNAs_nopopw.Rdata")
        kpop_w <- weights_nodnk_noNAs_nopopw[[index]]$kpop_w
        kpop_conv_w <- weights_nodnk_noNAs_nopopw[[index]]$kpop_w_conv
        kpop_mf_w <- weights_nodnk_noNAs_nopopw[[index]]$kpop_mf_w
        
    } else if(pop_weights) {
            cces_svy <- cces_awt
            
            if(age_buckets) {
                #note this is identitcal to the rerun for 32 check here:
                #load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/kbal_32_wpop_rerun.Rdata")
                 load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/kpop_nodnk_agebuck_wpopw.Rdata")
                caption_m = "Margins (Difference): w/Pop W. (OLD) Outcomes + Age Buckets (no dnk)"
                caption_o = "Outcomes (Difference): w.Pop W. (OLD) Outcomes + Age Buckets (no dnk)"
                caption_vm = "Vote Margins: w/Pop W. (OLD) + Age Buckets (no dnk)"
            
                kpop_w <- weights_nodnk_agebuckets_wpopw[[index]]$kpop_w
                kpop_conv_w <- weights_nodnk_agebuckets_wpopw[[index]]$kpop_w_conv
                kpop_mf_w <- weights_nodnk_agebuckets_wpopw[[index]]$kpop_mf_w
                b_lab = paste0("b",b,"x")
                colnames_bottom = c("Wts", "Wts", b_lab, b_lab, b_lab,"all", 
                                    "reduc", "all", "retro")
                # colnames_bottom = c("Wts", "Wts", b_lab, b_lab, b_lab,
                #                     "noeduc", "weduc", "all", "", "reduc", "all", "retro")
                
            } else { #POP W + NO AGE BUCKETS
                load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/kpop_nodnk_fixed.Rdata")
                
                caption_m = "Margins (Difference): w/Pop W.(OLD) Outcomes + No Age Buckets (no dnk)"
                caption_o = "Outcomes (Difference): w/Pop W.(OLD) Outcomes + No Age Buckets (no dnk)"
                caption_vm = "Vote Margins: w/Pop W.(OLD) + No Age Buckets (no dnk)"
                b_lab = paste0("b",b,"x")
                 colnames_bottom = c("Wts", "Wts", b_lab, b_lab, b_lab,"all", 
                                    "reduc", "all", "retro")
                # colnames_bottom =  c("Wts", "ts", b_lab, b_lab, b_lab,
                #                     "noeduc", "weduc", "all", "", "reduc", "all", "retro")
                kpop_w <- weights_nodnk[[index]]$kpop_w
                kpop_conv_w <- weights_nodnk[[index]]$kpop_w_conv
                kpop_mf_w <- weights_nodnk[[index]]$kpop_mf_w
            }
        } else { #NO POP WEGIHTS
            cces_svy <- cces_nowt
            b_lab = paste0("b", b, "x")
             colnames_bottom = c("No Wts", "No Wts", b_lab, b_lab, b_lab, b_lab,"all", 
                                    "reduc", "all", "retro")
            # colnames_bottom =  c("No Wts", "No Wts", b_lab, b_lab, b_lab,
            #                         "noeduc", "weduc", "all", "", "reduc", "all", "retro")
            if(drop_ccesNAs) {
                # load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/kpop_nodnk_noNas_nopopw.Rdata")
                load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/noNAs_nopopw.Rdata")
                kpop_w <- weights_nodnk_noNAs_nopopw[[index]]$kpop_w
                kpop_conv_w <- weights_nodnk_noNAs_nopopw[[index]]$kpop_w_conv
                kpop_mf_w <- weights_nodnk_noNAs_nopopw[[index]]$kpop_mf_w
                
            } else {
                 if(age_buckets) {
                     load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/kpop_nodnk_agebuckets_nopopw.Rdata")
                } else {
                    load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/kpop_nodnk_nopopw.Rdata")
                }
                kpop_w <- weights_nodnk_nopopw[[index]]$kpop_w
                kpop_conv_w <- weights_nodnk_nopopw[[index]]$kpop_w_conv
                kpop_mf_w <- weights_nodnk_nopopw[[index]]$kpop_mf_w
                
                }
           
    }
    
     targets_rake_demos_noeduc <- create_targets(cces_svy,
                                                    formula_rake_demos_noeduc)
     targets_rake_demos_weduc <- create_targets(cces_svy, formula_rake_demos_weduc)
     targets_rake_all_vars <- create_targets(cces_svy, 
                                                       formula_rake_all_vars)
     targets_retrospective <- create_targets(cces_svy, formula_retrospective)
     targets_ps <- svytable(formula = ~strata,
                               design = subset(cces_svy, !(strata %in%
                                                                missing_strata)))
     targets_ps_reduc <- svytable(formula = ~strata_reduc,
                               design = subset(cces_svy, !(strata_reduc %in%
                                                                missing_strata_reduc)))
     targets_ps_all <- svytable(formula = ~strata_all,
                               design = subset(cces_svy, !(strata_all %in%
                                                                missing_strata_all)))
     
     rake_demos_noeduc <- calibrate(design = pew_nowt,
                                   formula = formula_rake_demos_noeduc,
                                   population = targets_rake_demos_noeduc,
                                   calfun = "raking")
     rake_demos_noeduc <- svydesign(~1, data = pew_xgb_dat, 
                                   weights = weights(rake_demos_noeduc))
    
     rake_demos_weduc <- calibrate(design = pew_nowt,
                                  formula = formula_rake_demos_weduc,
                                  population = targets_rake_demos_weduc,
                                  calfun = "raking")
     rake_demos_weduc <- svydesign(~1, data = pew_xgb_dat, 
                                  weights = weights(rake_demos_weduc))
    
     rake_all_vars <- calibrate(design = pew_nowt,
                                  formula = formula_rake_all_vars,
                                  population = targets_rake_all_vars,
                                  calfun = "raking")
     rake_all_vars <- svydesign(~1, data = pew_xgb_dat, 
                                  weights = weights(rake_all_vars))
    
    #post stratification
    pew_ps_xgb <- svydesign(ids = ~1, 
                            data = pew_xgb_dat %>% filter(!(strata %in% problem)))
    post_stratification <- postStratify(design = pew_ps_xgb,
                                        strata = ~strata,
                                        population = targets_ps)
    post_stratification <- svydesign(~1, data = pew_xgb_dat %>% 
                                         filter(!(strata %in% problem)),
                                     weights = weights(post_stratification))
    #reduced
    pew_ps_reduc_xgb <- svydesign(ids = ~1, data = pew_xgb_dat %>% 
                                      filter(!(strata_reduc %in% problem_reduc)))
    post_strat_reduc <- postStratify(design = pew_ps_reduc_xgb,
                                        strata = ~strata_reduc,
                                        population = targets_ps_reduc)
    post_strat_reduc <- svydesign(~1, data = pew_xgb_dat %>%
                                      filter(!(strata_reduc %in% problem_reduc)),
                                     weights = weights(post_strat_reduc))
    
    pew_ps_all_xgb <- svydesign(ids = ~1,  data = pew_xgb_dat %>%  
                                    filter(!(strata_all %in% problem_all)))
    post_strat_all <- postStratify(design = pew_ps_all_xgb,
                                        strata = ~strata_all,
                                        population = targets_ps_all)
    post_strat_all <- svydesign(~1, data = pew_xgb_dat %>% 
                                    filter(!(strata_all %in% problem_all)),
                                weights = weights(post_strat_all))
    
    rake_retrospective <- calibrate(design = pew_nowt,
                                    formula = formula_retrospective,
                                    population = targets_retrospective,
                                    calfun = "raking",
                                    force = TRUE)
    rake_retrospective <- svydesign(~1,
                                    data = pew_xgb_dat,
                                    weights = weights(rake_retrospective))
    
    # kpop
    kpop <- svydesign(~1, data = pew_xgb_dat,
                weights = kpop_w[kbal_data_sampled ==1])

    kpop_conv <- svydesign(~1, data = pew_xgb_dat,
                               weights = kpop_conv_w[kbal_data_sampled ==1])
    
    kpop_mf <-  svydesign(~1, data = pew_xgb_dat,
                              weights = kpop_mf_w[kbal_data_sampled ==1])
    
    
    
    
    if(cat_kernel) {
         kpop_constr <-  svydesign(~1, data = pew_xgb_dat,
                              weights = kpop_constr_w[kbal_data_sampled ==1])
         
         kpop_full_constr <-  svydesign(~1, data = pew_xgb_dat,
                              weights = kpop_full_constr_w[kbal_data_sampled ==1])
         
    }
    
    if(is.null(margins_formula)) {
        if(three_way) {
            margins_formula <- ~recode_vote_2016 +
                xgb_cces_on_pew_pD + xgb_cces_on_pew_pR + xgb_cces_on_pew_pO +
                xgb_pew_on_pew_pD + xgb_pew_on_pew_pR + xgb_pew_on_pew_pO + 
                recode_pid_3way + 
                recode_female + recode_race +recode_region + recode_educ +recode_relig_6way+
                recode_born + recode_attndch_4way + recode_income_5way +
                recode_age_bucket+recode_age+recode_agesq+recode_agecubed+recode_age_factor+
                recode_race_educ_reg + recode_educ_wh_3way + 
                recode_educ_pid_race +
                recode_pid_race + 
                recode_educ_pid +
                recode_midwest_edu_race +
                recode_midwest_wh_edu


          margins_formula_cces <- ~recode_vote_2016 +
            xgb_cces_on_cces_pD + xgb_cces_on_cces_pR + xgb_cces_on_cces_pO +
            xgb_pew_on_cces_pD + xgb_pew_on_cces_pR + xgb_pew_on_cces_pO + 
            recode_pid_3way + 
            recode_female + recode_race +recode_region + recode_educ + recode_relig_6way + 
            recode_born + recode_attndch_4way + recode_income_5way +
            recode_age_bucket + recode_age +recode_agesq+recode_agecubed+recode_age_factor +
            recode_race_educ_reg + recode_educ_wh_3way + 
            recode_educ_pid_race +
            recode_pid_race + 
            recode_educ_pid +
            recode_midwest_edu_race +
            recode_midwest_wh_edu
     } else {
         margins_formula <- ~recode_vote_2016 +
                xgb_cces_on_pew_pD + xgb_cces_on_pew_pR + 
                xgb_pew_on_pew_pD + xgb_pew_on_pew_pR + 
                recode_pid_3way + 
                recode_female + recode_race +recode_region + recode_educ +recode_relig_6way+
                recode_born + recode_attndch_4way + recode_income_5way +
                recode_age_bucket+recode_age+recode_agesq+recode_agecubed+recode_age_factor+
                recode_race_educ_reg + recode_educ_wh_3way + 
                recode_educ_pid_race +
                recode_pid_race + 
                recode_educ_pid +
                recode_midwest_edu_race +
                recode_midwest_wh_edu
         
          margins_formula_cces <- ~recode_vote_2016 +
            xgb_cces_on_cces_pD + xgb_cces_on_cces_pR + 
            xgb_pew_on_cces_pD + xgb_pew_on_cces_pR + 
            recode_pid_3way + 
            recode_female + recode_race +recode_region + recode_educ + recode_relig_6way + 
            recode_born + recode_attndch_4way + recode_income_5way +
            recode_age_bucket + recode_age +recode_agesq+recode_agecubed+recode_age_factor +
            recode_race_educ_reg + recode_educ_wh_3way + 
            recode_educ_pid_race +
            recode_pid_race + 
            recode_educ_pid +
            recode_midwest_edu_race +
            recode_midwest_wh_edu
     }
    }
    
    margins <- round(cbind(
        pew = svymean(margins_formula, pew_nowt),
        cces_margins = svymean(margins_formula_cces, cces_svy, 
                               na.rm = ifelse(drop_ccesNAs, TRUE, FALSE)),
        kpop = svymean(margins_formula, kpop),
        kpop_mf = svymean(margins_formula, kpop_mf),
        kpop_conv = svymean(margins_formula, kpop_conv),
        kpop_constr = if(cat_kernel) {
            svymean(margins_formula, kpop_constr)
            }else {NA},
        kpop_full_constr = if(cat_kernel) {
            svymean(margins_formula, kpop_full_constr)
            }else {NA},
        #rake_demos_noeduc = svymean(margins_formula, rake_demos_noeduc),
        #rake_demos_weduc = svymean(margins_formula, rake_demos_weduc),
        rake_all_vars = svymean(margins_formula, rake_all_vars),
        #post_stratification = svymean(margins_formula, post_stratification),
        post_strat_reduc = svymean(margins_formula, post_strat_reduc),
        post_strat_all = svymean(margins_formula, post_strat_all),
        rake_retrospective = svymean(margins_formula, rake_retrospective)) * 100, 5)
    #we multiplied the recode_age margins by 100 unnecc above bc it' just a straight mean
    #so let's undo that
    
    rownames(margins) <- sapply(rownames(margins), 
                                       function(x) (
                                           if(grepl("recode", x)) {
                                               substr(x, 8,nchar(x) )
                                           } else {
                                               x
                                           }
                                       ) )
    margins["age",] <- margins["age",]/100 
    margins["agesq",] <- margins["agesq",]/100
    margins["agecubed",] <- margins["agecubed",]/100


    margins_diff <- as.data.frame(margins) %>% 
        mutate(pew = cces_margins - pew,
               kpop = cces_margins - kpop,
               kpop_mf = cces_margins - kpop_mf,
               kpop_conv = cces_margins - kpop_conv,
               kpop_constr = if(cat_kernel) {cces_margins - kpop_constr }
               else {NA},
               kpop_full_constr = if(cat_kernel) {cces_margins - kpop_full_constr }
               else {NA},
               #rake_demos_noeduc = cces_margins- rake_demos_noeduc,
               #rake_demos_weduc = cces_margins- rake_demos_weduc,
               rake_all_vars = cces_margins - rake_all_vars,
               #post_stratification = cces_margins-  post_stratification,
               post_strat_reduc = cces_margins-  post_strat_reduc,
               post_strat_all = cces_margins-  post_strat_all,
               rake_retrospective = cces_margins- rake_retrospective)
    rownames(margins_diff) <- rownames(margins)
    
    #get cces proportions:
    
    #weighted average here: compensating for the fact we *100 by 100 above and
    #we will take the straight average below so /100*n
    #we already have p-q, so here we are just q*(p-q)
    # p = margins[(grep("age_factor", rownames(margins))), ]
    # q = margins[grep("age_factor", rownames(margins)), "cces_margins"]
    # colMeans(abs(p-q)*q/100*length(q))
    # colMeans(abs((p-q)*q)/100*length(q))
    
    margins_diff[(grep("age_factor", rownames(margins_diff))), ] <-
      (margins_diff[(grep("age_factor", 
                          rownames(margins_diff))),
                    ])* (margins[grep("age_factor", rownames(margins)), "cces_margins"]/100)*length(levels(cces_xgb_dat$recode_age_factor))
    #### summarize
    #HAHAHHAHAHAHA i dont know how to regex but it works. this is horrific I should switch to str_extract now that i belatedly discovered it
    wmabserr <- margins_diff %>% 
    mutate(var = sapply(rownames(margins_diff), 
                        function(y) {
                            substr(y, 1, 
                                   sapply(rownames(margins_diff), 
                                          function(x) {
                                              if(grepl("income",x)) {
                                                  11 #income_5way
                                             #this is so ridiculous WHY (sunk cost ugh)
                                              } else if(grepl("xgb",x) |
                                                        (grepl("age",x) & 
                                                         !grepl("bucket",x) &
                                                         !grepl("factor",x)) ){
                                                  nchar(x) #keep all xgb stuff
                                                  #THIS IS SO STUPID
                                              } else if(grepl("factor",x)) {
                                                  10 #age_factor
                                              } else {
                                               (gregexpr("[A-Z]|[1-9][1-9] |[1-9][1-9]\\+|[1-9]\\-", x)[[1]][1]-1)
                                              }
                                          })[y])
                        })) %>%
    group_by(var) %>% summarize(pew_unweighted = mean(abs(pew)), 
                                kpop = mean(abs(kpop)),
                                kpop_conv = mean(abs(kpop_conv)), 
                                kpop_mf = mean(abs(kpop_mf)),
                                kpop_constr = mean(abs(kpop_constr)),
                                kpop_full_constr = mean(abs(kpop_full_constr)),
                                #rake_demos_noeduc = mean(abs(rake_demos_noeduc)),
                                #rake_demos_weduc = mean(abs(rake_demos_weduc)), 
                                rake_all_vars = mean(abs(rake_all_vars)), 
                                #post_stratification =
                                #    mean(abs(post_stratification)),
                                post_strat_reduc = mean(abs(post_strat_reduc)),
                                post_strat_all = mean(abs(post_strat_all)),
                                rake_retrospective = mean(abs(rake_retrospective)))
    #for kable aethetics later this helps
    wmabserr$var[wmabserr$var == "educ"]<- "educ_6way"
    
    if(!cat_kernel) {
        margins <- margins[,-which(colnames(margins) == "kpop_constr")]
        margins_diff <- margins_diff[,-which(colnames(margins_diff) == "kpop_constr")]
        wmabserr <- wmabserr[,-which(colnames(wmabserr) == "kpop_constr")]
        
        margins <- margins[,-which(colnames(margins) == "kpop_full_constr")]
        margins_diff <- margins_diff[,-which(colnames(margins_diff) == "kpop_full_constr")]
        wmabserr <- wmabserr[,-which(colnames(wmabserr) == "kpop_full_constr")]
    }
    
    #labels
    if(age_buckets) {
        ageb = "+ Age Buckets"
    } else {
        ageb =""
    }
    if(pop_weights) {
        popw_lab = "w/ Pop Weights"
    } else {
        popw_lab = "No pop Weights"
    }
    if(three_way) {
        xgb_lab = " (3way xgb)"
    } else {
        xgb_lab = " (2way xgb)"
    }
    if(drop_ccesNAs) {
        NAs_lab = "No CCES NAs "
    } else {
        NAs_lab = "No CCES NAs "
    }
    if(!cat_kernel) {
        caption_m = paste0("Margins (Difference): ",NAs_lab, popw_lab, ageb, " (no dnk) ",
                       "b=", b, xgb_lab)
        caption_o = paste0("Absolute Error on Margins of Outcomes and First Moments: ",
                       NAs_lab, popw_lab, ageb, " (no dnk) ",
                       "b=", b, xgb_lab)
    
        caption_err = paste0("Weighted Mean Abs Error: ", NAs_lab, popw_lab, ageb, " (no dnk) ",
                       "b=", b, xgb_lab)
    } else {
        caption_m = paste0("Margins (Difference): Unscaled K ", "b=", b,NAs_lab, popw_lab, " Age Buckets Only (no dnk) ",
                       xgb_lab)
        caption_o = paste0("Absolute Error on Margins of Outcomes and First Moments: Unscaled K ","b=", b,
                       NAs_lab, popw_lab, " Age Buckets Only (no dnk) ",
                        xgb_lab)
    
        caption_err = paste0("Weighted Mean Abs Error: Unscaled K ","b=", b, NAs_lab, popw_lab,
                              " Age Buckets Only (no dnk) ",xgb_lab)
    }
    
    #rearrange: c() #(var %in% c("age", "agesq", "agecubed") |
    wmabserr_nooutcomes <- wmabserr %>% 
        filter(!(var %in% c("agecubed") |grepl("xgb", var) | grepl("vote", var))) %>%
        arrange(nchar(var))
    if(is.null(order)) {
        order = c("female", "pid_3way", "race", "region", "educ_6way", "income_5way", 
                  "relig_6way", 
                  "pid_race", "educ_pid",
                  "educ_pid_race", "race_educ_reg", "educ_wh_3way", "midwest_wh_edu",
                  "midwest_edu_race",
                  "agesq", "age_factor")
    }
    
    wmabserr_nooutcomes <- wmabserr_nooutcomes[as.numeric(sapply(order, function(x) which(wmabserr_nooutcomes$var == x))),]
    
    # #this messes up the roundign in kable if you actually pass a character for var so...
    # wmabserr_nooutcomes <-  wmabserr_nooutcomes %>% rbind(c(0,
    #                                  colMeans(wmabserr_nooutcomes[, -1])))
    # #this is so stupid but for the rounding to work
    # wmabserr_nooutcomes$var[nrow(wmabserr_nooutcomes)] <- "Column Average"
    
    
    noedu_aes <- sapply(wmabserr_nooutcomes$var, function(x) {
            ifelse(grepl(x, as.character(formula_rake_demos_noeduc)[2]),
                   "gray", "black") })
    wedu_aes <-  sapply(wmabserr_nooutcomes$var, function(x) {
            ifelse(grepl(x, as.character(formula_rake_demos_weduc)[2]), "gray", "black")
        })
    all_aes <-  sapply(wmabserr_nooutcomes$var, function(x) {
            ifelse(grepl(x, as.character(formula_rake_all_vars)[2]) | x == "educ_6way", "gray", "black")
        })
    
    ps_aes <- sapply(wmabserr_nooutcomes$var, function(x) {
            ifelse(grepl(x, as.character(formula_ps)[2]), "gray", "black") })
    ps_reduc_aes <- sapply(wmabserr_nooutcomes$var, function(x) {
            ifelse(grepl(x, as.character(formula_ps_reduc)[2]), "gray", "black") })
    ps_all_aes <- sapply(wmabserr_nooutcomes$var, function(x) {
            ifelse(grepl(x, as.character(formula_ps_all)[2]), "gray", "black") })
    
    retro_aes <- sapply(wmabserr_nooutcomes$var, function(x) {
            ifelse(grepl(x, as.character(formula_retrospective)[2]), "gray", "black") })
    if(!cat_kernel) {
        formula_kpop <- c("age", "female", "race",
                      "region", "pid_3way","educ_6way", "income_5way",
                      "relig_6way","born","attndch_4way", 
                      if(age_buckets){ "age_buckets"})
    } else {
        formula_kpop <- c("age_buckets", "female", "race",
                      "region", "pid_3way","educ_6way", "income_5way",
                      "relig_6way","born","attndch_4way")
    }
    
    kpop_aes <- ifelse((wmabserr_nooutcomes$var %in% formula_kpop), "gray", "black")
    
    if(cat_kernel) { 
        kpop_constr_aes <- noedu_aes
        kpop_full_constr_aes <- all_aes
        # #wmabserr_nooutcomes[, -which(colnames(wmabserr_nooutcomes) == "kpop_full_constr")]
        #  kable_err <- kable(wmabserr_nooutcomes,
        #                format = "latex",
        #                caption = caption_err,
        #               col.names = c("Variable", colnames_bottom[-2]),
        #                booktabs = T,
        #                digits = 3) %>% kable_styling() %>%
        #         column_spec(5,
        #                 color =kpop_aes) %>%
        #         column_spec(6,
        #                 color =kpop_constr_aes) %>%
        #      column_spec(7,
        #                 color =kpop_full_constr_aes) %>%
        #         column_spec(8,
        #                 color = all_aes) %>%
        #         column_spec(9,
        #                 color =ps_reduc_aes) %>%
        #         column_spec(10,
        #                 color =ps_all_aes) %>%
        #         column_spec(11,
        #                 color =retro_aes)
        
         kable_err <- kable(wmabserr_nooutcomes[, -which(colnames(wmabserr_nooutcomes) == "kpop_full_constr")],
                       format = "latex",
                       caption = caption_err,
                      col.names = c("Variable", colnames_bottom[-2]),
                       booktabs = T,
                       digits = 3) %>% kable_styling() %>%
                column_spec(5,
                        color =kpop_aes) %>%
                column_spec(6,
                        color =kpop_constr_aes) %>%
                column_spec(7,
                        color = all_aes) %>%
                column_spec(8,
                        color =ps_reduc_aes) %>%
                column_spec(9,
                        color =ps_all_aes) %>%
                column_spec(10,
                        color =retro_aes)
        
        
        
    } else {
        kable_err <- kable(wmabserr_nooutcomes,
                       format = "latex",
                       caption = caption_err,
                       col.names = c("Variable", colnames_bottom[-2]),
                       booktabs = T,
                       digits = 3) %>% kable_styling() %>%
                column_spec(5,
                        color =kpop_aes) %>%
                column_spec(6,
                        color = all_aes) %>%
                column_spec(7,
                        color =ps_reduc_aes) %>%
                column_spec(8,
                        color =ps_all_aes) %>%
                column_spec(9,
                        color =retro_aes)
    }
        
    
  
    # kable_err <- kable(wmabserr_nooutcomes,
    #                    format = "latex",
    #                    caption = caption_err, 
    #                    col.names = c("Variable", colnames_bottom[-2]),
    #                    booktabs = T,
    #                    digits = 3) %>% kable_styling() %>%
    #     column_spec(5, 
    #             color =kpop_aes) %>%
    #     column_spec(6, 
    #             color =noedu_aes) %>%
    #     column_spec(7, 
    #             color =wedu_aes) %>%
    #     column_spec(8, 
    #             color =all_aes) %>%
    #     column_spec(9, 
    #             color =ps_aes) %>%
    #     column_spec(10, 
    #             color =ps_reduc_aes) %>%
    #     column_spec(11, 
    #             color =ps_all_aes) %>%
    #     column_spec(12, 
    #             color =retro_aes)
    
    #wmabserr[, -which(colnames(wmabserr) == "kpop_full_constr")]
    kable_om <- kable(wmabserr[, -which(colnames(wmabserr) == "kpop_full_constr")] %>% 
                          filter((var %in% c("age", "agesq", "agecubed") |
                                      grepl("xgb", var) |
                                      grepl("vote", var))) %>% arrange(nchar(var)),
                       format = "latex",
                       caption = caption_o, 
                       col.names = c("Variable", colnames_bottom[-2]),
                       booktabs = T,
                       digits = 3)
    margins_out <- margins_diff[-c(1:9),]
    margins_out <- margins_out[!grepl("age_factor", rownames(margins_out)), ] 
    # margins_out <- margins_out %>% rbind(colMeans(margins_out))
    # rownames(margins_out)[nrow(margins_out)] <- "Column Average"
    
    #margins_out[, -which(colnames(margins_out) == "kpop_full_constr")]
    kable_margins <- kable(margins_out[, -which(colnames(margins_out) == "kpop_full_constr")],
          format = "latex",
          caption = caption_m,
          col.names = colnames_bottom,
          booktabs = T, digits= 3) 
    
    out <- list(margins = margins,
                margins_diff = margins_diff,
                wmabserr = wmabserr,
                wmabserr_nooutcomes = wmabserr_nooutcomes,
                kable_err = kable_err,
                kable_outmom = kable_om, 
                kable_margins= kable_margins)
    return(out)
}

```

```{r run_specific}
load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/allB_cat_par_m500_t1e-06_2021-03-04.Rdata")
b_run <- out_cat$b

cat_margins <- allmargins(pop_weights = FALSE, 
                             age_buckets = FALSE, 
                             three_way = TRUE, 
                             b = b_run[2],
                             pew_xgb_dat = cat_kernel_out$pew_dat,
                             cces_xgb_dat = cat_kernel_out$cces_dat, 
                             drop_ccesNAs = TRUE, 
                              cat_kernel = TRUE)
View(cat_margins$wmabserr)
cat_margins$kable_err
cat_margins$kable_outmom
cat_margins$kable_margins

cat_margins_best <- allmargins(pop_weights = FALSE, 
                             age_buckets = FALSE, 
                             three_way = TRUE, 
                             b = b_run[13],
                             pew_xgb_dat = cat_kernel_out$pew_dat,
                             cces_xgb_dat = cat_kernel_out$cces_dat, 
                             drop_ccesNAs = TRUE, 
                              cat_kernel = TRUE)

cat_margins_best$kable_err
cat_margins_best$kable_outmom


# 
# 
# 
# 
# kpop_w_age <- (kpop_w[kbal_data_sampled ==1]*pew_xgb_dat$recode_age)
# 
# ks.test(kpop_w_age, cces_xgb_dat$recode_age)
# 
# kpop_age <- data.frame(x = kpop_w[kbal_data_sampled ==1]*pew_xgb_dat$recode_age)
# rake_demos_age <- data.frame(x = weights(rake_demos_noeduc)*pew_xgb_dat$recode_age)
# ps_age <- data.frame(x = weights(post_stratification)*pew_xgb_dat$recode_age)
# ggplot() +
#     stat_ecdf(geom = "step", aes(x=x,color = "Kpop"), 
#               data = kpop_age) +
#      # stat_ecdf(geom = "step", aes(x=x,color = "Rake No Edu"), 
#      #          data = rake_demos_age) +
#      # stat_ecdf(geom = "step", aes(x=x,color = "PS"), 
#      #          data = ps_age) +
#     stat_ecdf(geom = "step", aes(x=recode_age,color = "CCES Unweighted"),
#               data = cces_xgb_dat) +
#     theme_bw() +
#     theme(legend.title = element_blank(),legend.position = 
#               "bottom")
# 
# ggplot() +
#     geom_histogram(aes(x= x, fill = "Kpop"), alpha = 0.4,
#               data = kpop_age) +
#     geom_histogram(aes(x=recode_age, fill = "CCES Unweighted"), alpha = 0.4,
#               data = cces_xgb_dat) +
#     theme_bw() +
#     theme(legend.title = element_blank(),legend.position = 
#               "bottom")


```




# updating bb
```{r}
# load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/Working/bigB_noNAs_nopopw.Rdata")
#  load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/cat_nodnk_noNas_nopopw.Rdata")
# cat <- out_nopopw_noNAs_cat
# load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/Working/biggerB_nodnk_noNas_nopopw.Rdata")
# bigb <- out_nopopw_noNAs
# 
# load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/Working/smallB_nodnk_noNas_nopopw_man.Rdata")
# smallb <- smallb_out_nopopw_noNAs

# biasbound <- rbind(smallb %>% dplyr::select(b, bbr, bbr_conv, bbr_mf, numdims, numdims_conv, numdims_mf, mf_append_dims),
#       bigb %>% dplyr::select(b, bbr, bbr_conv, bbr_mf, numdims, numdims_conv, numdims_mf, mf_append_dims), 
#       c(b = NA, cat %>% dplyr::select(bbr, bbr_conv, bbr_mf, numdims, numdims_conv, numdims_mf, mf_append_dims))) %>% arrange(b)

#cat
# load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/allB_cat.Rdata")
# 
# load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/altB_cat.Rdata")

# load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/allB_cat_2021-02-25.Rdata")

#bigger tolerance: NO DIFFERENCE.... this is bc max iter was too small
# load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/allB_cat_parallel_2021-02-26.Rdata")

#tolerance 1e-6 and increase maxit to 500, maxnumdims 500
load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/allB_cat_par_m500_t1e-06_2021-03-04.Rdata")

biasbound <- rbind(out_cat %>% dplyr::select(b, bbr, bbr_conv, bbr_mf, bbr_constr, numdims, numdims_conv, numdims_mf, numdims_constr, mf_append_dims)) %>% arrange(b)


# #add variance of K
# load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/varK_cat.Rdata")
# load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/kernels_cat.Rdata") 
# load("/Users/Ciara/Documents/Cloud Documents/Hazlett:Hartman RA/2016 Election/kernels_cat_altB.Rdata") 
# biasbound <- merge(biasbound, varK_bind, by = "b")
# biasbound <- biasbound %>% mutate(varKx100 = 100*var_K) %>% dplyr::select(-var_K)

biasbound %>% filter(max(bbr) == bbr) %>% dplyr::select(b)
biasbound %>% filter(max(bbr_conv) == bbr_conv) %>% dplyr::select(b)
biasbound %>% filter(max(bbr_mf) == bbr_mf) %>% dplyr::select(b)
biasbound %>% filter(max(bbr_constr) == bbr_constr) %>% dplyr::select(b)
kable(biasbound,
       format = "latex",
       caption = "Unscaled Kernel: Bias Bound (Orig:Optimal) and Dims Selected", 
       booktabs = T,
       digits = 3)
```






```{r run_margins}
#RUN

nopopw_margins_wNAs <- allmargins(pop_weights = FALSE, 
                             age_buckets = FALSE, 
                             three_way = TRUE, 
                             b = 32,
                             pew_xgb_dat = pre_nopopw_3way$pew_dat,
                             cces_xgb_dat = pre_nopopw_3way$cces_dat, 
                             drop_ccesNAs = FALSE)

nopopw_margins_2way_wNAs <- allmargins(pop_weights = FALSE, 
                             age_buckets = FALSE, 
                             three_way = FALSE, 
                             b = 32,
                             pew_xgb_dat = pre_nopopw_2way$pew_dat,
                             cces_xgb_dat = pre_nopopw_2way$cces_dat,
                             drop_ccesNAs = FALSE)

nopopw_margins_noNAs <- allmargins(pop_weights = FALSE, 
                             age_buckets = FALSE, 
                             three_way = TRUE, 
                             b = 32,
                             pew_xgb_dat = pre_nopopw_3way$pew_dat,
                             cces_xgb_dat = pre_nopopw_3way$cces_dat, 
                             drop_ccesNAs = TRUE)

nopopw_margins_noNAs$kable_err

nopopw_margins_2way_noNAs <- allmargins(pop_weights = FALSE, 
                             age_buckets = FALSE, 
                             three_way = FALSE, 
                             b = 32,
                             pew_xgb_dat = pre_nopopw_2way$pew_dat,
                             cces_xgb_dat = pre_nopopw_2way$cces_dat,
                             drop_ccesNAs = TRUE)



out <- rbind(nopopw_margins_wNAs$wmabserr[-12, ] %>% summarise(mean(kpop), 
                                                  mean(kpop_conv), 
                                                  mean(kpop_mf), 
                                                  mean(rake_demos_noeduc),
                                                  mean(rake_demos_weduc), 
                                                  mean(post_stratification), 
                                                  mean(rake_retrospective)),
             nopopw_margins_noNAs$wmabserr[, ] %>% summarise(mean(kpop),
                                                  mean(kpop_conv), 
                                                  mean(kpop_mf), 
                                                  mean(rake_demos_noeduc),
                                                  mean(rake_demos_weduc), 
                                                  mean(post_stratification), 
                                                  mean(rake_retrospective)),
             nopopw_margins_2way_wNAs$wmabserr[-12, ] %>% summarise(mean(kpop), 
                                                       mean(kpop_conv),
                                                       mean(kpop_mf), 
                                                  mean(rake_demos_noeduc),
                                                  mean(rake_demos_weduc), 
                                                  mean(post_stratification), 
                                                  mean(rake_retrospective)),
             nopopw_margins_2way_noNAs$wmabserr[, ] %>% summarise(mean(kpop), 
                                                  mean(kpop_conv), 
                                                  mean(kpop_mf), 
                                                  mean(rake_demos_noeduc),
                                                  mean(rake_demos_weduc), 
                                                  mean(post_stratification), 
                                                  mean(rake_retrospective)))
out <- as.data.frame(out)
rownames(out) <- c("3way NAs",
                   "3way noNAs", 
                   "2way NAs",
                   "2way noNAs")

kable(out, 
      format = "latex",
      caption = "Average MAE Across Above Margins",
          booktabs = T, digits= 4)
```


```{r doublecheck, eval = T}

#DOUBLE CHECK SURVEY PACKAGE IS DOING WHAT I THINK IT'S DOING
nopopw_margins$margins["femaleFemale", "kpop"]
kpop_weights <- kpop_w[1:(nrow(pew_xgb_dat))]
a <- mean(kpop_weights*(pew_xgb_dat$recode_female== "Female"))*100
a
a_targ <- mean(cces_xgb_dat$recode_female == "Female")*100

#so yes direct survey mean on femal is the same as just mean of logical
svymean(~recode_female, svydesign(~1, data = cces_xgb_dat), na.rm = TRUE)


#WTF IS GOING ON WITH SVYMEAN ON MULTIPLE VARS
formula <- ~recode_female + recode_vote_2016 + 
    recode_race + recode_region + recode_educ + 
    recode_relig_6way + recode_born + recode_attndch_4way + recode_income_5way +
    recode_educ_wh_3way + 
    xgb_cces_on_cces_pO + xgb_pew_on_cces_pD + xgb_pew_on_cces_pR + 
    xgb_pew_on_cces_pO + recode_pid_3way + recode_age_bucket 
#Ok turns out this is because there are NAs in recode_vote_2016 so if we remove them we drop lots of units and that changes the overall mean of female even though it doesnt itse;f have any NAs so we get different cces margins and therefore different mae if we drop them or not
all <- data.frame(svymean(formula, svydesign(~1, data = cces_xgb_dat), na.rm = TRUE))
all[c("recode_femaleFemale", "recode_femaleMale"),]
svymean(~recode_female, svydesign(~1, data = cces_xgb_dat), na.rm = TRUE)

#w mean abs error
#have to drop the NAs to get the same thing as what's in the above function
cces_noNAs <- cces %>% filter(!is.na(recode_vote_2016))

nopopw_margins$margins["femaleFemale", "cces_margins"]
mean(cces_noNAs$recode_female == "Female")*100

abs(mean(cces_noNAs$recode_female == "Female") - mean(kpop_weights*(pew_xgb_dat$recode_female== "Female")))*100 

nopopw_margins$wmabserr[nopopw_margins$wmabserr$var =="female", "kpop"]

#so yes they are the same thank jesus



```



















```{r graveyard}

#to get outcomes (all this info is int h e comp_df objects in the output of the pew funct)

votemargins_cces <- function(survey) {
    return(
        c(
            vote_2016 = svycontrast(svymean(~recode_vote_2016, 
                                            survey, na.rm = TRUE), vote_contrast),
            xgb_cces_avg_marg = svymean(~margin_cces_on_cces, 
                                        survey, na.rm = TRUE),
            xgb_pew_avg_marg = svymean(~margin_pew_on_cces, 
                                       survey, na.rm = TRUE),
            xgb_cces_marg_at_avg = (svymean(~xgb_cces_on_cces_pD, survey) -
                                        svymean(~xgb_cces_on_cces_pR, survey))
                                    / (svymean(~xgb_cces_on_cces_pD, survey) +
                                          svymean(~xgb_cces_on_cces_pR, survey)),
            xgb_pew_marg_at_avg = (svymean(~xgb_pew_on_cces_pD, survey) -
                                       svymean(~xgb_pew_on_cces_pR, survey))
                                    /(svymean(~xgb_pew_on_cces_pD, survey)
                                      + svymean(~xgb_pew_on_cces_pR, survey)) ) 
    )
}

votemargins_pew <- function(survey) {
    return(
        c(
            vote_2016 = svycontrast(svymean(~recode_vote_2016, 
                                            survey, na.rm = TRUE), vote_contrast),
            xgb_cces_avg_marg = svymean(~margin_cces_on_pew, 
                                        survey, na.rm = TRUE),
            xgb_pew_avg_marg = svymean(~margin_pew_on_pew, 
                                       survey, na.rm = TRUE),
            xgb_cces_marg_at_avg = (svymean(~xgb_cces_on_pew_pD, survey) -
                                        svymean(~xgb_cces_on_pew_pR, survey)) 
                                    /(svymean(~xgb_cces_on_pew_pD, survey) +
                                          svymean(~xgb_cces_on_pew_pR, survey)),
            xgb_pew_marg_at_avg = (svymean(~xgb_pew_on_pew_pD, survey) - 
                                       svymean(~xgb_pew_on_pew_pR, survey))
                                    /(svymean(~xgb_pew_on_pew_pD, survey)
                                      + svymean(~xgb_pew_on_pew_pR, survey)) ) 
    )
    
}

###### difference #######
votediff_cces <- function(survey) {
    return(
        c(
         vote_2016 = svycontrast(svymean(~recode_vote_2016, 
                                            survey, na.rm = TRUE), vote_contrast),
            xgb_cces_avg_marg = svymean(~margin_cces_on_cces, 
                                        survey, na.rm = TRUE),
            xgb_pew_avg_marg = svymean(~margin_pew_on_cces, 
                                       survey, na.rm = TRUE),
            xgb_cces_marg_at_avg = (svymean(~xgb_cces_on_cces_pD, survey) -
                                        svymean(~xgb_cces_on_cces_pR, survey)),
            xgb_pew_marg_at_avg = (svymean(~xgb_pew_on_cces_pD, survey) -
                                       svymean(~xgb_pew_on_cces_pR, survey)) ) 
    )
}

votediff_pew <- function(survey) {
    return(
        c(
            vote_2016 = svycontrast(svymean(~recode_vote_2016, 
                                            survey, na.rm = TRUE), vote_contrast),
            xgb_cces_avg_marg = svymean(~margin_cces_on_pew, 
                                        survey, na.rm = TRUE),
            xgb_pew_avg_marg = svymean(~margin_pew_on_pew, 
                                       survey, na.rm = TRUE),
            xgb_cces_marg_at_avg = (svymean(~xgb_cces_on_pew_pD, survey) -
                                        svymean(~xgb_cces_on_pew_pR, survey)),
            xgb_pew_marg_at_avg = (svymean(~xgb_pew_on_pew_pD, survey) - 
                                       svymean(~xgb_pew_on_pew_pR, survey)) ) 
    )
}


### cces on pew
    votemargin_pew <- cbind(
                        pew = votemargins_pew(pew_nowt),
                        cces = votemargins_cces(cces_svy),
                        kpop = votemargins_pew(kpop), 
                        kpop_mf = votemargins_pew(kpop_mf),
                        kpop_conv = votemargins_pew(kpop_conv),
                        rake_noedu = votemargins_pew(rake_demos_noeduc),
                        rake_wedu = votemargins_pew(rake_demos_weduc), 
                        ps = votemargins_pew(post_stratification), 
                        rake_retro =  votemargins_pew(rake_retrospective))
    
    votemargin_pew <- as.data.frame(votemargin_pew*100)
    rownames(votemargin_pew) <- sapply(rownames(votemargin_pew),
                                       function(x) gsub("\\..*","", x ) ) 
    
    
     caption_o = paste0("Outcomes (Difference): ", popw_lab, ageb, "(no dnk) ",
                       "b=", b, xgb_lab)
    caption_vm = paste0("Vote Margins: ", popw_lab, ageb, " (no dnk) ", 
                        "b=", b, xgb_lab)
       
    kable_outcomes <- kable(margins_diff[c(1:9),],
          format = "latex",
          caption = caption_o,
          col.names = colnames_bottom,
          booktabs = T, digits= 3) 
    
    kable_vm <- kable(votemargin,
                      format = "latex",
                      caption = caption_vm,
                      col.names = colnames_bottom,
                      booktabs = T, digits= 2)

```














## XGB CCES RUN - 2WAY

```{r xgb_cces_2way, eval = F}
################ 2 way Outcome #############
#as before with the actual outcome we will drop others in the model then predict for all data to get the predicted probability of these individuals who voted other for D or R
#360 NAs were dropped from the kbal runs so should maybe be dropped here?
cces_DR = cces %>% filter(recode_vote_2016 != "Other" & !is.na(recode_vote_2016))

outcome = cces_DR$recode_vote_2016
#we've already dropped na's (this is used in the application setting)
#
#this makes Rep = 1, Dem = 0
out_int <- as.integer(as.factor(outcome))-1

#why does this have NAs in it at all though... didn't we fix that?
#or was that only in pew
####### Set up Model
cces_matrix_sparse_DR <- cces_DR %>%
    dplyr::select(recode_age,
           recode_female,
           recode_race,
           recode_region,
           recode_pid_3way,
           recode_educ,
           recode_income,
           #recode_relig has 38 Nas so need to use buckets
           recode_relig_6way,
           recode_born,
           #recode_attndch has some nas need to use buckegs
           recode_attndch_4way,
           recode_race_educ_reg) %>%
    sparse.model.matrix(as.formula("~."), .)
#WHAT THE ACTUAL FUCK IS sparse model matrix doing; it's dropping the NAs
nrow(cces_matrix_sparse_DR)
nrow(cces_DR)

cces_matrix_sparse_DR = cces_matrix_sparse_DR[,-1]

#using 80% to train
percent <- sample.int(nrow(cces_DR),
                      (nrow(cces_DR)/10)*8)

dat_xgb_train <- xgb.DMatrix(data = cces_matrix_sparse_DR[percent,], 
                             label = out_int[percent])
dat_xgb_outofsamp <- xgb.DMatrix(data = cces_matrix_sparse_DR[-percent,], 
                                 label = out_int[-percent])
#params (not cv'ed)
params = list(
    booster="gbtree",
    eta=0.3,
    max_depth=10,
    min_child_weight = 4,
    gamma=3,
    subsample= 0.7,
    colsample_bytree=1,
    objective="multi:softprob",
    num_class=2,
    eval_metric = "merror"
)

xgbcv <- xgb.cv( params = params,
                 data = dat_xgb_train,
                 nrounds = 500,
                 nfold = 5,
                 early_stopping_rounds = 50,
                 showsd = T,
                 stratified = T,
                 print_every_n = 10,
                 early_stop_round = 20,
                 maximize = F)
xgbcv$best_iteration

#run
xgb_cces_DR =xgb.train(params=params,
                    data=dat_xgb_train,
                    nrounds= xgbcv$best_iteration,
                    watchlist = list(validation = dat_xgb_outofsamp),
                    nthreads=2,
                    print_every_n = 10)

xgb_outcome = predict(xgb_cces_DR, dat_xgb_train, reshape=T)
xgb_outofsamp = predict(xgb_cces_DR, dat_xgb_outofsamp, reshape =T)

##### peak at model performance: #####
#1. max probability what percent correct?
#convert to max prob outcome:
xgb_plurality_train <- apply(xgb_outcome,1, which.max)
xgb_plurality_test <- apply(xgb_outofsamp,1, which.max)
#what percent correct in and out of sample
sum(xgb_plurality_train -1 == out_int[percent])/length(out_int[percent])
sum(xgb_plurality_test - 1 == out_int[-percent])/length(out_int[-percent])

#2. get confusion matrix: doing things in terms of characters to keep track 
#now rep = 1, dem = 0
xgb_train_char = case_when(xgb_plurality_train-1  == 1 ~ "Republican",
                           xgb_plurality_train-1  == 0 ~ "Democrat")

xgb_test_char = case_when(xgb_plurality_test-1  == 0 ~ "Democrat",
                          xgb_plurality_test-1  == 1 ~ "Republican")
#check same as above
sum(xgb_train_char == outcome[percent])/length(percent)
sum(xgb_test_char == outcome[-percent])/length(outcome[-percent])

conf_train = confusionMatrix(as.factor(xgb_train_char), as.factor(cces_DR$recode_vote_2016)[percent])
conf_test = confusionMatrix(as.factor(xgb_test_char), as.factor(cces_DR$recode_vote_2016)[-percent])

#confusion matrices
#because dividing rowwise is annoying:
cat("Confusion Matrix: CCES 2way on CCES Training")
t(t(conf_train$table)/colSums(conf_train$table))
cat("Confusion Matrix: CCES 2way on CCES Training")
t(t(conf_test$table)/colSums(conf_test$table))

```
```{r 2way, eval = F}
pre_nopopw_2way <- pew_out(PRE = TRUE,    
                           age_buckets = FALSE, 
                              popw = FALSE,
                              three_way = FALSE,
                              noDNK_weights = TRUE, 
                           drop_ccesNAs = TRUE,
                              xgb_cces_mod = xgb_cces_DR)

pre_nopopw_2way$plot_diff
#margin is bolding 16, diff is bolding 16, pR and ufcking pD WHY

#ggsave("./app_xgb_diff_2way_wCCES_NAs.pdf", width = 14, height = 8)
```