---
output: pdf_document
header-includes:
  - \usepackage{graphicx}
  - \usepackage{booktabs}
  - \usepackage{makecell}
---


### Note that all ratios are original:optimal


```{r messages = F, echo=F, warning=FALSE}
suppressMessages(library(kableExtra))
suppressMessages(library(tidyverse))
suppressMessages(library(survey))
#suppressMessages(library(dplyr))
load("bb_dat_wEst.Rdata")
```


# With Party Id

### KPOP (no meanfirst)
```{r, echo = F, results= "asis"}

kable(bb_comp[1:6],
      format = "latex",
      caption = "KPOP + MF=FALSE + W PID: Comparison of Bias bound and L1 distance by choice of b",
      col.names = c("Bias Bound Ratio", "L1 Ratio",
                    "Bias Bound Orig", "Bias Bound Opt",
                    "L1 Orig", "L1 Opt"),
      booktabs = T, digits= 4) %>%
    kable_styling(position = "center", latex_options = "hold_position")


kable(bb_comp[c(1,2,7,8)],
      format = "latex",
      caption = "KPOP + MF=FALSE + W PID: Choice of b and Estimated Outcome",
      col.names = c("Bias Bound Ratio", "L1 Ratio","Est Vote Margin", "Diff from Target"),
      booktabs = T, digits= 4) %>%
    kable_styling(position = "center", latex_options = "hold_position")




```

### KPOP with meanfirst

```{r, echo  = F, results = "asis"}


kable(bb_comp_mf[1:6],
      format = "latex",
      caption = "KPOP + MF=TRUE + W PID: Comparison of Bias bound and L1 distance by choice of b",
      col.names = c("Bias Bound Ratio", "L1 Ratio",
                    "Bias Bound Orig", "Bias Bound Opt",
                    "L1 Orig", "L1 Opt"),
      booktabs = T, digits= 4) %>%
    kable_styling(position = "center", latex_options = "hold_position")


kable(bb_comp_mf[c(1,2,7,8)],
      format = "latex",
      caption = "KPOP + MF=TRUE + W PID: Choice of b and Estimated Outcome",
      col.names = c("Bias Bound Ratio", "L1 Ratio","Est Vote Margin", "Diff from Target"),
      booktabs = T, digits= 4) %>%
    kable_styling(position = "center", latex_options = "hold_position")

```


# Without Party Id


### KPOP (no meanfirst)

```{r, echo  = F, results = "asis"}


kable(bb_comp_nopid[1:6],
      format = "latex",
      caption = "KPOP + MF=FALSE + NO PID: Comparison of Bias bound and L1 distance by choice of b",
      col.names = c("Bias Bound Ratio", "L1 Ratio",
                    "Bias Bound Orig", "Bias Bound Opt",
                    "L1 Orig", "L1 Opt"),
      booktabs = T, digits= 4) %>%
    kable_styling(position = "center", latex_options = "hold_position")


kable(bb_comp_nopid[c(1,2,7,8)],
      format = "latex",
      caption = "KPOP + MF=FALSE + NO PID: Choice of b and Estimated Outcome",
      col.names = c("Bias Bound Ratio", "L1 Ratio","Est Vote Margin", "Diff from Target"),
      booktabs = T, digits= 4) %>%
    kable_styling(position = "center", latex_options = "hold_position")

```


### KPOP with meanfirst


```{r, echo  = F, results = "asis"}

kable(bb_comp_mf_nopid[1:6],
      format = "latex",
      caption = "KPOP + MF=TRUE + NO PID: Comparison of Bias bound and L1 distance by choice of b",
      col.names = c("Bias Bound Ratio", "L1 Ratio",
                    "Bias Bound Orig", "Bias Bound Opt",
                    "L1 Orig", "L1 Opt"),
      booktabs = T, digits= 4) %>%
    kable_styling(position = "center", latex_options = "hold_position")


kable(bb_comp_mf_nopid[c(1,2,7,8)],
      format = "latex",
      caption = "KPOP + MF=TRUE + NO PID: Choice of b and Estimated Outcome",
      col.names = c("Bias Bound Ratio", "L1 Ratio","Est Vote Margin", "Diff from Target"),
      booktabs = T, digits= 4) %>%
    kable_styling(position = "center", latex_options = "hold_position")

#save(bb_comp, bb_comp_mf, bb_comp_nopid, bb_comp_mf_nopid,file = "bb_dat_wEst.Rdata")

```




```{r, echo  = F, eval = F}
######### Used to update bb_comps but now resaved in bb_dat_wEst
#resaved bb_dat to update these
load("2016_Ex/bb_dat.Rdata")
load("2016_Ex/surveys_wPID.Rdata")
load("2016_Ex/surveys_NoPID.Rdata")

#data
pres <- readRDS("data/election.rds")
natl_margin <- pres %>%
    summarise(margin = (sum(demtotal) - sum(reptotal)) /
                  (sum(demtotal) + sum(reptotal))) %>%
    as.numeric()
cces <- readRDS("./data/cces.rds")
### Drop invalid cases
cces <- cces %>%
    filter((CC16_401 == "I definitely voted in the General Election.") &
               !is.na(commonweight_vv_post))

### Make survey design
cces_awt <- svydesign(ids = ~1, weights = ~commonweight_vv_post, data = cces)

### unweighted CCES
cces_nowt <- svydesign(ids = ~1, data = cces)
vote_contrast <- quote((recode_vote_2016Democrat - recode_vote_2016Republican) /
                           (recode_vote_2016Democrat + recode_vote_2016Republican))
#adding estimate for reweighted clinton outcome
comp_df <- data.frame(
    CCES = svycontrast(svymean(~recode_vote_2016, cces_awt, na.rm = TRUE),
                       vote_contrast),
    #b = 2
    ## no meanfirst
    Pew_kbal_b2x_nopid = svycontrast(svymean(~recode_vote_2016,
                                              kbal_wt_b2x_nopid, na.rm = TRUE),
                                      vote_contrast),
    Pew_kbal_b2x = svycontrast(svymean(~recode_vote_2016, kbal_wt_b2x,
                                        na.rm = TRUE), vote_contrast),
    ## meanfirst
    Pew_kbal_mf_b2x_nopid = svycontrast(svymean(~recode_vote_2016,
                                                kbal_wt_mf_nopid_b2x, na.rm = TRUE),
                                     vote_contrast),
    Pew_kbal_mf_b2x = svycontrast(svymean(~recode_vote_2016, kbal_mf_wt_b2x,
                                       na.rm = TRUE), vote_contrast),
    #b = 1
    ## no meanfirst
    Pew_kbal_b1x_nopid = svycontrast(svymean(~recode_vote_2016,
                                             kbal_wt_b1x_nopid, na.rm = TRUE),
                                     vote_contrast),
    Pew_kbal_b1x = svycontrast(svymean(~recode_vote_2016, kbal_wt_b1x,
                                       na.rm = TRUE), vote_contrast),
    ## meanfirst 
    Pew_kbal_mf_b1x_nopid = svycontrast(svymean(~recode_vote_2016,
                                                kbal_wt_mf_nopid_b1x, na.rm = TRUE),
                                        vote_contrast),
    Pew_kbal_mf_b1x = svycontrast(svymean(~recode_vote_2016, kbal_mf_wt_b1x,
                                          na.rm = TRUE), vote_contrast),
    
    #b = 0.5
    ##no meanfirst
    Pew_kbal_b.5x_nopid = svycontrast(svymean(~recode_vote_2016,
                                              kbal_wt_b.5x_nopid, na.rm = TRUE),
                                      vote_contrast),
    Pew_kbal_b.5x = svycontrast(svymean(~recode_vote_2016, kbal_wt_b.5x,
                                        na.rm = TRUE), vote_contrast),
    ## meanfirst
    Pew_kbal_mf_b.5x_nopid = svycontrast(svymean(~recode_vote_2016,
                                                kbal_wt_mf_nopid_b.5x, na.rm = TRUE),
                                        vote_contrast),
    Pew_kbal_mf_b.5x = svycontrast(svymean(~recode_vote_2016, kbal_mf_wt_b.5x,
                                          na.rm = TRUE), vote_contrast),
    
    #b = 0.25
    ## no meanfirst
    Pew_kbal_b.25x_nopid = svycontrast(svymean(~recode_vote_2016,
                                               kbal_wt_b.25x_nopid, na.rm = TRUE),
                                       vote_contrast),
    Pew_kbal_b.25x = svycontrast(svymean(~recode_vote_2016, kbal_wt_b.25x, 
                                         na.rm = TRUE), vote_contrast),
    ## meanfirst 
    Pew_kbal_mf_b.25x_nopid = svycontrast(svymean(~recode_vote_2016,
                                                kbal_wt_mf_nopid_b.25x, na.rm = TRUE),
                                        vote_contrast),
    Pew_kbal_mf_b.25x = svycontrast(svymean(~recode_vote_2016, kbal_mf_wt_b.25x,
                                          na.rm = TRUE), vote_contrast),
    
    #b = 0.125
    ## nomeanfirst
    Pew_kbal_b.125x_nopid = svycontrast(svymean(~recode_vote_2016,
                                                kbal_wt_b.125x_nopid, na.rm = TRUE),
                                        vote_contrast),
    Pew_kbal_b.125x = svycontrast(svymean(~recode_vote_2016, kbal_wt_b.125x, 
                                          na.rm = TRUE), vote_contrast),
    ## meanfirst
    Pew_kbal_mf_b.125x_nopid = svycontrast(svymean(~recode_vote_2016,
                                                kbal_wt_mf_nopid_b.125x, na.rm = TRUE),
                                        vote_contrast),
    Pew_kbal_mf_b.125x = svycontrast(svymean(~recode_vote_2016, kbal_mf_wt_b.125x,
                                          na.rm = TRUE), vote_contrast),

    #b =0.0625 (only did for nopid + mf = F)
    Pew_kbal_b.0625x_nopid = svycontrast(svymean(~recode_vote_2016,
                                                kbal_wt_b.0625x_nopid, na.rm = TRUE),
                                        vote_contrast)
   
) %>%
    pivot_longer(cols = everything(),
                 names_to = c("source", ".value"), 
                 names_pattern = "(.*)\\.(.*)") %>%
    rename(est = nlcon) %>%
    mutate(err = est - natl_margin, 
           source = str_replace(source, "_", " ")) %>%
    mutate(err_target = est - est[source == "CCES"])


#merging to bb_comps
bb_comp <- bb_comp %>% mutate(Est_VoteMargin = comp_df$est[c(3,7,11,15,19)],
                              Diff_from_Target = comp_df$err_target[c(3,7,11,15,19)])
rownames(bb_comp) <- c("b=2x",
                       "b=1x",
                       "b=.5x",
                       "b=.25x",
                       "b=.125x")

#merging to bb_comps
bb_comp_mf <- bb_comp_mf %>% mutate(Est_VoteMargin = comp_df$est[c(5,9,13,17,21)],
                              Diff_from_Target = comp_df$err_target[c(5,9,13,17,21)])
rownames(bb_comp_mf) <- c("b=2x",
                       "b=1x",
                       "b=.5x",
                       "b=.25x",
                       "b=.125x")


bb_comp_nopid <- bb_comp_nopid %>% mutate(
    Est_VoteMargin = comp_df$est[c(2,6,10,14,18,22)],
    Diff_from_Target = comp_df$err_target[c(2,6,10,14,18,22)])
rownames(bb_comp_nopid) <- c("b=2x",
                       "b=1x",
                       "b=.5x",
                       "b=.25x",
                       "b=.125x",
                       "b=0.0625")

bb_comp_mf_nopid <- bb_comp_mf_nopid %>% mutate(
    Est_VoteMargin = comp_df$est[c(4,8,12,16,20)],
    Diff_from_Target = comp_df$err_target[c(4,8,12,16,20)])
rownames(bb_comp_mf_nopid) <- c("b=2x",
                                "b=1x",
                                "b=.5x",
                                "b=.25x",
                                "b=.125x")

save(bb_comp_nopid, bb_comp_mf_nopid, bb_comp, bb_comp_mf, file = "bb_dat_wEst.Rdata")

```



