---
title: "2016 Application - March 2023"
author: "Ciara Sterbenz"
date: '2023-04-03'
output:
  pdf_document: default
editor_options: 
  chunk_output_type: console
---


```{r setup, include = F, echo = F}
#rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
set.seed(9345876)

### Packages
library(tidyverse)
library(survey)
library(kbal)
library(knitr)
library(kableExtra)
#loading the updated data:
path_data= "/Users/Ciara_1/Dropbox/kpop/2023/application/data/"
path_weights = "/Users/Ciara_1/Dropbox/kpop/2023/application/weights/"
#old weights
weights_file = "bmaxvar_cat_nodiag_lasso061021_wTRUE_m500_t1e-06_2021-07-07.Rdata"
#no popw (note that estimates are w popw tho oops, weights are without however)
#weights_file = "app_update_raw2023-04-06_noPOPW.Rdata"
weights_file = "app_update_raw2023-04-06.Rdata"
POPW = TRUE
TEST = FALSE
```


```{r load_dat, echo = F}
if(POPW) {
    cces <- readRDS(paste0(path_data, "cces_lasso_061021.rds"))
    pew <- readRDS(paste0(path_data, "pew_lasso_061021.rds"))
} else {
    cces <- readRDS(paste0(path_data, "cces_xgb.rds"))
    pew <- readRDS(paste0(path_data, "pew_xgb.rds"))
    #the var name here is wrong, this should be updated in the above files rather than here but for now:
    #these should be included and fixed in lasso_061021
    
    cat("PLEASE CHECK IF RACE_REG_REG_WH_EDUC INTERACTION IS STILL NEEEDED")
    pew <- pew %>% rename(recode_race_reg_wh_educ = recode_race_educ_reg) %>% 
        mutate(recode_race_educ_reg = as.factor(paste(recode_race, recode_region, 
                                                      recode_educ_3way, sep = ", ")))
    
    cces <- cces %>% rename(recode_race_reg_wh_educ = recode_race_educ_reg) %>% 
        mutate(recode_race_educ_reg = as.factor(paste(recode_race, recode_region, 
                                                      recode_educ_3way , sep = ", ")))
    if(TEST) {
        cces = cces[out$test_sample$rs_cces,]
        pew = pew[out$test_sample$rs_pew,]
    }
        

}
```


```{r SE_funct, echo = F}
## Variance functions
var_fixed <- function(Y, weights, pop_size) {
    ## note: needs weights that sum to population total
    if(round(sum(weights)) != pop_size) { weights = weights*pop_size/sum(weights)}
    return(Hmisc::wtd.var(Y, weights))
}

## kott (14) (under poisson)
var_quasi <- function(weights, residuals, pop_size) {
    #moving from kott 14 w sum w =N to weights that sum to 1 + var of total to var of mean:
    #sum^n (w_i^2 - 1/N_pop w_i)e_i^2 
    return(sum((weights^2 - (weights / pop_size))*residuals^2))
}

## kott (15) linearization
var_linear <- function(weights, residuals, sample_size) {
    #moving from kott 14 w sum w =N to weights that sum to 1 + var of total to var of mean:
    # n/(n-1) sum^n (w_i*e_i)^2 - (1/n-1) [sum^n] *using this for now
    # approx = sum^n (w_i*e_i)^2 - (1/n) [sum^n]
    n = sample_size
    return((n/(n-1))*sum((weights * residuals)^2) - 1/(n-1) * sum(weights * residuals)^2)
}

## chad
var_chad <- function(weights, residuals) {
    return(sum(weights^2 * residuals^2))
}

## calculate all variances
calc_SEs <- function(Y, residuals, pop_size, weights, sample_size) {
    if(round(sum(weights)) != 1 ) {
        weights = weights/sum(weights)
    }
    return(data.frame(SE_fixed = sqrt(var_fixed(Y, weights, pop_size) / length(Y)),
                      SE_quasi = sqrt(var_quasi(weights, residuals, pop_size)),
                      SE_linear = sqrt(var_linear(weights, residuals, sample_size)),
                      SE_chad = sqrt(var_chad(weights, residuals))))
}

```


```{r setup_targets, echo = F}
formula_rake_demos_noeduc <- ~recode_age_bucket + recode_female + recode_race + 
    recode_region + recode_pid_3way

formula_rake_demos_weduc <- ~recode_age_bucket + recode_female + 
    recode_race + recode_region + recode_educ + recode_pid_3way


#test
# formula_test <- ~recode_age_bucket:recode_pid_3way + 
#     recode_female:recode_pid_3way+ 
#     recode_race:recode_pid_3way+ 
#     recode_region:recode_pid_3way + 
#     recode_edu_wh_6way:recode_pid_3way


formula_rake_all_vars <- ~recode_age_bucket + recode_female + 
    recode_race + recode_region + recode_pid_3way + recode_educ +
    recode_income_5way + recode_relig_6way + recode_born + recode_attndch_4way

#wait why is this so reduced???
#changed recode_educ_wh_3way to more retrospectively informed: recode_educ_wh_3way
formula_ps <- ~recode_age_3way + recode_female + recode_race +
    recode_region + recode_race_reg_wh_educ + recode_pid_3way

#4/28 this DID NOT HAVE THE RIGHT RETROSPECTIVE INTERACTION
formula_ps_reduc <- ~recode_age_3way + 
    recode_female + 
    recode_race + 
    recode_region + 
    recode_pid_3way  +
    recode_income_3way + 
    recode_born +
    #recode_educ
    #recode_educ_3way
    recode_educ_wh_3way 
    #recode_race_reg_wh_educ 
#let's coarsen income and religion and attend church:

#same as above but without coarsening of educ, income, or age
formula_ps_all <- ~recode_age_bucket +
    recode_female +
    recode_race +
    recode_region +
    recode_pid_3way +
    recode_income_5way +
    recode_born +
    recode_educ

#fully all available vars: (same as rake all)
#this has coarsening of relig (12) and attndcgh (9) and income (9), and ofc age already which no specification uses 
# formula_ps_all <- ~recode_age_bucket +
#     recode_female +
#     recode_race +
#     recode_region +
#     recode_pid_3way +
#     recode_income_5way +
#     recode_born +
#     recode_educ + 
#     recode_relig_6way + 
#     recode_attndch_4way
    
# formula_ps_all <- ~recode_age_3way + recode_female +
#     recode_race + recode_region + recode_pid_3way + recode_educ_3way +
#     recode_income_3way + recode_relig_6way + recode_born + recode_attndch_bin

formula_retrospective <- ~recode_age_bucket:recode_pid_3way + 
    recode_female:recode_pid_3way+ recode_race_reg_wh_educ:recode_pid_3way

### set up some functions for convenient estimates
vote_contrast <- quote((recode_vote_2016Democrat - recode_vote_2016Republican) /
                               (recode_vote_2016Democrat + recode_vote_2016Republican))

vote_diff <- quote((recode_vote_2016Democrat - recode_vote_2016Republican) /(recode_vote_2016Democrat + recode_vote_2016Republican + recode_vote_2016Other)) 


#### Build Strata For PS
cces <- bind_cols(cces, cces %>% 
                      unite("strata", all.vars(formula_ps), remove = FALSE) %>%
                         unite("strata_reduc", all.vars(formula_ps_reduc), 
                               remove = FALSE) %>%
                         unite("strata_all", all.vars(formula_ps_all)) %>%
                      dplyr::select(strata, strata_reduc, strata_all))

cces = cces %>% mutate(recode_edu_wh_6way = case_when(recode_race == "White" ~ recode_educ,
                                                      TRUE ~ "No split"))

pew <- bind_cols(pew, pew %>% 
                     unite("strata", all.vars(formula_ps), remove = FALSE) %>%
                     unite("strata_reduc", all.vars(formula_ps_reduc), 
                           remove = FALSE) %>%
                     unite("strata_all", all.vars(formula_ps_all)) %>%
                     dplyr::select(strata, strata_reduc, strata_all))

pew = pew %>% mutate(recode_edu_wh_6way = case_when(recode_race == "White" ~ recode_educ,
                                                      TRUE ~ "No split"))
#make targets
create_targets <- function (target_design, target_formula) {
    target_mf <- model.frame(target_formula, model.frame(target_design))
    target_mm <- model.matrix(target_formula, target_mf)
    wts <- weights(target_design)
    colSums(target_mm * wts) / sum(wts)
}

```



# Weights Diagnostics

```{r weights, echo = F}
load(paste0(path_weights,weights_file))
# load("/Users/Ciara_1/Dropbox/kpop/Updated/application/weights/bmaxvar_cat_nodiag_lasso061021_wTRUE_m500_t1e-06_2021-07-07.Rdata")

if(POPW) {
    cces_awt <- svydesign(~1, weights = ~commonweight_vv_post, data = cces)
} else {
    #NOT TEMPRORARY ABUSE OF NAMING HERE BC IM LAZY
    cces_awt <- svydesign(~1, weights = ~1, data = cces)
}

pew_nowt <- suppressWarnings(svydesign(~1, data = pew))

#post stratification
missing_strata_reduc <- unique(cces$strata_reduc)[!(unique(cces$strata_reduc) %in%
                                            unique(pew$strata_reduc))]
problem_reduc <- unique(pew$strata_reduc)[!(unique(pew$strata_reduc)
                                                         %in%
                                                   unique(cces$strata_reduc))]

targets_rake_demos_noeduc <- create_targets(cces_awt,
                                                    formula_rake_demos_noeduc)
targets_rake_demos_weduc <- create_targets(cces_awt, formula_rake_demos_weduc)
targets_rake_all_vars <- create_targets(cces_awt, 
                                               formula_rake_all_vars)
targets_retrospective <- create_targets(cces_awt, formula_retrospective)
targets_ps_reduc <- svytable(formula = ~strata_reduc,
                       design = subset(cces_awt, !(strata_reduc %in%
                                                        missing_strata_reduc)))

rake_demos_noeduc <- calibrate(design = pew_nowt,
                           formula = formula_rake_demos_noeduc,
                           population = targets_rake_demos_noeduc,
                           calfun = "raking")

rake_demos_weduc <- calibrate(design = pew_nowt,
                          formula = formula_rake_demos_weduc,
                          population = targets_rake_demos_weduc,
                          calfun = "raking")

rake_all_vars <- calibrate(design = pew_nowt,
                          formula = formula_rake_all_vars,
                          population = targets_rake_all_vars,
                          calfun = "raking")

rake_retrospective <- calibrate(design = pew_nowt,
                            formula = formula_retrospective,
                            population = targets_retrospective,
                            calfun = "raking",
                            force = TRUE)

#reduced
pew_ps_reduc <- suppressWarnings(svydesign(ids = ~1, data = pew %>% 
                              filter(!(strata_reduc %in% problem_reduc))))
post_strat_reduc <- postStratify(design = pew_ps_reduc,
                                strata = ~strata_reduc,
                                population = targets_ps_reduc)

#what is going on here: why do they sum to 31k because of the dropped strata i guess?
#yes: we dont have weights or 27 units because their strata dn exist in the population
# sum(weights(post_strat_reduc))
# length(weights(post_strat_reduc))
n_samp = nrow(pew)
# sum(is.na(weights(post_strat_reduc)[1:n_samp]))
# #why are there NAs....not good -> these are the "problem units" in pew not cces
# #dropped above when we filter by the following
# sum(pew$strata_reduc %in% problem_reduc)

weights_bmaxvar <- data.frame(kpop_w = out$weights$kpop_w,
                              kpop_demos_w = out$weights$kpop_demos_w,
                              kpop_demos_edu_w = out$weights$kpop_demos_wedu_w,
                              kpop_all_w = out$weights$kpop_all_w,
                              rake_demos = weights(rake_demos_noeduc)[1:n_samp]/mean( weights(rake_demos_noeduc)[1:n_samp]),
                              rake_demos_wedu = weights(rake_demos_weduc)[1:n_samp]/mean(weights(rake_demos_weduc)[1:n_samp]),
                              rake_all = weights(rake_all_vars)[1:n_samp]/mean(weights(rake_demos_weduc)[1:n_samp]),
                              ps_reduced = (weights(post_strat_reduc)*n_samp/sum(weights(post_strat_reduc)))[1:n_samp] )

##### Effective sample size: Kish's eff
#n_eff = n/ (mean(w^2) / mean(w)^2) = (sum w)^2 / sum(w^2)
n_eff <- apply(weights_bmaxvar, 2, function(x) {
    #to drop the ps weights
    x <- na.omit(x)
    sum(x)^2 / sum(x^2)
})
cat("Effective Sample Size \n")
n_eff



####### How many units to get 90% of the sum of the weights from biggest to smallest
#have to do ps manually because of the NAs in ps
sorted <- apply(weights_bmaxvar[,-8], 2, function(x) sort(x, decreasing =T))
#manually go back and add ps with NAs at the end so we get the right ordering
sorted <- cbind(sorted, c(sort(na.omit(weights_bmaxvar[,8]), decreasing = T),
                          rep(NA, sum(is.na(weights_bmaxvar$ps_reduced))))   )

sum_90perc <- matrix(NA, ncol(sorted), nrow =1 )
#old school nested loop, why not
for(j in 1:ncol(sorted)) {
    for(i in 1:nrow(sorted)) {
        if( sum(sorted[c(1:i), j]) >= .9*n_samp) {
            stop_index = i
            break
        }
    }
    sum_90perc[1,j] <- i  
}
colnames(sum_90perc) <- c("Kpop", "Kpop Demos", "Kpop Demos+Edu", "Kpop All", "Rake Demos",
                          "Rake Demos+Edu", "Rake All", "PS")
cat("How many units must we sum the weights of from biggest to smallest to get 90%\nof the total sum of the weights?")
sum_90perc


###### Output Results
#Put all this information together
numerical_dist_w <- data.frame(Variance = apply(weights_bmaxvar, 2, var, na.rm =T), 
                               Max = apply(weights_bmaxvar, 2, max, na.rm =T),
                               Min = apply(weights_bmaxvar, 2, min, na.rm =T),
                               IQR = apply(weights_bmaxvar, 2, IQR, na.rm =T),
                               Effective_SS = n_eff,
                               sum_90perc = as.numeric(sum_90perc))
rownames(numerical_dist_w) <- c("kpop",
                    "kpop+MF (Demos)",
                    "kpop+MF (D+Edu)",
                   "kpop+MF (All)",
                   "Mean Calib. (Demos)",
                   "Mean Calib. (D+Edu)",
                   "Mean Calib. (All)",
                   "Post-Strat (Reduced)")

kable(numerical_dist_w, format = "latex", booktabs = TRUE, digits =4,
      col.names = c("Variance", "Max", "Min", "IQR", "Effective SS",
                    "No. Units to 90% Sum of Total"),
      caption = "Numerical Summary of Distribution of Survey Weights"
      )


### full faceted ggplot
#ugly data wrangling for ggpolot
weights_gg <- c(weights_bmaxvar[,1], 
                    weights_bmaxvar[,2], 
                    weights_bmaxvar[,3], 
                    weights_bmaxvar[,4], 
                    weights_bmaxvar[,5], 
                    weights_bmaxvar[,6], 
                    weights_bmaxvar[,7], 
                    weights_bmaxvar[,8])
weights_gg <- data.frame(weight = weights_gg,
                         Method = c(rep("kpop", n_samp),
                                    rep("kpop+MF (Demos)", n_samp),
                                    rep("kpop+MF (D+Edu)", n_samp),
                                    rep("kpop+MF (All)", n_samp),
                                    rep("Mean Calibration (Demos)", n_samp),
                                    rep("Mean Calibration (D+Edu)", n_samp),
                                    rep("Mean Calibration (All)", n_samp),
                                    rep("Post-Stratification (Reduced)", n_samp)),
                         binary_method = c(rep("kpop", 4*n_samp),
                                           rep("Mean Calibration", 3*n_samp),
                                           rep("Post-Stratification", n_samp)))
 
                         
weights_gg <- weights_gg %>% mutate(top_90 = c(rep(c(sorted[sum_90perc[1],1],
                                                   sorted[sum_90perc[2],2],
                                                   sorted[sum_90perc[3],3],
                                                   sorted[sum_90perc[4],4],
                                                   sorted[sum_90perc[5],5],
                                                   sorted[sum_90perc[6],6],
                                                   sorted[sum_90perc[7],7],
                                                   sorted[sum_90perc[8],8]), each = n_samp)))


dist_w <- ggplot(weights_gg) + 
    geom_density(aes(x = weight, color = Method)) + 
    geom_vline(aes(xintercept = top_90, color = Method)) +
    facet_grid(rows = vars(binary_method),  scales = "free_x", space = "free_x") +
    scale_color_brewer(palette="Paired") +
    #ylim(0,.1) + 
    xlim(0,7) + 
    theme_bw()
dist_w
#ggsave(dist_w, file = "/Users/Ciara_1/Dropbox/kpop/2023/application/plots/dist_w_full.pdf", height = 6, width = 10)
#ggsave(dist_w, file = "/Users/Ciara_1/Dropbox/kpop/2023/application/plots/dist_w_close.pdf", height = 6, width = 10)


```


# Results: Main Plots + Margins

```{r res_main_funct, echo = F}
main_res_plot <- function(target = "modeled vote choice",
                          weights_file,
                          specify_nonkpop = c("cces orig", "cces mod", 
                                              "unweighted",
                                              #"pew unweighted",
                                              "rake demos_noeduc", "rake demos_wedu", "rake all_vars",
                                             "post stratification", 
                                             "post strat_reduc",
                                             #"post strat_all",
                                             "rake retrospective"),
                          specify_kpop = c("kpop", 
                                           #"kpop conv", "kpop_amf"
                                           "kpop demos_mf", "kpop demos_wedu_mf", "kpop all_mf"), 
                          margins_formula = NULL,
                          eval_margins = TRUE,
                          margins_pop_weighted_avg = TRUE,
                          margins_var_order = NULL) {
    if(target == "true vote choice") {
        target = "CCES Orig"
    } else if(target == "modeled vote choice") {
        target = "CCES Modeled"
    }
    
    pew_nowt <- suppressWarnings(svydesign(ids = ~1, data = pew))
    pew_awt <- suppressWarnings(svydesign(ids = ~1, weights = ~weight, data = pew))
    
    missing_strata <- unique(cces$strata)[!(unique(cces$strata) %in%
                                                        unique(pew$strata))]
    missing_strata_reduc <- unique(cces$strata_reduc)[!(unique(cces$strata_reduc) %in%
                                                unique(pew$strata_reduc))]
  
    missing_strata_all <- unique(cces$strata_all)[!(unique(cces$strata_all) %in%
                                                unique(pew$strata_all))]
    
    problem <- unique(pew$strata)[!(unique(pew$strata) %in%
                                                   unique(cces$strata))]
    problem_reduc <- unique(pew$strata_reduc)[!(unique(pew$strata_reduc)
                                                         %in%
                                                   unique(cces$strata_reduc))]
    
    problem_all <- unique(pew$strata_all)[!(unique(pew$strata_all) %in%
                                                   unique(cces$strata_all))]
    
    kbal_data_sampled <- c(rep(1, nrow(pew)),
                           rep(0, nrow(cces)))


    load(paste0(path_weights,weights_file))
    cat(paste0("loading weights w: maxit=", maxit," tolerance=", tolerance," b=", 
               round(out$est$b_out,3)," popweights=", POPW,"\n from file ",
               weights_file,"\n"))
    b = out$est$b_out
    pop_weights = POPW
    kpop_w <- out$weights$kpop_w
    kpop_conv_w <- out$weights$kpop_w_conv
    kpop_mf_w <- out$weights$kpop_mf_w
    kpop_demos_w <- out$weights$kpop_demos_w
    kpop_demos_wedu_w <- out$weights$kpop_demos_wedu_w
    kpop_all_w <- out$weights$kpop_all_w

    b_lab = paste0("b=", round(b, 2))
    plot_b_lab = c("b=argmax V(K)")
    
    if(pop_weights) {
        cces_svy <- svydesign(ids = ~1, weights = ~commonweight_vv_post,
                          data = cces)
    } else {
        cces_svy <- suppressWarnings(svydesign(ids = ~1,
                          data = cces))
    }
    
     targets_rake_demos_noeduc <- create_targets(cces_svy,
                                                    formula_rake_demos_noeduc)
     targets_rake_demos_weduc <- create_targets(cces_svy, formula_rake_demos_weduc)
     targets_rake_all_vars <- create_targets(cces_svy, 
                                                       formula_rake_all_vars)
     targets_retrospective <- create_targets(cces_svy, formula_retrospective)
     targets_ps <- svytable(formula = ~strata,
                               design = subset(cces_svy, !(strata %in%
                                                                missing_strata)))
     targets_ps_reduc <- svytable(formula = ~strata_reduc,
                               design = subset(cces_svy, !(strata_reduc %in%
                                                                missing_strata_reduc)))
     targets_ps_all <- svytable(formula = ~strata_all,
                               design = subset(cces_svy, !(strata_all %in%
                                                                missing_strata_all)))
     
     rake_demos_noeduc <- calibrate(design = pew_nowt,
                                   formula = formula_rake_demos_noeduc,
                                   population = targets_rake_demos_noeduc,
                                   calfun = "raking")
     #doing this means svy doesnt know where the weights come from cn do linearization SEs, 
     #instead uses much larger HT SEs
     # rake_demos_noeduc <- svydesign(~1, data = pew, 
     #                               weights = weights(rake_demos_noeduc))
    
     rake_demos_weduc <- calibrate(design = pew_nowt,
                                  formula = formula_rake_demos_weduc,
                                  population = targets_rake_demos_weduc,
                                  calfun = "raking")

     rake_all_vars <- calibrate(design = pew_nowt,
                                  formula = formula_rake_all_vars,
                                  population = targets_rake_all_vars,
                                  calfun = "raking")
 
    #post stratification
    pew_ps <- suppressWarnings(svydesign(ids = ~1, 
                            data = pew %>% filter(!(strata %in% problem))))
    post_stratification <- postStratify(design = pew_ps,
                                        strata = ~strata,
                                        population = targets_ps)
    
     n_drop =  cces %>% filter(strata %in% missing_strata) %>% count() %>% pull()
     n_drop
    
    n_problem_drop = pew %>% filter(strata_reduc %in% problem_reduc) %>% count() %>% pull()
    if("post stratification" %in% specify_nonkpop) {
        cat(paste("PS drops",n_drop,
              "units or", round(n_drop/nrow(cces)*100, 2), "% of CCES units",
              "or", round(cces %>% filter(strata%in% missing_strata) %>% summarize(n_distinct(strata)) %>%
        pull()/n_distinct(cces$strata)*100, 2), "% of CCES strata\n",
              "and", n_problem_drop, "or", round(n_problem_drop/nrow(pew)*100,2), "%\ of pew units\n") )

    }
    
    #reduced
    pew_ps_reduc <- suppressWarnings(svydesign(ids = ~1, data = pew %>% 
                                      filter(!(strata_reduc %in% problem_reduc))))
    post_strat_reduc <- postStratify(design = pew_ps_reduc,
                                        strata = ~strata_reduc,
                                        population = targets_ps_reduc)
    
    
    n_reduc_drop =  cces %>% filter(strata_reduc %in% missing_strata_reduc) %>% count() %>% pull()
    #percent of strata dropped 
    
    
    n_problem_reduc_drop = pew %>% filter(strata_reduc %in% problem_reduc) %>% count() %>% pull()
    if("post strat_reduc" %in% specify_nonkpop) {
         cat(paste("PS (reduc) drops",n_reduc_drop, 
              "units or", round(n_reduc_drop/nrow(cces)*100, 2), "% of CCES units",
              "or", round(cces %>% filter(strata_reduc %in% missing_strata_reduc) %>% summarize(n_distinct(strata_reduc)) %>%
        pull()/n_distinct(cces$strata_reduc)*100, 2), "% of CCES strata_reduc\n", 
              "and", n_problem_reduc_drop, "or", round(n_problem_reduc_drop/nrow(pew)*100,2), "%\ of pew units\n") )
    }
   
    
    pew_ps_all <- suppressWarnings(svydesign(ids = ~1,  data = pew %>%
                                    filter(!(strata_all %in% problem_all))))
    post_strat_all <- postStratify(design = pew_ps_all,
                                        strata = ~strata_all,
                                        population = targets_ps_all)
    
    n_all_drop =  cces %>% filter(strata_all %in%missing_strata_all) %>% count() %>% pull()
    #percent of strata dropped 
    cces %>% filter(strata_all %in% missing_strata_all) %>% summarize(n_distinct(strata_all)) %>%
        pull()/n_distinct(cces$strata_all)
    
    n_problem_all_drop = pew %>% filter(strata_all %in% problem_all) %>% count() %>% pull()
    if("post strat_all" %in% specify_nonkpop) {
        cat(paste("PS (all) drops",n_all_drop,
              "units or", round(n_all_drop/nrow(cces)*100, 2), "% of CCES units",
              "or", round(cces %>% filter(strata_all %in% missing_strata_all) %>% summarize(n_distinct(strata_all)) %>%
        pull()/n_distinct(cces$strata_all)*100, 2), "% of CCES strata_all\n",
              "and", n_problem_all_drop, "or", round(n_problem_all_drop/nrow(pew)*100,2), "%\ of pew units\n") )
    }
    
    cat("NB: retrospective rake converges only to eps = 0.0068\n")
    rake_retrospective <- suppressWarnings(calibrate(design = pew_nowt,
                                    formula = formula_retrospective,
                                    population = targets_retrospective,
                                    calfun = "raking",
                                    force = TRUE))

    # kpop
    kpop <- svydesign(~1, data = pew,
                weights = kpop_w)

    kpop_conv <- svydesign(~1, data = pew,
                               weights = kpop_conv_w)
    
    kpop_mf <-  svydesign(~1, data = pew,
                              weights = kpop_mf_w)

    kpop_demos <-  svydesign(~1, data = pew,
                          weights = kpop_demos_w)
    
    kpop_demos_wedu <-  svydesign(~1, data = pew,
                          weights = kpop_demos_wedu_w)
     
    kpop_all <-  svydesign(~1, data = pew,
                          weights = kpop_all_w)
    
    ################################# Margins #################################
    if(eval_margins) { 
        if(is.null(margins_formula)) {
                margins_formula <- ~recode_vote_2016 +
                    mod_cces_on_pew_pD + mod_cces_on_pew_pR + mod_cces_on_pew_pO +
                    mod_pew_on_pew_pD + mod_pew_on_pew_pR + mod_pew_on_pew_pO + 
                    recode_pid_3way + 
                    recode_female + recode_race +recode_region + recode_educ +recode_relig_6way+
                    recode_born + recode_attndch_4way + recode_income_5way +
                    recode_age_bucket+recode_age+recode_agesq+recode_agecubed+recode_age_factor+
                    recode_race_educ_reg + recode_educ_wh_3way + 
                    recode_educ_pid_race +
                    recode_pid_race + 
                    recode_educ_pid +
                    recode_midwest_edu_race +
                    recode_midwest_wh_edu + 
                    recode_race_reg_wh_educ 
    
              margins_formula_cces <- ~recode_vote_2016 +
                mod_cces_on_cces_pD + mod_cces_on_cces_pR + mod_cces_on_cces_pO +
                mod_pew_on_cces_pD + mod_pew_on_cces_pR + mod_pew_on_cces_pO + 
                recode_pid_3way + 
                recode_female + recode_race +recode_region + recode_educ + recode_relig_6way + 
                recode_born + recode_attndch_4way + recode_income_5way +
                recode_age_bucket + recode_age +recode_agesq+recode_agecubed+recode_age_factor +
                recode_race_educ_reg + recode_educ_wh_3way + 
                recode_educ_pid_race +
                recode_pid_race + 
                recode_educ_pid +
                recode_midwest_edu_race +
                recode_midwest_wh_edu + 
                recode_race_reg_wh_educ 
        }
        
        margins <- round(cbind(
            pew = svymean(margins_formula, pew_nowt),
            cces_margins = svymean(margins_formula_cces, cces_svy, 
                                   na.rm =  TRUE),
            kpop = svymean(margins_formula, kpop),
            kpop_mf = svymean(margins_formula, kpop_mf),
            kpop_conv = svymean(margins_formula, kpop_conv),
            kpop_demos = svymean(margins_formula, kpop_demos),
            kpop_demos_wedu = svymean(margins_formula, kpop_demos_wedu),
            kpop_all = svymean(margins_formula, kpop_all),
            rake_demos_noeduc = svymean(margins_formula, rake_demos_noeduc),
            rake_demos_weduc = svymean(margins_formula, rake_demos_weduc),
            rake_all_vars = svymean(margins_formula, rake_all_vars),
            post_stratification = svymean(margins_formula, post_stratification),
            post_strat_reduc = svymean(margins_formula, post_strat_reduc),
            post_strat_all = svymean(margins_formula, post_strat_all),
            rake_retrospective = svymean(margins_formula, rake_retrospective)) * 100, 5)
        
        rownames(margins) <- gsub("recode_", "", rownames(margins))
        #we multiplied the recode_age margins by 100 unnecc above bc it' just a straight mean
        #so let's undo that
        margins["age",] <- margins["age",]/100 
        margins["agesq",] <- margins["agesq",]/100
        margins["agecubed",] <- margins["agecubed",]/100
    
        margins_diff <- as.data.frame(margins) %>% 
            mutate(pew = cces_margins - pew,
                   kpop = cces_margins - kpop,
                   kpop_mf = cces_margins - kpop_mf,
                   kpop_conv = cces_margins - kpop_conv,
                   kpop_demos = cces_margins - kpop_demos,
                   kpop_demos_wedu =cces_margins - kpop_demos_wedu,
                   kpop_all = cces_margins - kpop_all,
                   rake_demos_noeduc = cces_margins- rake_demos_noeduc,
                   rake_demos_weduc = cces_margins- rake_demos_weduc,
                   rake_all_vars = cces_margins - rake_all_vars,
                   post_stratification = cces_margins-  post_stratification,
                   post_strat_reduc = cces_margins-  post_strat_reduc,
                   post_strat_all = cces_margins-  post_strat_all,
                   rake_retrospective = cces_margins- rake_retrospective)
        rownames(margins_diff) <- rownames(margins)
        
        
        if(margins_pop_weighted_avg) {
            #weighting the difference by the proportion in that bin in cces
            #margins_diff is in percents, so it's the percent difference btwn the sample and the pop on each margin, we want tottake the averge abs value of this differnce, but we dont' just want the straight average, we want it weighted by the percent in that margin in the cces
            #so that means if we just multiply the idfference by the cces margin/100 we only need to sum them in wmabserr
            w_margins_diff <- margins_diff*(margins[, "cces_margins"]/100)
            #dont's square cces:
            w_margins_diff[, "cces_margins"] <- margins_diff[, "cces_margins"]
            #manugally fix the one level margins: then we'll just report the abs diff on these
            w_margins_diff["age",] <- margins_diff["age",]
            w_margins_diff["agesq",] <- margins_diff["agesq",]
            w_margins_diff["agecubed",] <- margins_diff["agecubed",]
    
            wmabserr <- w_margins_diff 
            wmabserr$var <- gsub("[A-Z].+$|[0-9][0-9]\\+?$|(?<=way).*[0-9]k?$|(?<=bucket).*[0-9]$|(?<=educ)[0-9].*$","",
                                 rownames(margins_diff), perl = T)
            wmabserr$var[wmabserr$var == "educ"]<- "educ_6way"
          
            wmabserr <- wmabserr %>% group_by(var) %>% 
                summarize(pew_unweighted = sum(abs(pew)), 
                                            kpop = sum(abs(kpop)),
                                            #kpop_conv = sum(abs(kpop_conv)), 
                                            #kpop_mf = sum(abs(kpop_mf)),
                                            kpop_demos = sum(abs(kpop_demos)),
                                            rake_demos_noeduc = sum(abs(rake_demos_noeduc)),
                                            kpop_demos_wedu = sum(abs(kpop_demos_wedu)),
                                            rake_demos_weduc = sum(abs(rake_demos_weduc)),
                                            kpop_all = sum(abs(kpop_all)),
                                            rake_all_vars = sum(abs(rake_all_vars)), 
                                            rake_retrospective = sum(abs(rake_retrospective)),
                                            #post_stratification =
                                            #    sum(abs(post_stratification)),
                                            post_strat_reduc = sum(abs(post_strat_reduc))
                                            #post_strat_all = sum(abs(post_strat_all)),
                                            )
        
        } else {
            #get cces proportions: for weighted L1 dist on age 
            margins_diff[(grep("age_factor", rownames(margins_diff))), ] <-
              (margins_diff[(grep("age_factor", 
                                  rownames(margins_diff))),
                            ])* (margins[grep("age_factor", rownames(margins)), "cces_margins"]/100)*length(levels(cces$recode_age_factor))
            
            wmabserr <- margins_diff 
            wmabserr$var <- gsub("[A-Z].+$|[0-9][0-9]\\+?$|(?<=way).*[0-9]k?$|(?<=bucket).*[0-9]$|(?<=educ)[0-9].*$","",
                                 rownames(margins_diff), perl = T)
            wmabserr$var[wmabserr$var == "educ"]<- "educ_6way"
            
            wmabserr <- wmabserr %>% 
                group_by(var) %>% summarize(pew_unweighted = mean(abs(pew)), 
                                        kpop = mean(abs(kpop)),
                                        #kpop_conv = mean(abs(kpop_conv)), 
                                        #kpop_mf = mean(abs(kpop_mf)),
                                        kpop_demos = mean(abs(kpop_demos)),
                                        rake_demos_noeduc = mean(abs(rake_demos_noeduc)),
                                        kpop_demos_wedu = mean(abs(kpop_demos_wedu)),
                                        rake_demos_weduc = mean(abs(rake_demos_weduc)),
                                        kpop_all = mean(abs(kpop_all)),
                                        rake_all_vars = mean(abs(rake_all_vars)), 
                                        rake_retrospective = mean(abs(rake_retrospective)),
                                        #post_stratification =
                                        #    mean(abs(post_stratification)),
                                        post_strat_reduc = mean(abs(post_strat_reduc))
                                        #post_strat_all = mean(abs(post_strat_all)),
                                        )
        }
        
    
        #labels
        if(pop_weights) {
            popw_lab = "w/ Pop Weights"
        } else {
            popw_lab = "No pop Weights"
        }
        tol_label = paste0(" tol=",as.character(tolerance))
        maxit_label = paste0( " maxit=", as.character(maxit))
        
        if(margins_pop_weighted_avg) {
            caption_m = paste0("W. Margins (Difference): Unscaled K ", "b=", round(b, 2),
                           popw_lab, " Age Buckets Only (no dnk) ",
                           tol_label, maxit_label)
            caption_o = paste0("Absolute Error on Weighted Margins of Outcomes: Unscaled K ","b=", 
                               round(b, 2),
                               popw_lab, " Age Buckets Only (no dnk) ",
                               tol_label, maxit_label)
            
            caption_err = paste0("Weighted Mean Abs Error: Unscaled K ","b=", 
                                 round(b, 2), popw_lab,
                                      " Age Buckets Only (no dnk) ", tol_label, maxit_label)   
            
        } else {
            caption_m = paste0("Margins (Difference): Unscaled K ", "b=", round(b, 2),
                           popw_lab, " Age Buckets Only (no dnk) ",
                           tol_label, maxit_label)
            caption_o = paste0("Absolute Error on Margins of Outcomes: Unscaled K ","b=", 
                               round(b, 2),
                               popw_lab, " Age Buckets Only (no dnk) ",
                               tol_label, maxit_label)
            
            caption_err = paste0("Mean Abs Error: Unscaled K ","b=", 
                                 round(b, 2), popw_lab,
                                      " Age Buckets Only (no dnk) ", tol_label, maxit_label)   
        }
        #var %in% c("agecubed") |
        
        wmabserr_nooutcomes <- wmabserr %>% 
            filter(!(grepl("xgb|mod|vote", var))) %>%
            arrange(nchar(var))
        if(is.null(margins_var_order)) {
            margins_var_order = c("female", "pid_3way", "age_bucket","race",  "region", "educ_6way",
                      "income_5way", "born",
                      "relig_6way", "attndch_4way",
                      "pid_race", "educ_pid",
                      "educ_pid_race", "race_educ_reg", "educ_wh_3way", "midwest_wh_edu",
                      "midwest_edu_race",
                      "agesq", "agecubed", "age_factor")
        }
        
        wmabserr_nooutcomes <- wmabserr_nooutcomes[as.numeric(sapply(margins_var_order, 
                                                                     function(x) which(wmabserr_nooutcomes$var == x))),]
        
        noedu_aes <- sapply(wmabserr_nooutcomes$var, function(x) {
                ifelse(grepl(x, as.character(formula_rake_demos_noeduc)[2]),
                       "gray", "black") })
        wedu_aes <-  sapply(wmabserr_nooutcomes$var, function(x) {
                ifelse(grepl(x, as.character(formula_rake_demos_weduc)[2]) | x == "educ_6way", "gray", "black")
            })
        all_aes <-  sapply(wmabserr_nooutcomes$var, function(x) {
                ifelse(grepl(x, as.character(formula_rake_all_vars)[2]) | x == "educ_6way", "gray", "black")
            })
        
        ps_aes <- sapply(wmabserr_nooutcomes$var, function(x) {
                ifelse(grepl(x, as.character(formula_ps)[2]), "gray", "black") })
        ps_reduc_aes <- sapply(wmabserr_nooutcomes$var, function(x) {
                ifelse(grepl(x, as.character(formula_ps_reduc)[2]), "gray", "black") })
        ps_all_aes <- sapply(wmabserr_nooutcomes$var, function(x) {
                ifelse(grepl(x, as.character(formula_ps_all)[2]), "gray", "black") })
        #interaction picks up race alone so back and fix bc does not include
        retro_aes <- sapply(wmabserr_nooutcomes$var, function(x) {
                ifelse(grepl(x, as.character(formula_retrospective)[2]) & x != "race", "gray", "black") })
        
        kpop_demos_aes <- noedu_aes
        kpop_demos_wedu_aes <- wedu_aes
        kpop_all_aes <- all_aes
        
        
        #dropping age:
        ps_reduc_aes_noage = ps_reduc_aes[1:(length(ps_reduc_aes) - 3)]
        retro_aes_noage =  retro_aes[1:(length(ps_reduc_aes) - 3)]
        noedu_aes_noage = noedu_aes[1:(length(ps_reduc_aes) - 3)]
        
        wedu_aes_noage = wedu_aes[1:(length(ps_reduc_aes) - 3)]
        all_aes_noage = all_aes[1:(length(ps_reduc_aes) - 3)]
        kpop_demos_aes_noage = kpop_demos_aes[1:(length(ps_reduc_aes) - 3)]
        kpop_demos_wedu_aes_noage = kpop_demos_wedu_aes[1:(length(ps_reduc_aes) - 3)]
        kpop_all_aes_noage = kpop_all_aes[1:(length(ps_reduc_aes) - 3)]
        
        #change name so its clear that recode_educ is 6 way and fixing some labels that are slighly off bc i apparently could not count when i named them/less cleaning in latex names
        wmabserr$var[wmabserr$var == "income_5way"]<- "income (6way)"
        wmabserr$var[wmabserr$var == "educ_6way"]<- "educ (6way)"
        wmabserr$var[wmabserr$var == "relig_6way"]<- "relig (5way)"
        wmabserr$var[wmabserr$var == "educ_wh_3way"]<- "educ (3way))$\times$white"
        wmabserr$var[wmabserr$var == "race"]<- "race/ethnicity"
        wmabserr$var[wmabserr$var == "pid_3way"]<- "pid (3way)"
        wmabserr$var[wmabserr$var == "age_bucket"]<- "age (4way)"
        
        wmabserr_nooutcomes$var[wmabserr_nooutcomes$var == "income_5way"]<- "income (6way)"
        wmabserr_nooutcomes$var[wmabserr_nooutcomes$var == "educ_6way"]<- "educ (6way)"
        wmabserr_nooutcomes$var[wmabserr_nooutcomes$var == "relig_6way"]<- "religion (5way)"
        wmabserr_nooutcomes$var[wmabserr_nooutcomes$var == "attndch_4way"]<- "church attnd. (4way)"
        wmabserr_nooutcomes$var[wmabserr_nooutcomes$var == "race"]<- "race/ethnicity (4way)"
        wmabserr_nooutcomes$var[wmabserr_nooutcomes$var == "pid_3way"]<- "pid (3way)"
        wmabserr_nooutcomes$var[wmabserr_nooutcomes$var == "region"]<- "region (4way)"
        wmabserr_nooutcomes$var[wmabserr_nooutcomes$var == "born"]<- "born-again (bin)"
        wmabserr_nooutcomes$var[wmabserr_nooutcomes$var == "age_bucket"]<- "age (4way)"
        wmabserr_nooutcomes$var[wmabserr_nooutcomes$var == "educ_wh_3way"]<- "educ$\\times$white"
        wmabserr_nooutcomes$var[wmabserr_nooutcomes$var == "midwest_wh_edu"]<- "midwest$\\times$white$\\times$educ"
        wmabserr_nooutcomes$var[wmabserr_nooutcomes$var == "age_factor"]<- "age (factor)"
        
        kable_prep = wmabserr_nooutcomes
        kable_prep = structure(data.frame(kable_prep[,-1]), 
                               class = "data.frame") 
        old_colnames = colnames(wmabserr_nooutcomes)
        rownames(kable_prep) = wmabserr_nooutcomes$var
        rownames(kable_prep) =  str_replace_all(rownames(kable_prep),"_", "$\\\\times$")
        colnames(kable_prep) <- linebreak(c(#"\nVariable",
                                          "Pew\n Orig",
                                          "kpop",
                                          "kpop + MF:\n(Demos)",
                                          "Mean Calib:\n(Demos)",
                                          "kpop + MF:\n(D+Edu)",
                                          "Mean Calib:\n(D+Edu)",
                                          "kpop + MF:\n(All)",
                                          "Mean Calib:\n(All)",
                                          "Mean Calib:\n(Retro)",
                                          "Post-Strat\n(Reduc)"))
        
        #drop age variables
        kable_err <- kable(kable_prep[1:(nrow(kable_prep) - 3),],
                                   format = "latex",
                                   caption = caption_err,
                                   booktabs = T,
                                    escape = F,
                                   digits = 2) %>% kable_styling() %>%
                            column_spec(which(old_colnames == "kpop_demos"),
                                    color =kpop_demos_aes_noage) %>%
                            column_spec(which(old_colnames ==
                                                  "rake_demos_noeduc"),
                                    color = noedu_aes_noage) %>%
                            column_spec(which(old_colnames ==
                                                  "kpop_demos_wedu"),
                                    color = kpop_demos_wedu_aes_noage) %>%
                            column_spec(which(old_colnames ==
                                                  "rake_demos_weduc"),
                                    color = wedu_aes_noage) %>%
                            column_spec(which(old_colnames == "rake_all_vars"),
                                    color = all_aes_noage) %>%
                            column_spec(which(old_colnames == "kpop_all"),
                                    color =kpop_all_aes_noage) %>%
                            column_spec(which(old_colnames ==
                                                  "rake_retrospective"),
                                    color =retro_aes_noage) %>% 
                            column_spec(which(old_colnames ==
                                                  "post_strat_reduc"),
                                        color =ps_reduc_aes_noage)
    
         kable_om <- kable(wmabserr %>% 
                               filter( grepl("mod|vote", var)) %>%
                               arrange(nchar(var)),
                               format = "latex",
                               caption = caption_o,
                               booktabs = T,
                               digits = 2)
            
        #dropping outcomes        
        margins_out <- margins_diff[-c(1:9),]
        margins_out <- margins_out[!grepl("age_factor", rownames(margins_out)), ] 
        # margins_out <- margins_out %>% rbind(colMeans(margins_out))
        # rownames(margins_out)[nrow(margins_out)] <- "Column Average"
    } else {
        kable_om = NULL
        kable_err = NULL
        margins_out = NULL
    }
    
    ##################################### Plot Prep
    #this will be structured to take a single choice of
    df_build <- function(var_orig, var_cces, var_pew, vote_form = vote_diff,
                         real = FALSE) {
        if(!real) {
          df <- data.frame(
            cces_orig = svycontrast(svymean(as.formula(paste0("~", var_orig)), 
                                            cces_svy, na.rm = TRUE),
                                    vote_form),
            #this is cces modeled outcome on cces
            cces_mod = svymean(as.formula(paste0("~", var_cces)), cces_svy, na.rm = TRUE),
            
            #outcome = modeled cces predicted with pew (cces on pew)
            unweighted = svymean(as.formula(paste0("~", var_pew)), pew_nowt,
                                 na.rm = TRUE),
            pew_weighted = svymean(as.formula(paste0("~", var_pew)), pew_awt, 
                                   na.rm = TRUE),
            rake_demos_noeduc = svymean(as.formula(paste0("~", var_pew)), 
                                        rake_demos_noeduc, na.rm = TRUE),
            rake_demos_weduc = svymean(as.formula(paste0("~", var_pew)), 
                                       rake_demos_weduc, na.rm = TRUE),
            rake_all_vars = svymean(as.formula(paste0("~", var_pew)), 
                                       rake_all_vars, na.rm = TRUE),
            post_stratification = svymean(as.formula(paste0("~", var_pew)), 
                                          post_stratification,
                                          na.rm = TRUE),
            post_strat_reduc = svymean(as.formula(paste0("~", var_pew)), 
                                          post_strat_reduc,
                                          na.rm = TRUE),
            post_strat_all = svymean(as.formula(paste0("~", var_pew)), 
                                          post_strat_all,
                                          na.rm = TRUE),
            rake_retrospective = svymean(as.formula(paste0("~", var_pew)),
                                         rake_retrospective, 
                                         na.rm = TRUE),
            kpop = svymean(as.formula(paste0("~", var_pew)), kpop, 
                                 na.rm = TRUE),
            kpop_conv = svymean(as.formula(paste0("~", var_pew)), kpop_conv,
                                      na.rm = TRUE),
            kpop_amf = svymean(as.formula(paste0("~", var_pew)), kpop_mf, 
                                    na.rm = TRUE),
            
            kpop_demos_mf =svymean(as.formula(paste0("~", var_pew)), kpop_demos,
                                  na.rm = TRUE),
            kpop_demos_wedu_mf =svymean(as.formula(paste0("~", var_pew)), 
                                       kpop_demos_wedu, na.rm = TRUE),
            kpop_all_mf = svymean(as.formula(paste0("~", var_pew)), 
                                      kpop_all, na.rm = TRUE)
            ) %>%
    pivot_longer(cols = everything(),
                         names_to = c("source", ".value"), 
                         names_pattern = "(.*)\\.(.*)") 
          
            df$SE <- coalesce(df[[var_cces]], df[[var_pew]], df$SE)
            df <- df %>% mutate(est = coalesce(nlcon, mean))
        } else {
            df <- data.frame(
                cces_orig = svycontrast(svymean(~recode_vote_2016, 
                                                cces_svy, na.rm = TRUE),
                                        vote_form),
                #outcome = modeled cces predicted with pew (cces on pew)
                unweighted = svycontrast(svymean(~recode_vote_2016, 
                                                 pew_nowt, na.rm = TRUE),
                                         vote_form),
                pew_weighted = svycontrast(svymean(~recode_vote_2016, 
                                                   pew_awt, na.rm = TRUE),
                                           vote_form),
                
                rake_demos_noeduc = svycontrast(svymean(~recode_vote_2016, 
                                                        rake_demos_noeduc, na.rm = TRUE),
                                                vote_form),
                rake_demos_weduc = svycontrast(svymean(~recode_vote_2016, 
                                                       rake_demos_weduc, na.rm = TRUE),
                                               vote_form),
                rake_all_vars = svycontrast(svymean(~recode_vote_2016, 
                                                       rake_all_vars, na.rm = TRUE),
                                               vote_form),
                post_stratification = svycontrast(svymean(~recode_vote_2016, 
                                                          post_stratification,
                                                          na.rm = TRUE),
                                                  vote_form),
                post_strat_reduc = svycontrast(svymean(~recode_vote_2016, 
                                                          post_strat_reduc,
                                                          na.rm = TRUE),
                                                  vote_form),
                post_strat_all = svycontrast(svymean(~recode_vote_2016, 
                                                          post_strat_all,
                                                          na.rm = TRUE),
                                                  vote_form),
                rake_retrospective = svycontrast(svymean(~recode_vote_2016, 
                                                         rake_retrospective,
                                                         na.rm = TRUE),
                                                 vote_form),
            
                kpop= svycontrast(svymean(~recode_vote_2016,
                                                  kpop, na.rm = TRUE), vote_form),
                kpop_conv =svycontrast(svymean(~recode_vote_2016,
                                                  kpop_conv, na.rm = TRUE), vote_form),
                kpop_amf = svycontrast(svymean(~recode_vote_2016,
                                                  kpop_mf, na.rm = TRUE), vote_form),
                
                kpop_demos_mf = svycontrast(svymean(~recode_vote_2016,
                                                  kpop_demos, na.rm = TRUE), vote_form),
                kpop_demos_wedu_mf = svycontrast(svymean(~recode_vote_2016,
                                                  kpop_demos_wedu, na.rm = TRUE), vote_form),
                kpop_all_mf = svycontrast(svymean(~recode_vote_2016,
                                                  kpop_all, na.rm = TRUE), vote_form)
        ) %>%
                pivot_longer(cols = everything(),
                             names_to = c("source", ".value"), 
                             names_pattern = "(.*)\\.(.*)") 
            
            df <- df %>% rename(est = nlcon)
            
        }
        #df <- df %>% filter(!is.na(source))
        df <- df %>% 
            dplyr::select(source, est, SE) %>%
            mutate(est = est * 100,
                   SE = SE * 100,
                   #err_target = est - target_diff * 100,
                   source = str_replace(source, "_", " ")) %>% rename(SE_svy = SE)

        
        df$b <- NA
        df$b[grep("kpop", df$source) ]<- b
        df$MF <- "NA"
        df$MF[grep("mf", df$source) & !grep("amf", df$source)] <- "MF"
        df$MF[!grepl("mf", df$source) & grepl("kpop", df$source)]<- "No MF"
        df$aMF <- "NA"
        df$aMF[grep("amf", df$source)] <- "aMF"
        df$aMF[!grepl("amf", df$source) & grepl("kpop", df$source)]<- "No aMF"
        
        df$Conv <- "NA"
        df$Conv[!grepl("conv", df$source) & 
                              grepl("kpop", df$source)]<- "Conv Not Required"
        df$Conv[c(grep("conv", df$source),
                            grep("mf", df$source))] <- "Conv Required"
        df <- df %>% arrange(!is.na(b), b)
        df <- df %>% 
            mutate(source_name = factor(source, 
                                        levels = as.character(df$source) ,
                                        labels = c("CCES Orig",
                                                   if(!real){"CCES Modeled"},
                                                   "Pew Unweighted", 
                                                   "Pew Weights",
                                                   "Mean Calibration:\n (Demos)", 
                                                   "Mean Calibration:\n (Demos+Edu)", 
                                                   "Mean Calibration:\n (All)",
                                                   "Post-Strat:\n (former)", 
                                                   "Post-Stratification:\n (Reduc)",
                                                   "Post-Strat:\n (All)",
                                                   "Mean Calibration:\n (Retrospective)", 
                                                   "kpop",
                                                   "kpop Conv",
                                                   "kpop aMF",
                                                   "kpop+MF:\n (Demos)",
                                                   "kpop+MF:\n (Demos+Edu)",
                                                   "kpop+MF:\n (All)"
                                            )))
        df <- df %>% filter(!is.na(est))
        
        return(df)
    }
    
    comp_df_diff <- df_build(var_orig = "recode_vote_2016", 
                             var_cces = "diff_cces_on_cces",
                             var_pew = "diff_cces_on_pew")
    
    ####### adding new SEs to vote diff outcome 
    #(only have updated SEs for this outcome run in app_march_23.R) bc getting SEs for all outcomes requires running regressions on this outcome with the svd dims which is large and time consuming and since in the end we present only the vote diff outcome, I updated to only add the new SEs here
    #can get the SEs for other outcomes by changing "outcome" variable in app_march_23.R and rerunning
    #or saving the svd object and rerunning SEs running after the fact
    formula_null = ~1
    residuals = residuals(lm(update(formula_null, diff_cces_on_pew ~ .), 
                         data = rake_demos_noeduc$variables))
    
    rake_null_se <- calc_SEs(Y = pew$diff_cces_on_pew, 
                                 residuals = residuals, 
                                 pop_size = nrow(cces), 
                                 sample_size =nrow(pew),
                                 weights = rep(1, nrow(pew)))
    rownames(rake_null_se) = "pew unweighted"   
    rake_demos_noeduc_se <- calc_SEs(Y = rake_demos_noeduc$variables$diff_cces_on_pew, 
                             residuals = residuals(lm(update(formula_rake_demos_noeduc,
                                                             diff_cces_on_pew ~ .), 
                                                      data = rake_demos_noeduc$variables)), 
                             pop_size = nrow(cces), 
                             sample_size = nrow(pew),
                             weights = weights(rake_demos_noeduc))
    
    rake_demos_weduc_se <- calc_SEs(Y = rake_demos_weduc$variables$diff_cces_on_pew, 
                             residuals = residuals(lm(update(formula_rake_demos_weduc,
                                                             diff_cces_on_pew ~ .), 
                                                      data = rake_demos_weduc$variables)), 
                             pop_size = nrow(cces), 
                             sample_size = nrow(pew),
                             weights = weights(rake_demos_weduc))
    
    rake_demos_all_se <- calc_SEs(Y = rake_all_vars$variables$diff_cces_on_pew, 
                             residuals = residuals(lm(update(formula_rake_all_vars,
                                                              diff_cces_on_pew ~ .), 
                                                      data = rake_all_vars$variables)), 
                             pop_size = nrow(cces), 
                             sample_size = nrow(pew),
                             weights = weights(rake_all_vars))
    
    rake_retrospective_se <- calc_SEs(Y = rake_retrospective$variables$diff_cces_on_pew, 
                             residuals = residuals(lm(update(formula_retrospective,
                                                             diff_cces_on_pew ~ .), 
                                                      data = rake_retrospective$variables)), 
                             pop_size = nrow(cces), 
                             sample_size = nrow(pew),
                             weights = weights(rake_retrospective))
    
    SEs = rbind(rake_null_se,
                rake_demos_noedu = rake_demos_noeduc_se, 
                rake_demos_wedu = rake_demos_weduc_se,
                rake_all = rake_demos_all_se, 
                rake_retrospective = rake_retrospective_se, out$SEs)
    #these are not in percent, to match the svy package/convinience of plotting *100
    SEs = 100*SEs
    #make source column with matching names to comp_df to merge
    SEs = cbind(source = c("unweighted", "rake demos_noeduc", "rake demos_weduc", "rake all_vars",
                           "rake retrospective", 
                           "kpop", "kpop conv", "kpop amf", "kpop demos_mf", "kpop demos_wedu_mf",
                           "kpop all_mf"), SEs)
    
    source_row_order = matrix(comp_df_diff$source)
    comp_df_diff = merge(comp_df_diff, SEs, by = "source", all.x = T, all.y = T)
   
    comp_df_diff = comp_df_diff[ apply(source_row_order, 1, function(x) which(comp_df_diff$source == x)), c(1,2,3,9:12,4,5,6,7,8)]

    comp_df_margin <- df_build("recode_vote_2016", 
                               "margin_cces_on_cces",
                               "margin_cces_on_pew")  
    comp_df_pR <- df_build("recode_vote_2016", 
                           "mod_cces_on_cces_pR",
                           "mod_cces_on_pew_pR",
                            vote_form = quote((recode_vote_2016Republican  +recode_vote_2016Republican)/2 ))  
    comp_df_pD <- df_build("recode_vote_2016", 
                           "mod_cces_on_cces_pD",
                           "mod_cces_on_pew_pD",
                           vote_form = quote((recode_vote_2016Democrat +recode_vote_2016Democrat)/2 )) 
    comp_df_real <- df_build("recode_vote_2016", 
                           "recode_vote_2016",
                           "recode_vote_2016",
                           real = TRUE, 
                           vote_form = vote_contrast)
    comp_df_real_diff <-  df_build("recode_vote_2016", 
                           "recode_vote_2016",
                           "recode_vote_2016",
                           real = TRUE) 

    if(is.null(specify_nonkpop)) {
        specify_nonkpop = comp_df_diff$source
    }
    if(is.null(specify_kpop)) {
        specify_kpop = comp_df_diff$source[grepl("kpop",comp_df_diff$source)]
    } 
    comp_df_diff_all = comp_df_diff
    comp_df_diff <- comp_df_diff_all %>% 
       filter(source %in% specify_nonkpop | source %in% specify_kpop)
    comp_df_margin <- comp_df_margin %>% 
        filter(source %in% specify_nonkpop | source %in% specify_kpop)
    comp_df_pR <- comp_df_pR %>% 
        filter(source %in% specify_nonkpop | source %in% specify_kpop)
    comp_df_pD <- comp_df_pD %>% 
        filter(source %in% specify_nonkpop | source %in% specify_kpop)
    comp_df_real <- comp_df_real %>% 
        filter(source %in% specify_nonkpop | source %in% specify_kpop)
    comp_df_real_diff <- comp_df_real_diff %>%
        filter(source %in% specify_nonkpop | source %in% specify_kpop)
    #note that if you want plots of all the above with thingbs projected onto the lasso model fitted to pew outcomes its all basically the same and you can lift the code and copy paste rather than retyping from the app-results.Rmd from previously
 
    if(pop_weights) {
        popw_lab = "(w/Pop Weights)"
        mod_lab = "Lasso Modeled"
    } else {
        popw_lab = "(No Pop Weights)"
        mod_lab = "XGB Modeled"
    }
    pres <- readRDS(paste0(path_data, "election.rds"))
    
    natl_margin <- pres %>%
        summarise(margin = (sum(demtotal) - sum(reptotal)) /
                      (sum(demtotal) + sum(reptotal))) %>% as.numeric()
    natl_diff <- pres %>%
        summarise(margin = (sum(demtotal) - sum(reptotal)) /
                      (sum(totalvotes))) %>% as.numeric()
    natl_Rep <- pres %>%
        summarise(pR =  sum(reptotal) /
                      sum(totalvotes)) %>% as.numeric()
    natl_Dem <- pres %>%
        summarise(pR =  sum(demtotal) /
                      sum(totalvotes)) %>% as.numeric()
    
    ############Plots... let the horror begin!
    comp_df_real_margin_plot <- comp_df_real %>% filter(!str_detect(source, "cces"))
    comp_df_plot_real_margin <-
        ggplot() +
        aes(x = source_name, y = est, ymin = est - qnorm(.975)*SE_svy, ymax = est + qnorm(.975)*SE_svy) +
        
        geom_hline(yintercept = c(0, if(pop_weights) {natl_margin*100},
                                  comp_df_margin$est[comp_df_margin$source_name == "CCES Orig"]),
                   linetype = c("solid", if(pop_weights) {"dashed"}, "longdash"),
                   color = c("black", if(pop_weights){"gray60"}, "black")) +
        geom_pointrange(data = comp_df_real_margin_plot) +
        scale_y_continuous(breaks = c(natl_margin, seq(-5, 10, 5)),
                           minor_breaks = NULL,
                           labels = scales::percent_format(scale=1, accuracy = 0.1)) +
        theme_bw() +
        theme(plot.title = element_text(hjust = 0.5)) +
        
        labs(x = NULL, y = "Estimated Vote Margin (95% CI)", popw_lab) +
        ggtitle(paste("Pew on TRUE CCES Vote Margin", popw_lab, plot_b_lab)) +
        theme(axis.text.x = element_text(angle = 70, hjust = 1 )) +
        annotate(geom = "text", x = nrow(comp_df_real_margin_plot)+.35,
                 y = if(pop_weights){natl_margin * 100} else {comp_df_margin$est[comp_df_margin$source_name == "CCES Orig"] },
                 label = if(pop_weights) {" True\n National\n Margin"} else {""},
                 hjust = 0, angle = -90,
                 color = "gray60", size = 3) +
        annotate(geom = "text", x = nrow(comp_df_real_margin_plot)+.35,
                 y = comp_df_margin$est[comp_df_margin$source_name == "CCES Orig"],
                 label = if(pop_weights)" Weighted\n CCES\n Target" else {" Unweighted\n CCES\n Target"},
                 hjust = 0, angle = 90, size = 3) +
        #for spacing
         annotate(geom = "text", x = nrow(comp_df_real_margin_plot)+1,
                 y = comp_df_margin$est[comp_df_margin$source_name == "CCES Orig"],
                 label = " ",
                 hjust = 0, angle = 90, size = 3) +
        theme(legend.title = element_blank())
    
    comp_df_real_diff_plot <- comp_df_real_diff %>% filter(!str_detect(source, "cces"))
    comp_df_plot_real_diff <-
        ggplot() +
        aes(x = source_name, y = est, ymin = est - qnorm(.975)*SE_svy, ymax = est + qnorm(.975)*SE_svy)  + 
        
        geom_hline(yintercept = c(0, if(pop_weights){natl_diff*100},
                                  comp_df_real_diff$est[comp_df_real_diff$source_name
                                                        =="CCES Orig"]),
                   linetype = c("solid", if(pop_weights){"dashed"}, "longdash"),
                   color = c("black", if(pop_weights) {"gray60"}, "black")) +
        geom_pointrange(data = comp_df_real_diff_plot) +
        scale_y_continuous(breaks = c(natl_diff*100, seq(-5, 10, 5)),
                           minor_breaks = NULL,
                           labels = scales::percent_format(scale=1, accuracy = 0.1)) +
        theme_bw() +
        theme(plot.title = element_text(hjust = 0.5)) +
        
        labs(x = NULL, y = "Estimated Vote Difference (95% CI)") +
        ggtitle(paste("Pew on TRUE CCES Vote Difference",  
                      popw_lab, plot_b_lab)) +
        theme(axis.text.x = element_text(angle = 70, hjust = 1)) +
        annotate(geom = "text", 
                 x = nrow(comp_df_real_diff_plot) +.35,
                 y = if(pop_weights) {natl_diff * 100} else {comp_df_real_diff$est[comp_df_real_diff$source_name == 
                                               "CCES\ Orig"]},
                 label = if(pop_weights){" True\n National\n Diff"} else {""},
                 hjust = 0, angle = -90,
                 color = "gray60", size = 3) +
        annotate(geom = "text", x = nrow(comp_df_real_diff_plot) +.35,
                 y = comp_df_real_diff$est[comp_df_real_diff$source_name == 
                                               "CCES\ Orig"],
                 label = if(pop_weights)" Weighted\n CCES\n Target" else {" Unweighted\n CCES\n Target"},
                 hjust = 0, angle = 90, size = 3) +
        #for spacing
         annotate(geom = "text", x = nrow(comp_df_real_diff_plot) +1,
                 y = comp_df_real_diff$est[comp_df_real_diff$source_name == 
                                               "CCES Orig"],
                 label = "",
                 hjust = 0, angle = 90, size = 3) +
        theme(legend.title = element_blank())
    
    
    ######### main vote diff plot #########
    comp_df_diff_plot <- comp_df_diff %>% filter(!str_detect(source, "cces")) %>% 
    mutate(method =  factor(case_when(str_detect(source, "unweighted") ~ "Raw Survey", 
                               str_detect(source, "rake") ~ "Mean Calibration",
                               str_detect(source, "post") ~ "Post-Strat",
                               str_detect(source, "kpop") ~ "kpop", 
                               TRUE ~ NA_character_),
                            levels = c("Raw Survey", "Mean Calibration", "Post-Strat", "kpop")),
           zero = 0,
           natl_diff =natl_diff*100,
           cces_target = comp_df_diff$est[comp_df_diff$source_name == target],
           plot_SE = case_when(str_detect(source, "unweighted") ~ SE_svy, 
                               str_detect(source, "rake") ~ SE_linear,
                               str_detect(source, "post") ~ SE_svy,
                               str_detect(source, "kpop") ~ SE_linear, 
                               TRUE ~ -99))

    label_pos = c(length(specify_kpop) +.5, length(specify_kpop) + .5, length(specify_kpop) + 1)
    text_for_gg <- data.frame(source_name =  label_pos,
                          method =factor("kpop", levels(comp_df_diff_plot$method)),
                          est = c(comp_df_diff_plot$natl_diff[1], 
                                  comp_df_diff_plot$cces_target[1], 0),
                          label = c(" True\n National\n Diff", 
                                    " Weighted\n CCES\n Target", " "))

    #UPDATED TO SE LINEAR = linearization SEs for the main plot; old was SE_svy
    cat("NB: plot_diff combines linearization SEs for raking, kpop, and PS with HT SEs for the unweighted pew \n")
    comp_df_plot_diff <- ggplot(comp_df_diff_plot) +
        geom_pointrange(aes(x = source_name, 
                            y = est, 
                            ymin = est - qnorm(.975)*plot_SE, 
                            ymax = est + qnorm(.975)*plot_SE)) +
        facet_grid(cols = vars(method),  scales = "free_x", space = "free_x") +
        geom_hline(aes(yintercept = zero)) +
        geom_hline(aes(yintercept = natl_diff), linetype = 2, color = "grey60") +
        geom_hline(aes(yintercept = cces_target), linetype = 2) +
       
        scale_y_continuous(breaks = c(natl_diff*100, seq(-5, 10, 5)),
                           minor_breaks = NULL,
                           labels = scales::percent_format(scale=1, accuracy = 0.1)) +
        theme_bw() +
        theme(plot.title = element_text(hjust = 0.5)) +
        labs(x = NULL, y = "Estimated Retrospective Vote Difference (95% CI)") +
        theme(axis.text.x = element_text(angle = 70, hjust = 1)) +
        geom_text(data = text_for_gg, aes(x = source_name, 
                                          y = est,
                                          label = label), 
                  angle = c(-90,90, 90), color = c("grey60", "black", "purple"),
                  hjust = 0, size = 2.6) +
        theme()
    
    ######### CIS
    
    comp_df_diff_all <- comp_df_diff_all %>% mutate(
         plot_SE = case_when(str_detect(source, "weighted|cces|weighted") ~ SE_svy, 
                               str_detect(source, "rake") ~ SE_linear,
                               str_detect(source, "post") ~ SE_svy,
                               str_detect(source, "kpop") ~ SE_linear, 
                               TRUE ~ -99))
    
    CIs_diff <- comp_df_diff_all %>% mutate(CI_low = est - qnorm(.975)*plot_SE, 
                                             CI_high = est+ qnorm(.975)*plot_SE, 
                                             CI_width = CI_high - CI_low) %>% 
    dplyr::select(source, est, CI_low, CI_high, CI_width, plot_SE, SE_svy, SE_linear)
    
    CIs_diff =  CIs_diff %>% dplyr::select(source, est, plot_SE, CI_low, CI_high, CI_width, SE_linear, SE_svy)
    #movign raking retrospective in with all the other raking
  
    #first get rake retrospective with other raking    
    order = comp_df_diff_all$source[c(1:7,11,8:10, 12:nrow(comp_df_diff_all))]
    order
    #now subset to only methods specified in input
    specify_nonkpop_nocces = specify_nonkpop[!grepl("cces",specify_nonkpop)]
    targ_order = comp_df_diff_all[comp_df_diff_all$source_name == target, "source"]
    order = order[(order %in% specify_nonkpop_nocces | order %in% specify_kpop | order == targ_order)]
    kable_pass = CIs_diff[as.numeric(sapply(order, function(x) which(CIs_diff$source == x))),2:5]

    all_rname = comp_df_diff_all[as.numeric(sapply(order, function(x) which(CIs_diff$source == x))),"source_name"]
    all_rname
    all_rname = gsub("\\n|\\(|\\)", "", all_rname)
    all_rname = gsub("Demos\\+Edu", "D\\+Edu", all_rname)
    all_rname = gsub("Demos$", "Demographics", all_rname)
    all_rname = gsub("Reduc$", "Reduced", all_rname)
    all_rname = gsub("\\+MF", " \\+ MF", all_rname)
    all_rname = paste0("\\hspace{1em}", all_rname)
    all_rname[1] = "\\textbf{CCES Target}"
    rownames(kable_pass) = all_rname
    colnames(kable_pass) = c("Estimate", "SE", "CI Lower", "CI Upper")
    
    kable_diff_CI <- kable(kable_pass,
                           escape = F,
                        format = "latex", 
                        booktabs = T,
                        caption = "Performance on Modeled p(D) - p(R) Vote Difference among Various Weighting Methods",
                        digits = 2)
    
    
    kable_SE_pass = comp_df_diff %>% dplyr::select(source_name, est, SE_svy, SE_fixed, SE_linear, SE_quasi, SE_chad)
    kable_diff_allSEs <- kable(kable_SE_pass, 
                        format = "latex", 
                        booktabs = T,
                        caption = "Comparison of SE Estimators across Methods (in Percent)",
                        digits = 2)
    
    
    ########### TEMP: View ALL SEs in One Big Plot
    gg_unravel = rbind(comp_df_diff_plot, 
                   comp_df_diff_plot, 
                   comp_df_diff_plot, 
                   comp_df_diff_plot, 
                   comp_df_diff_plot) %>% dplyr::select(source, est, method,
                                                 source_name, 
                                                 zero, natl_diff, cces_target)  %>% 
    mutate(SE = c(comp_df_diff_plot$SE_svy, 
                      comp_df_diff_plot$SE_fixed,
                      comp_df_diff_plot$SE_quasi, 
                      comp_df_diff_plot$SE_linear, 
                      comp_df_diff_plot$SE_chad), 
           SE_method = as.factor(rep(c("Svy Pkg", "Fixed", "Quasi-Poisson", "Linear", "Chad"),
                           each = nrow(comp_df_diff_plot)) ))

    gg_unravel[grepl("pew|strat|unweighted", gg_unravel$source) & is.na(gg_unravel$SE), "est"] = NA
    
    if(pop_weights) {
        text_pass = " Weighted\n CCES\n Target"
    } else {
        text_pass = " Unweighted\n CCES\n Target"
    }
    text_for_gg <- data.frame(source_name =  c(.8, .8, 2),
                              method =factor("Raw Survey", levels(comp_df_diff_plot$method)),
                              est = c(comp_df_diff_plot$natl_diff[1], 
                                      comp_df_diff_plot$cces_target[1], 0),
                              label = c(" True\n National\n Diff", 
                                        text_pass, " "))


    comp_df_plot_diff_allSEs <-ggplot(gg_unravel) +
    geom_pointrange(aes(x = source_name, 
                        y = est, 
                        ymin = est - qnorm(.975)*SE, 
                        ymax = est + qnorm(.975)*SE, color = SE_method), 
                    position = position_dodge(width = .8)) +
    facet_grid(cols = vars(method),  scales = "free_x", space = "free_x") +
    geom_hline(aes(yintercept = zero)) +
    geom_hline(aes(yintercept = natl_diff), linetype = 2, color = "grey60") +
    geom_hline(aes(yintercept = cces_target), linetype = 2) +
    
    scale_y_continuous(breaks = c(natl_diff*100, seq(-5, 10, 5)),
                       minor_breaks = NULL,
                       labels = scales::percent_format(scale=1, accuracy = 0.1)) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = NULL, y = "Estimated Retrospective Vote Difference (95% CI)") +
    theme(axis.text.x = element_text(angle = 70, hjust = 1)) +
    labs(color= "SE Method") + 
    geom_text(data = text_for_gg, aes(x = source_name, 
                                      y = est,
                                      label = label), 
              angle = c(-90,90, 90), color = c("grey60", "black", "purple"),
              hjust = 0, size = 2.6) +
    theme()

    ### XXX ADD Final Plot with what alt SEs want to use.
    comp_df_margin_plot <- comp_df_margin %>% filter(!str_detect(source, "cces")) 
    comp_df_plot_margin <-
        ggplot() +
        aes(x = source_name,
            y = est, 
            ymin = est - qnorm(.975)*SE_svy, ymax = est + qnorm(.975)*SE_svy) +
        geom_hline(yintercept = c(0, 
                                  if(pop_weights) {natl_margin*100},
                                 # if(pop_weights) {comp_df_margin$est[comp_df_margin$source_name == "CCES Orig"]},
                                  comp_df_margin$est[comp_df_margin$source_name == "CCES Modeled"]),
                   linetype = c("solid", 
                                if(pop_weights) {"dashed"},
                                #if(pop_weights) {"longdash"},
                                "dashed"),
                   color = c("black", 
                             if(pop_weights) {"gray60"},
                             #if(pop_weights){"black"},
                             "black")) +
        geom_pointrange(data =  comp_df_margin_plot) +
        scale_y_continuous(breaks = c(natl_margin, seq(-5, 10, 5)),
                           minor_breaks = NULL,
                           labels = scales::percent_format(scale=1, accuracy = 0.1)) +
        theme_bw() +
        theme(plot.title = element_text(hjust = 0.5)) +
        
        labs(x = NULL, y = "Estimated Modeled Vote Margin (95% CI)") +
        ggtitle(paste("Pew on CCES", mod_lab, "Mean Indiv Vote Margin",popw_lab,
                      plot_b_lab)) +
        theme(axis.text.x = element_text(angle = 70, hjust = 1)) +
         annotate(geom = "text", 
                  x = nrow(comp_df_margin_plot)+.35, 
                 y = if(pop_weights) {natl_margin * 100} else {comp_df_margin$est[comp_df_margin$source_name == "CCES Modeled"]},
                 label = if(pop_weights) {" True\n National\n Margin"} else {""},
                 hjust = 0, angle = -90,
                 color = "gray60", size = 3) +
        annotate(geom = "text", 
                 x =  nrow(comp_df_margin_plot)+.35,
                 y = comp_df_margin$est[comp_df_margin$source_name == "CCES Modeled"],
                 label = " CCES\n Modeled Target",
                 color = "black",
                 hjust = 0, angle = 90, size = 3) +
        #for spacing
        annotate(geom = "text",
                 x = nrow(comp_df_margin_plot)+1,
                 y = comp_df_margin$est[comp_df_margin$source_name == "CCES Modeled"],
                 label = "",
                 color = "purple",
                 hjust = 0, angle = -90, size = 3) +
        
        theme(legend.title = element_blank())
    
    
    ####### p(R) plot
    comp_df_pR_plot <- comp_df_pR %>% filter(!str_detect(source, "cces")) 
    comp_df_plot_both_pR <-
        ggplot() +
        aes(x = source_name, y = est, ymin = est - qnorm(.975)*SE_svy, ymax = est + qnorm(.975)*SE_svy) +
        
        geom_hline(yintercept = c(if(pop_weights) {natl_Rep*100},
                                  # if(pop_weights) {comp_df_pR$est[comp_df_pR$source_name == "CCES Orig"]},
                                  comp_df_pR$est[comp_df_pR$source_name == "CCES Modeled"]),
                   linetype = c( if(pop_weights) {"dashed"}, 
                                 #if(pop_weights){"longdash"}, 
                                 "dashed"),
                   color = c(if(pop_weights) {"gray60"},
                             #if(pop_weights) {"black"},
                             "black")) +
        geom_pointrange(data = comp_df_pR_plot) +
       # geom_pointrange(data = comp_df_pR_pewoutcome, alpha = 0.4) +
        scale_y_continuous(breaks = c(natl_Rep, seq(40, 48, 2)),
                           minor_breaks = NULL,
                           labels = scales::percent_format(scale=1, accuracy = 0.1)) +
        theme_bw() +
        theme(plot.title = element_text(hjust = 0.5)) +
        
        labs(x = NULL, y = "Estimated Modeled Vote p(R) (95% CI)") +
        ggtitle(paste("Pew on CCES", mod_lab,  "p(R) modeled",
                     popw_lab, plot_b_lab)) +
        theme(axis.text.x = element_text(angle = 70, hjust = 1)) +
        annotate(geom = "text", 
                 x = nrow(comp_df_pR_plot)+.35, 
                 y = if(pop_weights) {natl_Rep * 100} else {comp_df_pR$est[comp_df_pR$source_name == "CCES Modeled"]},
                 label = if(pop_weights) {" True\n National\n % Rep"} else {""},
                 hjust = 0, angle = +90,
                 color = "gray60", size = 3) +
        annotate(geom = "text",
                 x = nrow(comp_df_pR_plot)+.35,
                 y = comp_df_pR$est[comp_df_pR$source_name == "CCES Modeled"],
                 label = " CCES\n Modeled Target",
                 color = "black",
                 hjust = 0, angle = -90, size = 3) +
        #for spacing
        annotate(geom = "text", 
                 x = nrow(comp_df_pR_plot)+1,
                 y = comp_df_pR$est[comp_df_pR$source_name == "CCES Modeled"],
                 label = "",
                 color = "purple",
                 hjust = 0, angle = -90, size = 3) +
        theme(legend.title = element_blank())
    
    
    ###### p(D) plot
    comp_df_pD_plot <- comp_df_pD %>% filter(!str_detect(source, "cces")) 
    
    comp_df_plot_both_pD <-
        ggplot() +
        aes(x = source_name, y = est, ymin = est - qnorm(.975)*SE_svy, ymax = est + qnorm(.975)*SE_svy) +
        
        geom_hline(yintercept = c(if(pop_weights) {natl_Dem*100},
                                  #if(pop_weights) {comp_df_pD$est[comp_df_pD$source_name == "CCES Orig"]},
                                  comp_df_pD$est[comp_df_pD$source_name == "CCES Modeled"]),
                   linetype = c( if(pop_weights) {"dashed"}, 
                                 #if(pop_weights){"longdash"}, 
                                 "dashed"),
                   color = c(if(pop_weights) {"gray60"},
                             #if(pop_weights) {"black"},
                             "black")) +
        geom_pointrange(data = comp_df_pD_plot ) +
        scale_y_continuous(breaks = c(natl_Dem*100, seq(40, 56, 4)),
                           minor_breaks = NULL,
                           labels = scales::percent_format(scale=1, accuracy = 0.1)) +
        theme_bw() +
        theme(plot.title = element_text(hjust = 0.5)) +
        
        labs(x = NULL, y = "Estimated Modeled Vote p(R) (95% CI)") +
        ggtitle(paste("Pew on CCES", mod_lab, "p(D) modeled",
                      popw_lab, plot_b_lab)) +
        theme(axis.text.x = element_text(angle = 70, hjust = 1)) +
        annotate(geom = "text", 
                 x = nrow(comp_df_pD_plot)+.35,
                 y = if(pop_weights) {natl_Dem * 100} else {comp_df_pD$est[comp_df_pD$source_name == "CCES Orig"]},
                 label = if(pop_weights){" True\n National\n % Rep"} else {""},
                 hjust = 0, angle = -90,
                 color = "gray60", size = 3) +
        annotate(geom = "text", 
                 x = nrow(comp_df_pD_plot)+.35,
                 y = comp_df_pD$est[comp_df_pD$source_name == "CCES Modeled"],
                 label = " CCES\n Modeled Target",
                 color = "black",
                 hjust = 0, angle = 90, size = 3) +
        annotate(geom = "text",
                 x = nrow(comp_df_pD_plot)+1,
                 y = comp_df_pD$est[comp_df_pD$source_name == "CCES Modeled"],
                 label = "",
                 color = "purple",
                 hjust = 0, angle = 90, size = 3) +
        theme(legend.title = element_blank() )

    
   
#     kable_cols_string = c("& Pew & kpop & kpop + MF:& Mean Calib: & kpop + MF: & Mean Calib: & kpop + MF: & Mean Calib:& Mean Calib:& PS \\
# Variable & Orig &  & (Demos) & (Demos) & (D+Edu) & (D+Edu) & (All) & (All) & Retro & Reduc\\")
    
    out <- list(plot_diff = comp_df_plot_diff,
                plot_diff_allSEs = comp_df_plot_diff_allSEs,
                plot_margin = comp_df_plot_margin,
                plot_pR = comp_df_plot_both_pR,
                plot_pD = comp_df_plot_both_pD,
                plot_real_margin = comp_df_plot_real_margin,
                plot_real_diff = comp_df_plot_real_diff,
                margins = margins,
                w_margins_diff = w_margins_diff,
                margins_diff = margins_diff,
                wmabserr = wmabserr,
                wmabserr_nooutcomes = wmabserr_nooutcomes,
                kable_err = kable_err,
                #kable_cols_string = kable_cols_string,
                kable_outmom = kable_om,
                problem = problem,
                problem_reduc = problem_reduc,
                problem_all = problem_all,
                comp_df_diff = comp_df_diff,
                comp_df_diff_all = comp_df_diff_all,
                comp_df_margin = comp_df_margin,
                comp_df_pR = comp_df_pR,
                comp_df_pD = comp_df_pD, 
                comp_df_real_margin = comp_df_real,
                comp_df_real_diff = comp_df_real_diff, 
                kable_diff = kable_diff_CI,
                kable_diff_allSEs = kable_diff_allSEs,
                CIs_diff_plot = CIs_diff, 
                gg_unravel = gg_unravel)
    return(out)
}


```




```{r run_res_main, echo = F}
test = main_res_plot(weights_file = weights_file, 
                     target = "true vote choice",
                    specify_nonkpop = c("cces orig", "cces mod", 
                                              "unweighted",
                                              #"pew unweighted",
                                              "rake demos_noeduc", "rake demos_weduc", "rake all_vars",
                                             #"post stratification", 
                                              "post strat_reduc",
                                            # "post strat_all",
                                             "rake retrospective"),
                    specify_kpop = c("kpop", 
                                     #"kpop conv", 
                                     "kpop demos_mf", "kpop demos_wedu_mf", "kpop all_mf"
                                     #,"kpop amf"
                                     )
                  )
test$comp_df_diff
test$plot_diff

#test$comp_df_diff_all
test$CIs_diff_plot
test$kable_diff
test$comp_df_diff_all
test$kable_diff
test$plot_diff
test$comp_df_diff_p
test$comp_df_pD

test$kable_err
#1) fix age^2 in the margins tables for the sims
#2) do we want ot include aMF and if so why tf is it EXACTLY the same as mf +all that seems wrong
test$CIs_diff_plot
test$kable_diff

test$plot_diff
test$gg_unravel
test$comp_df_diff
test$kable_err
test$kable_outmom
test$plot_real_diff


# POPW
# #ok so the the implicit two stage helped fix the rake SEs to match w linearization at least
# test$comp_df_diff %>% mutate(SE_check = round(SE_svy,6) == round(SE_linear,6)) %>% select(source, est, SE_check, SE_svy, SE_linear)
#still fucked for Kpop so this makes me wonder again if there's something wrong with the allprob param

#test$plot_diff_allSEs

test$plot_diff
ggsave("/Users/Ciara_1/Dropbox/kpop/2023/application/plots/app_votediff_aMF_linSEs_targetTruevote.pdf",
      width = 8.5, height = 4.5)
# test$kable_diff
test$kable_diff_allSEs
#test$comp_df_real_diff
#svycontrast(svymean(~recode_vote_2016, svydesign(~1, weights = ~1, data = cces)), vote_diff)*100

```


\clearpage

```{r plot_fig, echo = F, fig.align = 'center', fig.width = 14, fig.height = 9}

test$plot_diff_allSEs



```

